### ISSUE TITLE
Error in QoS>Basic Settings page on IE11 Windows 7 x64

### ISSUE THREAD

**Issue by AndreDVJ** [Jackysi/advancedtomato#1]
Hello Jacky,

Even on the latest AT release 2.01 (with the new bouncing animation when you expand/collapse the menu), I still get the error on the QoS page. Please check attached screenshot.

Google Chrome works fine. I know IE has a history of not being "developer friendly", though it's my most used web browser.

My router is a Netgear WNR3500L v2.

![image](https://cloud.githubusercontent.com/assets/8248926/3677690/f0dca358-1293-11e4-9364-84bd51e7e2d3.png)

**Comment by Jackysi** [comment]
I will look into this issue, I got rid of it on other pages, but I didn't know there is the same issue on QOS page. If you notice it anywhere else let me know!
