### ISSUE TITLE
Interference Mitigation Mode with noise reduction

### ISSUE THREAD

**Issue by ion-storm** [Jackysi/advancedtomato#10]
Found a bug related to interference mitigation:
The field "wl_mitigation" is invalid. Please report this problem.

Btw, love this firmware, its leaps and bounds better than dd-wrt, thanks for the hard work

**Comment by Jackysi** [comment]
Thanks for report, I will look into it!
Thank you, glad you like it!

**Comment by Jackysi** [comment]
It would seem this was an bug in Shibby's releases as well, he fixed it so it should be working fine in next AT release.
