### ISSUE TITLE
Add CSS skin to Adminer.

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#100]
This is fairly simple to do, just put the file adminer.css alongside adminer.php. You can get the skin from https://www.adminer.org/.

![screenshot](https://cloud.githubusercontent.com/assets/10690085/11718138/3acd0672-9f5d-11e5-852d-83853fd4ff32.png)

**Comment by Jackysi** [comment]
I don't know how many people actually use adminer. I use this skin too but not on my router though, we'll see if this is possible to embedded into Tomato, problem may be additional size (already very close to limit at most non-ARM routers).

**Comment by ghost** [comment]
Could you just do it for ARM then? I own an R7000. I also sent you a message some time ago about advancedtomato on Linksys E900 but your contact form doesn't seem to be working properly. I would greatly appreciate it. Thanks!

**Comment by Jackysi** [comment]
I receive daily emails that make no sense or answers are already available online, such emails I ignore. There is also many contact messages where people ask for support which I don't offer =/.

I will see but generally I don't do differences between ARM/RT-AC. My goal is to have united interface for easier maintenance and so on. I might however lose all other routers in future and only stay with ARM.

**Comment by ghost** [comment]
In your FAQ you said that if Shibby has builds available for my device (which he does) you might consider adding an advancedtomato build aswell. It means a lot to me, thank you!

**Comment by Jackysi** [comment]
Yes but only RT-N / RT-AC / ARM builds, the 900 is RT.

**Comment by ghost** [comment]
Actually, E900 is K26RT-N according to Shibby's router list page. It should be the same FW as ASUS RT-N10U (NVRAM64K, 8MB FLASH size) which means that you'll only need to update the headers. I might be wrong, even if I'm into dev-ing, I'm relatively new to router firmwares.

**Comment by Jackysi** [comment]
https://github.com/Jackysi/advancedtomato-gui/commit/96b4ed3f9dd6720dc9eb8e4fc5abd5696b5931ac
