### ISSUE TITLE
R7000 AC Wireless network

### ISSUE THREAD

**Issue by conanedogawa2** [Jackysi/advancedtomato#101]
Hello,

I just installed the last AdvencedTomato firmware for my r7000 Router. (Version 3.0-132)
Sadly, i can't make AC Wifi works. 
When I go to basics settings -> networks -> 5ghz -> Wireless Network Mod i can only see A and N.
https://puu.sh/lRIXO/0c4767015e.png

Thanks a lot for your help.

**Comment by Jackysi** [comment]
This is not support section. Please take your problems else where. http://www.linksysinfo.org/index.php
