### ISSUE TITLE
UPnP:  Not seeing app listed

### ISSUE THREAD

**Issue by Snake883** [Jackysi/advancedtomato#107]
I have UPnP/NAT-PMP enabled on LAN.

The application uses UPnP/NAT-PMP.

I do not see the application listed in the top section of the GUI:
Port Fowarding\UPnP/NAT-PMP\UPnP / NAT-PMP Port Forwarding

The application does appear to be accepting port connections, so I presume the feature is working, just not showing in the GUI.

**Comment by Jackysi** [comment]
I'm not sure if I'll be able to replicate this issue, but I will try. I haven't had such issue before. What is the name of app causing the issue?
