### ISSUE TITLE
QoS: Wrong classifications?

### ISSUE THREAD

**Issue by Snake883** [Jackysi/advancedtomato#108]
Why is "YouTube 2012 (Youtube)" classified as "Mail" and not "Media"?

Same with:
HTTP Video (Youtube)
Flash Video (Youtube)

**Comment by Jackysi** [comment]
This is Firmware related and not GUI. GUI is only displaying NVRAM values in QOS section and since I don't modify firmware (including NVRAM values) unless required for the GUI, I can't offer support or fix for this issue.
