### ISSUE TITLE
ASUS RT-N10U enters recovery automatically on boot after 3.0-132 FLASH.

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#109]
Hello,

There seems to be a problem with your latest 3.0-132 build for ASUS RT-N10U. It gets stuck into recovery after flash (I have tried multiple times, TFTP included) and I got the same result. Everything works fine with 2.9-131. I will try to update from 2.9-131 and tell you the result later. Thank you for your work!

**Comment by ghost** [comment]
I tried to upgrade from 2.9-131 and I get the following error: File is too big to fit in MTD. Looks like you have to make a smaller binary for this one. I would really appreciate if you could. Thank you!

**Comment by Jackysi** [comment]
Will be checked, but this issue tracker is meant for GUI issues and not firmware images problems... One is for "BUGS" and one is for "Problems" / "Support". Please rather email me instead in future...

**Comment by NoirHD** [comment]
Thanks for the reply, I surely will. As a side note: I know you are busy building your GUI for all models these days and it takes time so I might be able to take some burden away from you. If you could provide some steps I should follow, I will gladly build those images for you (I possess both Windows and Linux systems on physical machines highly capable in terms of raw CPU power).

**Comment by ghost** [comment]
Thanks for the reply, I surely will.
