### ISSUE TITLE
EA6700 wont set to 80Mhz

### ISSUE THREAD

**Issue by j88nyr** [Jackysi/advancedtomato#111]
I have a Linksys EA6700 with the latest 3.1-132 installed.
On my 5Ghz band, in the network settings, I have it set to Auto for channel, and 80Mhz in the band settings.
However, when returning to the status page, it shows that 5Ghz is only on 40Mhz and my speed fluctuated between about 100-300mbps.

Also in the network settings it does not let me set the network mode to AC, only Auto, A or N.

Any ideas?

**Comment by Jackysi** [comment]
Possible same issue: https://github.com/Jackysi/advancedtomato/issues/96
Otherwise this is not a support section. This issue is not related to the AdvancedTomato GUI. Please write up your question at http://linksysinfo.org
