### ISSUE TITLE
Real Time Bandwidth monitor visualization bug

### ISSUE THREAD

**Issue by Desani** [Jackysi/advancedtomato#112]
![visualization](https://cloud.githubusercontent.com/assets/9305718/12600105/fa283272-c464-11e5-8917-d4497e9a2f67.PNG)

If you let the Real-Time bandwidth monitor reach the end of the graph there is a line that jumps from the to the beginning spanning the entire graph. I also checked the Real-Time IP monitor and it suffers from the same issue. See Below.

![visualization2](https://cloud.githubusercontent.com/assets/9305718/12600230/f14c8b7a-c465-11e5-9b8c-a93a3b990f1e.PNG)

**Comment by Jackysi** [comment]
I haven't noticed this issue. How did you manage to start it so I can replicate and fix it?

**Comment by Desani** [comment]
All you have to do to reproduce the issue is visit any of the real time graphs and let the visualization get to the end of the graph. So sit on the page for about a minute or two and when it reaches the end of the graph you get the visualization as pictured above.

**Comment by mzhboy** [comment]
![real_time](https://cloud.githubusercontent.com/assets/5281193/13673697/3cf2153c-e715-11e5-9975-b50446561901.PNG)

**Comment by AdziePahlevi** [comment]
The bug still exist on 1-136 K26 USB AIO version. What you can do to reproduce the issue is, just wait until 10 minutes (because you have to get the graph from right to the left).. 

![image](https://cloud.githubusercontent.com/assets/19539988/15484480/bcb40570-2129-11e6-8bcc-e51e59506b47.png)

**Comment by Jackysi** [comment]
there has been no UI changes for last 3 shibby updates. Its still version 3.1 so I don't know why would u expect a fix?

**Comment by AdziePahlevi** [comment]
Hi Jackysi, okay I thought there was some update. I just recently using advancetomato, anyway this is minor bug not affecting the performance nor functionality..

**Comment by Jackysi** [comment]
its okay, well there was Shibby update but I only modified his updates and not GUI it self. I just have no time =/
