### ISSUE TITLE
Wds problems

### ISSUE THREAD

**Issue by own3dkosci** [Jackysi/advancedtomato#113]
I have a Linksys e3200 router with AdvancedTomato 3.0-132 k26 USB Mega-VPN
And tp-link tl-wr841n v10.0 default firmware.
I have tried a few guides, but none of them worked. My current setings are  basic settings->  network. Wan/internet disable, 
lan disabled dhcp and changed ip address to 192.168.0.2, 
set default gateway 192.168.0.1, 
static dns 192.168.0.1,
Set wireles mode to ap +wds tried wds and wireles bridge,
Set same ssid and password  on both routers 
Set chanel to 8 on both and 40 mhz width on both
Set link to correct mac addres 
Did i miss something?
Yesterday it was working fine except huge packet loss i pinged google and 1 of 4 packet returned any help?
P.s thanks in advance

**Comment by Jackysi** [comment]
This problem is related to router firmware, please report it to Shibby https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open! This is issue tracker for GUI related issues.
