### ISSUE TITLE
USB led on router

### ISSUE THREAD

**Issue by EdoAsus** [Jackysi/advancedtomato#114]
I'm new with advancedtomato firmware, i just install it on my Asus RT-AC68U and seems great to me, i noticed while i have attached an external SSD drive on the USB 3.0 port on the router that the LED remains off, erroneously the USB 2.0 LED is on, something is wrong with LED association.
The disk is working fine, it's mounted and i can access it, this was not happening with stock firmware, is that a bug? Let me know thanks.

Asus RT-AC68U
Firmware AdvancedTomato Version 3.1-132 
RT-AC68U-AT-ARM-3.1-132-AIO-64K.trx

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open! This is issue tracker for GUI related issues.
