### ISSUE TITLE
Ethernet Ports State Icons Spacing Issue

### ISSUE THREAD

**Issue by avelos156** [Jackysi/advancedtomato#118]
Hello,

There seems to be a spacing issue with the ethernet ports state icons and text.
In IE 11, sometimes (depending on IE window size) icons are truncated.

With Firefox:
![firefox](https://cloud.githubusercontent.com/assets/5371272/12813793/0d3c59e4-cb43-11e5-9e10-40b45b691bbc.PNG)

With IE11:
![ie11](https://cloud.githubusercontent.com/assets/5371272/12813796/0f66cf56-cb43-11e5-888b-ae9c240c6b76.PNG)

Router: Netgear R7000
Interface version: 3.1-132

Best regards

**Comment by Jackysi** [comment]
Fixed https://github.com/Jackysi/advancedtomato-gui/commit/d4e2524b592efef19d01a988a2f4c089d62ed1ef
