### ISSUE TITLE
IP Graphs Spacing Issues

### ISSUE THREAD

**Issue by avelos156** [Jackysi/advancedtomato#119]
Hello,

Graphs are out of bounds in firefox while in both IE11 and firefox figures are difficult to read due to spacing.

In firefox:
![firefoxipgraphs](https://cloud.githubusercontent.com/assets/5371272/12816430/23ec0236-cb55-11e5-822e-ddeae824625e.PNG)

In IE11:
![ie11ipgraphs](https://cloud.githubusercontent.com/assets/5371272/12816439/30c7ff6e-cb55-11e5-9d4f-c593a2883577.PNG)

Router: Netgear R7000
Interface version: 3.1-132

Best regards

**Comment by Jackysi** [comment]
This is a problem with Technology used. Firefox is not properly adapting cell widths in masonry grid (flux).  This "issue" is waiting for Firefox bug fix and won't be changed.
