### ISSUE TITLE
Update notification dont work

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#12]
I submit 2 issues since they are fixt (nice work!). I dont have update me router so i should get the message that there is an update when i logon on my router (some of the fetures of advanced tomato). But i dont get the message.

**Comment by Jackysi** [comment]
I will look into this, thanks!

**Comment by AndreDVJ** [comment]
I also did not notice 2.03 update immediately. I was checking around and found there was an update available.

**Comment by Jackysi** [comment]
It does take about 6-12h for updater to check you know that right? Since its now linked to TomatoAnon project. Also if you disable anon you disable update checker.

**Comment by ghost** [comment]
Yes i know it takes x hours butt i check your website update was 3 days availeble @my router no update message thats nore then 48 hours.

**Comment by Jackysi** [comment]
I found the problem, thanks for report. I forgot to update link to new web site and its still at.prahec.com which wget on router doesn't detect correctly, this is the message:

<pre>wget: bad address 'at.prahec.com'
cat: can't open '/tmp/anon.version': No such file or directory</pre>

I will fix it in next release, thanks!

**Comment by Jackysi** [comment]
I also fixed this issue for routers without this latest update. I lifted redirect on update.php so wget should work fine now :D if that makes any sense! :)
