### ISSUE TITLE
Classes in QoS Graphs 

### ISSUE THREAD

**Issue by avelos156** [Jackysi/advancedtomato#120]
Hello,

In Tomato by Shibby GUI, Classes under QoS Graphs Menu are displayed in descending priority (i.e Priority Class 1 is displayed first, then Class 2 and so on) which is usual/common in all QoS systems and convenient to read too.
With AdvancedTomato, lowest priority Class (e.g. Crawl) is displayed first, then Classes in ascending priority follow.
My suggestion: Please adopt the Tomato by Shibby approach for better readabilty and understanding of priorities with just one look.

In Tomato by Shibby GUI, in QoS Graphs Menu, when a user clicks on a Class, or on a corresponding area on the Pie Charts, only connections related to that Class are shown (i.e connections are filtered based on where the user clicks).
With AdvancedTomato, no matter what Class/Pie Chart area a user clicks on, always all connections will be displayed (it's like the user is always redirected to the QoS View Details Menu).
My suggestion: Please adopt the Tomato by Shibby approach for better user experience and faster/better filtering of the connections.

Router: Netgear R7000
Interface Version: 3.1-132

Best regards

**Comment by Jackysi** [comment]
All this makes no sense. AdvancedTomato uses same GUI functionality (all you wrote above) as Tomato by Shibby, so it should be the same. Sorry I know this is like LATE LATE.
