### ISSUE TITLE
Add Time Machine Mac OS

### ISSUE THREAD

**Issue by jon4god** [Jackysi/advancedtomato#123]
You are planning to add support for Time Machine Mac OS? It would be nice!
http://vena.net/post/86026368825/using-an-asus-router-as-a-time-capsule
http://d43.me/blog/1660/concisest-guide-to-setting-up-time-machine-server-on-ubuntu-server-12-04/
http://wiki.openwrt.org/timemachine

**Comment by Jackysi** [comment]
This is really not a proper section to post this to. 

And no I do not modify router firmware to do these things. I work on GUI which is the front-end the interface that allows you to actually modify firmware/linux settings.
