### ISSUE TITLE
Are the temperature readings correct?

### ISSUE THREAD

**Issue by mdPlusPlus** [Jackysi/advancedtomato#127]
![temp](https://cloud.githubusercontent.com/assets/9272131/13597793/a7f99334-e51a-11e5-93f6-8c8dcccca864.PNG)

~70°C and ~50°C seem way too high.

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to to the proper party. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!

This is a issue tracker for GUI related issues!
