### ISSUE TITLE
make it  dnscrypt=y,show error

### ISSUE THREAD

**Issue by livepu** [Jackysi/advancedtomato#129]
checking for mipsel-linux-strip... mipsel-uclibc-strip -R .note -R .comment
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
./configure: line 3417: syntax error near unexpected token `SYSTEMD,'
./configure: line 3417:`  PKG_CHECK_MODULES(SYSTEMD, libsystemd, have_systemd=yes,'
make[4]: **\* [dnscrypt/stamp-h1] Error 2
make[4]: Leaving directory `/home/food/github/advancedtomato/release/src/router'
make[3]: *** [all] Error 2
make[3]: Leaving directory`/home/food/github/advancedtomato/release/src-rt'
make[2]: **\* [bin] Error 2
make[2]: Leaving directory `/home/food/github/advancedtomato/release/src-rt'
make[1]: *** [b] Error 2
make[1]: Leaving directory`/home/food/github/advancedtomato/release/src-rt'
make: **\* [r2b] Error 2

**Comment by Jackysi** [comment]
This is not a support section. Please use linksysinfo forums http://linksysinfo.org/
