### ISSUE TITLE
RT-AC66U

### ISSUE THREAD

**Issue by sstraus** [Jackysi/advancedtomato#13]
There is no way to save the network settings on this router, a WL_SET error is issued. Probably is something related to the 5Ghz Wifi settings mask because on an RT-16N the same firmware release works great.

**Comment by Jackysi** [comment]
hmm interesting, I will look into it!

**Comment by sstraus** [comment]
Are you able to reproduce the problem? Do you need something?

**Comment by Jackysi** [comment]
I currently don't have any router at home to give it a try. I had to give RT-N66U back to its owner and I don't have source for R7000

**Comment by AustinSaintAubin** [comment]
Asus RT-AC66U with Tomato Firmware 1.28.0000 MIPSR2-2.4-123 K26AC USB AIO-64K.
5GHz setting save and work with one exception, the channel width does not set to 80MHz.
I have the channel width set to 80MHz, Spectrum analyzer shows it is a 40MHz...
Its worth noting that [Advanced Settings] -> [Virtual Wireless] does not show 80MHz as an option for the 5GHz radio.

**Comment by Jackysi** [comment]
That's strange :O! Have you been able to archive 80Mhz on Shibby if you had given it a try? Its possible when merging something went wrong I will look into it as soon as I have some time! I will fix Virtual Wireless page asap and include the fix in next release.

**Comment by Jackysi** [comment]
Did you guys try clearing NVRAM and running with clean installed router?

**Comment by AustinSaintAubin** [comment]
Cleared NVRAM, it made no difference. Still 40 MHz channel width MAX.
Tomato Firmware 1.28.0000 MIPSR2-2.4-123 K26AC USB AIO-64K

**Comment by Jackysi** [comment]
I'm sure this issue was fixed in latest releases, so closing the issue report. If anyone still has this issue please be my guest and re-open it.
