### ISSUE TITLE
Request: Show MAC addresses for each port

### ISSUE THREAD

**Issue by LordMike** [Jackysi/advancedtomato#130]
Hey,

Great UI - been using it for some time now. :)
A little request though: Would it be possible to display the MAC addresses associated with each LAN/WAN port? 

I'm unable to trace my cables (walls and stuff), so while I was setting up VLAN's on a new router, I had some problems tracking which port was hooked up to each client.

In the device list, the MAC's are shown pr. bridge, but not pr. port - so it's close. This request is similar to the features many managed switches provide, aiding administrators in finding troublesome devices.

Regards,
Mike

**Comment by Jackysi** [comment]
I follow Shibby's work closely so I can have best of both worlds (GUI + Top Firmware). So with that in mind extending such features is not possible. It would cause many more problems, more work (I already have too much work with Tomato) and so on. In new version 134 there has been added more MAC addresses for WAN's but guess that's not what you need.

At this time I don't extend features (non GUI related ofc) and I am not planing to do so in the future.

Thanks for taking your time and dropping a suggestion. You may want to suggest this to Shibby which you can find under nickname Shibby20 at http://linksysinfo.org/
