### ISSUE TITLE
No access to ipv6_dhcpd in web interface

### ISSUE THREAD

**Issue by npt** [Jackysi/advancedtomato#132]
The ipv6_dhcpd NVRAM setting isn't accessible, though I would think it would be accessible on the Advanced DHCP page the way ipv6_radvd is.

**Comment by Jackysi** [comment]
U should talk with Shibby about that. I'm GUI developer and I don't work firmware features
http://www.linksysinfo.org/index.php?threads/tomato-shibbys-releases.33858/page-63

**Comment by npt** [comment]
This is a GUI feature. The ipv6_dhcpd setting is already there in the firmware, and is present in the GUI in Shibby's Tomato, but not present in AdvancedTomato. Compare:
https://github.com/tomatofirmware/tomato/search?utf8=%E2%9C%93&q=ipv6_dhcpd
https://github.com/Jackysi/advancedtomato/search?utf8=%E2%9C%93&q=ipv6_dhcpd

**Comment by Jackysi** [comment]
I did not notice this please accept my sincere apologies! I will merge your commit, hopefully that's all that is missing?
