### ISSUE TITLE
tux icon in windows explorer

### ISSUE THREAD

**Issue by f242** [Jackysi/advancedtomato#134]
![tomato](https://cloud.githubusercontent.com/assets/10371194/13906226/5c1c0024-eee2-11e5-9d76-6317b1d84295.PNG)
please replace tux with tomato
for example http://all-free-download.com/free-vector/download/tomato_310436.html

**Comment by Jackysi** [comment]
We'll see. I'm not sure that is possible because Windows sets the icon and not the router it self.
