### ISSUE TITLE
Turning on QOS disables internet access

### ISSUE THREAD

**Issue by oozy-jet-portable** [Jackysi/advancedtomato#135]
I have an Asus RT-N16.

I just upgraded to AdvancedTomato Version 3.1-134.
I checked the md5sum of the firmware file before upgrading.
I cleared nvram on installation.

I recreated my wifi, vlan, ddns, adblock script, and openvpn client settings.
Openvpn client is not currently running (i.e. 'stopped').

Next on the list is to reactivate QOS. 
I have not made any changes, but as soon as I 'Enable QOS', internet access dies.
All classifications on the QOS Graphs page show as 'unclassified'.
Unchecking 'Enable QOS' restores internet access.

Anyone else experiencing this?
Any ideas on how to troubleshoot this?
Thanks!

**Comment by Jackysi** [comment]
http://www.linksysinfo.org/index.php?threads/tomato-shibbys-releases.33858/page-63

**Comment by oozy-jet-portable** [comment]
Thanks. Sounds like I will revert back to Version 3.1-132 to get QOS working.
