### ISSUE TITLE
 graphical interface displays nothing

### ISSUE THREAD

**Issue by CoderRunner** [Jackysi/advancedtomato#136]
After I flash the R6300v2-AT-ARM-3.1-134-AIO-64K.trx
my graphical interface becomes this..

Now, I don't know how to flash my router again..

<img width="1229" alt="screen shot 2016-03-22 at 22 28 04" src="https://cloud.githubusercontent.com/assets/15362076/13954898/aab4d44e-f07d-11e5-938a-600da07dd2ea.png">

**Comment by CoderRunner** [comment]
I've solved it.
It may result from not erasing nvram before I flash R6300v2-AT-ARM-3.1-134-AIO-64K.trx.

The solution is 
1. ssh/telnet login router
2. enter nvram_erase
3. enter reboot

Thanks.

**Comment by Jackysi** [comment]
You can also use http://192.168.1.1/upgrade-plain.asp which doesn't load UI at all. Its simple ASP to upload another image when main UI fails. I can't debug the problem you encounter without any details from console log (F12).
