### ISSUE TITLE
Asus RT N18U Download links 404 / broken

### ISSUE THREAD

**Issue by ionas** [Jackysi/advancedtomato#138]
Any hint why that's the case? https://advancedtomato.com/downloads/router/rt-n18u

**Comment by TuRDMaN** [comment]
I think all the downloads are broken. I checked a couple different firmware files for a few different routers and none of them worked.

**Comment by Jackysi** [comment]
I have moved all images and downloads to another folder. Doing so I caused a bug which made all downloads unavailable. I have fixed the issue now so it should work normally.

**Comment by TuRDMaN** [comment]
I can confirm everything working again now. Thanks!

**Comment by ionas** [comment]
Thank you guys!
