### ISSUE TITLE
IP traffic, 24 hours view is broken

### ISSUE THREAD

**Issue by aditaga** [Jackysi/advancedtomato#139]
The IP Traffic, last 24 hours graph is broken on my router. I have a Netgear WNR3500L-v2.

IP traffic data is not displayed correctly and the clickable IP address tabs at the top of the graph are only [visible](http://s30.postimg.org/y3kxbrtpd/bwm_ipt_24_1.png) for a couple of seconds, after which they [disappear](http://s30.postimg.org/6hi5r3ach/bwm_ipt_24_2.png).

Another odd thing is the last item on the "IPs currently on graphic" [drop down list](http://s30.postimg.org/6rpoafoyp/bwm_ipt_24_IPs_currently_on_graphic.png).

**Comment by Jackysi** [comment]
Please use F12 developers tools to copy/paste actual problem.

**Comment by aditaga** [comment]
Hi, the console shows no errors.
![screen shot 2016-04-02 at 8 39 53 pm](https://cloud.githubusercontent.com/assets/3527822/14228372/1fcd3e5e-f913-11e5-9b6e-321682f92757.png)

**Comment by aditaga** [comment]
Hi, I found the problem. It was on my side. 

The problem was that I had enabled saving of IP traffic monitoring history to a file on disk, but the file got corrupted, it seems. I cleared the bad data by using the 'Create New File' option and now IP monitoring works again.

**Comment by Jackysi** [comment]
Oh, I referenced wrong issue. agh well this one is for closing thanks for response! And sorry im so damn late! :/
