### ISSUE TITLE
Why USB-UHCI support disabled?

### ISSUE THREAD

**Issue by freetushkan** [Jackysi/advancedtomato#14]
"tomato-K26USB-1.28.AT-RT-N5x-MIPSR2-2.03.20-AIO.trx" on Asus RT-N16

USB-UHCI support checkbox is totally disabled, I can't check it.
It's a bit strange, so "uhci-hcd.ko" is exist in modules directory.

**Comment by Jackysi** [comment]
Apologizes for long response. I honestly have no idea. I tried to fix this issue a while ago and couldn't find the problem. At the moment I have no router to test it out so it might have to wait a while.

**Comment by Jackysi** [comment]
I have been looking into your issue and I couldn't find an error, could you do a little check up for me?
Please go to http://192.168.1.1/nas-usb.asp (Your router GUI URL and don't add # before nas-usb for this) then open source code of page (right click on bugy content and "View Source") and than check this for me:
'usb_uhci': '-1'

If this value is -1 as on my router, this is an internal issue of Tomato and has nothing to do with AdvancedTomato. I mean in this way that it doesn't work on Shibby's releases aether.

**Comment by freetushkan** [comment]
Sorry for late report. Yes, I have same ('usb_uhci': '-1') element in array.
Does Shibby have github or something else to report bugs? It seems, that this questions is a flood and garbage for here.

**Comment by Jackysi** [comment]
Hmm he does have Git but just repo without issues tracker. You could report this issue by LinksysInfo forums and perhaps even some other developer might help you why this is happening. I'm not fully excluding issue on my end with compilation, but I very much doubt that could be the case.
