### ISSUE TITLE
The field "qosl_ulr" is invalid. Please report this problem.

### ISSUE THREAD

**Issue by ionas** [Jackysi/advancedtomato#141]
Helloes,

I wanted to limit my wireless guest vlan to QoS = junk while the wireless internal and hardwired internal network have best performance always, so that if someone joins my office and I hand over some wifi credentials he cannot screw up my internet/network performance:

<img width="2304" alt="screen shot 2016-03-24 at 20 41 21" src="https://cloud.githubusercontent.com/assets/106845/14029214/288dff2e-f201-11e5-9745-15e98b7956ef.png">
<img width="2302" alt="screen shot 2016-03-24 at 20 41 34" src="https://cloud.githubusercontent.com/assets/106845/14029210/287c37d0-f201-11e5-9448-ae43c077ab55.png">
<img width="2304" alt="screen shot 2016-03-24 at 20 42 08" src="https://cloud.githubusercontent.com/assets/106845/14029211/287e88f0-f201-11e5-9887-f9797e1afe8a.png">
<img width="2304" alt="screen shot 2016-03-24 at 20 42 17" src="https://cloud.githubusercontent.com/assets/106845/14029212/28844dbc-f201-11e5-96e9-73968d652c08.png">
<img width="636" alt="screen shot 2016-03-24 at 20 43 57" src="https://cloud.githubusercontent.com/assets/106845/14029213/288883e6-f201-11e5-959c-1a4abb96f8b8.png">

However... I cannot save that setting.

**Router:** Asus RT-N18U
**FW:** 1.28.0000 -3.1-135 K26ARM USB AIO-64K

**Comment by Jackysi** [comment]
135 is beta/experimental. I'll look into it with next update

**Comment by ionas** [comment]
How do I know from the Downloads page if something is considered "stable" or beta/experimental

**Comment by Jackysi** [comment]
You don't. Warning was added because Shibby asked me to warn users since versions 132+ are unstable for now. MultiWAN features are hard to implement.

**Comment by ionas** [comment]
- Thus if I don't need MultiWAN 131 latest is the most stable and useful one?
- Could you add "BETA" as a section under downloads in any way? Edit: Or "Alpha" or "Bleeding Edge"

**Comment by Jackysi** [comment]
The warning is all you need, its totally explanatory. It says that versions 133 and above are currently not considered stable. At this time I won't bother and waste time on this problem while facing many others on the firmware. Remember this is free, open source project.

**Comment by gaia** [comment]
I am getting the same issue on 138. @Jackysi is your Mar 27 2016 comment still valid?
