### ISSUE TITLE
MAC Address (Version 3.1-135)

### ISSUE THREAD

**Issue by przemasisko** [Jackysi/advancedtomato#148]
It does not work correctly change the MAC address of the WAN port.
After clicking on the Save button nothing happens.
In the version 3.1-134 it works correctly.

**Comment by Jackysi** [comment]
This was fixed in 135, did you run NVRAM reset?

**Comment by przemasisko** [comment]
Of course NVRAM was cleaned several times.
Only 135 I have a problem. With 134 working properly.

**Comment by Jackysi** [comment]
I don't know i'll check...
