### ISSUE TITLE
Wireless channel doesn't change

### ISSUE THREAD

**Issue by Desani** [Jackysi/advancedtomato#15]
I am using an Asus RT-N66U and on the Basic > Network page. When I try to change the channel number of the wireless network (Both 2.4Ghz and 5.0Ghz) they do not change what channel the network is operating on (I.E. Channel 11 instead of Channel 6)

I am using AdvancedTomato Version: 2.3-120 K26AC USB AIO-64K.

**Comment by Jackysi** [comment]
Hmm interesting. I will give it a look once I get hands on some router that supports AdvancedTomato

**Comment by Jackysi** [comment]
Does this issue persist in new 2.5 version? If I am right this was fixed in 2.4 or 2.5 when Shibby released new 124 update.
