### ISSUE TITLE
[BETA] WAN IP won't renew on 134/135 releases

### ISSUE THREAD

**Issue by Alcolawl** [Jackysi/advancedtomato#162]
Router: ASUS RT-AC68P
Firmware: v3.1-134/135 AIO-64k
Notes: I understand this is a beta/experimental release. I'm not begging for a fix, I'm simply filing this so the dev is aware of an issue.

Issue: WAN IP does not renew after upgrading to either available experimental build. This happens regardless of whether the nvRAM is wiped after the upgrade or not.
![wan](https://cloud.githubusercontent.com/assets/5004749/14991596/1bf0cd16-1130-11e6-8862-8cda3719fdd2.png)

UPDATE: 5/5/2016, I've tried setting the WAN settings to Manual and entering the proper information by hand. The Subnet Mask, when set, does not stick, even when using a shell command.

**Comment by ruslan61rus** [comment]
You can just print in command line:

> nvram set wan_pptp_dhcp=0
> nvram commit
> 
> and issue will be fixed

**Comment by Alcolawl** [comment]
Executed the commands and restarted the router. Did not fix the issue.
![wan](https://cloud.githubusercontent.com/assets/5004749/15001832/e542490a-1168-11e6-976d-7d3b9a597325.png)

**Comment by Alcolawl** [comment]
Issue has been fixed. After comparing several screenshots and information I noticed that the MAC address being assigned to the WAN port was incorrect after flashing build 135 and clearing the nvram. I went to "Advanced Settings" > "MAC Address", changed the WAN port MAC address to the correct address and the problem was resolved.
