### ISSUE TITLE
Wireless 2.4GHz/eth0 Settings Missing

### ISSUE THREAD

**Issue by dmushail** [Jackysi/advancedtomato#164]
Hi, 

Linksys EA6500v2
v3.1-136

After upgrading to v3.1-136 from v3.1-135, my 5GHz SSID wasn't showing up. After going to the "Status Overview" page, I saw that my 5GHz adapters SSID was renamed to the 2.4GHz's SSID and all settings for eth0(2.4GHz) have disappeared. There is no sign of it in Status Overview, Networking, or Advanced->Wireless.

[Edit: Added screenshots. I collapsed everything just so that all columns can be seen on one page.]
<img width="1414" alt="screen shot 2016-05-12 at 9 17 00 pm" src="https://cloud.githubusercontent.com/assets/19336922/15235176/f8a86fae-1886-11e6-9289-f8de4c041c6f.png">
<img width="1414" alt="screen shot 2016-05-12 at 9 19 34 pm" src="https://cloud.githubusercontent.com/assets/19336922/15235218/5cbd971c-1887-11e6-9b14-25fba881c419.png">

**Comment by underley** [comment]
Almost the same issue with 1.28.0000 -3.3-138 K26ARM USB AIO-64K on Linksys EA6700
Via ssh I can see:
 LAN : 10.**_.**_.1/24 @ DHCP: 10.**_.**_.193 - 10.**_.**_.199
 WL0 : 2,4GHz @ *****\* @ channel: PL6 @ 48:F8:B3:7C:**:**
 WL1 : 5GHz @ *****\* @ channel: PLauto @ 48:F8:B3:7C:**:**
but ifconfig shows only eth0 (lan) and eth1 (WL1, 5GHz)

**Comment by phcorrigan** [comment]
I'm having a similar issue. I just installed Advanced Tomato on a Linksys EA6500V2. If i change the DHCP address range, change the Country setting, or change the SSID for the 5 GHz band I lose the 2.4 GHz band when I reboot. I suspect other changes will cause this as well. I even tried only enabling 2.4 GHz, but when the router is rebooted it comes back as 5 GHz only, but adopts the SSID that I assigned to the 2.4 GHz band. I am using Advanced Tomato v3.3-138 AIO-64K. Has anyone seen this issue and, if so, found a solution? Thanks.

**Comment by dmushail** [comment]
I don't know if this will help you, but what I did to solve the issue at the time was re-flash the router with the "Restore Defaults" option enabled. It was inconvenient to have to reconfigure everything, but I haven't had the problem since.

**Comment by phcorrigan** [comment]
I'll give it a try. Thanks.

**Comment by phcorrigan** [comment]
Reflash with Restore Defaults" didn't help. Thanks.
