### ISSUE TITLE
Public NTP servers not reachable from clients build 3.1-134 to 3.1-136

### ISSUE THREAD

**Issue by tusharm2** [Jackysi/advancedtomato#166]
Hi,

I have been struggling to make public NTP servers reachable from my clients on r7000 tomato AOI 3.1-134 to 3.1-136.
NTP servers(pool.ntp.org) are responding form route(command line) but not working from any of the clients wired or wireless.
Things i have tried.
- DMZ one of the client
- iptable open port 123 over UDP
- NVRAM rested and fresh setup
- upgrade to latest(though beta version 3.1-136)

NTP trace output on one of the client-
ntptrace pool.ntp.org
pool.ntp.org: timed out, nothing received
***Request timed out

NTPc from router for same server
ntpc pool.ntp.org
Trying pool.ntp.org [125.62.193.121]:

Time: Sat, 14 May 2016 14:35:59 +0530, no change was needed.

NTP use to be fine on Netgear default FW i am facing the issue on DD-WRT and tomato.

I feel i am missing something really stupid.
I am new to tomato, any suggestion/help is highly appreciated.

Thanks in advance

**Comment by Jackysi** [comment]
I'm sorry but this is not support forum. You can contact other users/developers at http://www.linksysinfo.org/
