### ISSUE TITLE
Captive Portal breaks when QoS&Bandwith Monitor are enabled

### ISSUE THREAD

**Issue by rix1337** [Jackysi/advancedtomato#167]
I am using Version 3.1-136 on my Asus RT-N66U to great success,

however, I want to create an isolated guest wifi using a captive portal.

With QoS (and bandwith limitations) enabled, I cannot access wan from my virtual Wifi, hence the "Ok, I agree" process ($action on splash.html) fails on my devices.

Any help would be greatly appreciated

**Comment by Jackysi** [comment]
This issue is related to the Tomato firmware, please contact developers who can fix the mentioned issue! http://www.linksysinfo.org/
