### ISSUE TITLE
PPPoE Connection issue

### ISSUE THREAD

**Issue by alecsandes** [Jackysi/advancedtomato#170]
Hi,

I've flashed to the 3.1-136 version on R7000 and I cannot connect to the PPPoE connection.
I was trying to set the router from scratch so I don't upload any configuration.

Is it related to VLAN?
If so, can someone please help me to set this as I am not interested to set multiple VLANs and WANs

Thanks

**Comment by alecsandes** [comment]
I tried to downgrade to 134 and I could not set the internet connection. All the tabs for Multi WAN were present in GUI but not accessible. The internet connection section was in non-accessible tabs.

Sorry, didn't made any screenshots. 

Went back to 136 and I could connect to PPPoE but actually I didn't have access to the Internet,
P.S. I made nvram clear after each action.

**Comment by Jackysi** [comment]
You should really consider reporting these issues to Shibby. Does really noone read description what AdvancedTomato is? Its only GUI for Tomato by Shibby...
