### ISSUE TITLE
Bandwidth Limiter not working

### ISSUE THREAD

**Issue by AdziePahlevi** [Jackysi/advancedtomato#174]
Hi, recently I'm doing some experiment and implementing bandwidth limitations on some devices..
as you can see below the bandwidth limiter is enabled and I already bound one device with the IP, in my case is 192.168.100.43

![image](https://cloud.githubusercontent.com/assets/19539988/15660163/ec73331e-26c7-11e6-9cfd-a06bd9c29c68.png)

however after its enabled and also after router is rebooted, seems the speed of the limited devices is still getting unlimited bandwidth, below is the graph from the IP Bandwidth monitoring

![image](https://cloud.githubusercontent.com/assets/19539988/15660211/8c86e30a-26c8-11e6-9ddb-5d94eb034e7f.png)

not sure why its not working, I already put devices MAC address and even I put the IP Address as well, but seems have no impact. would you please have look on it.

**Comment by AdziePahlevi** [comment]
I found these on linksysinfo.org

http://www.linksysinfo.org/index.php?threads/trouble-with-bandwidth-limiter.72417/

could it be related? some users are posting using 136 release the bandwidth limiter is not working, while it works on 124 release..

**Comment by Jackysi** [comment]
Yeah, its defo Tomato issue and has nothing to do with AdvancedTomato GUI.

**Comment by Bezalel79** [comment]
Hi, Do you know if it has been fixed in version 137?
I've tried the 132 version but don't work
Thanks

**Comment by AdziePahlevi** [comment]
on 132 bandwidth limiter is working like a charm, however in 137 after I flash it's not working.. people on linksysforum said I need to do clean flash router and re-configured the router from the scratch which is taking a lot of time, so I still haven't done it... if you want to test on 137 pls do it by performing clean flash your router...

**Comment by Bezalel79** [comment]
I did some tests and I realized that in the original version 132 of the BWM Shibby works well but in the advancedtomato 132 version does not work .
Regarding the version 137 does not work or the Shibby version nor that of AdvancedTomato

**Comment by AdziePahlevi** [comment]
I can confirm it works on 132 Advance tomato. Have you performing clean firmware installation using ASUS Firmware restorations? 

for 137 I haven't tried using clean firmware installations, later I will try when I have some spare time.. as per information you have to reconfigure your router from scratch and it won't work if you are restoring your router using backup file / configuration.

**Comment by Bezalel79** [comment]
I have not been able to do clean firmware installation using ASUS Firmware restorations with the 132 version of advanced tomato becouse I received an error and my Aus rt-n16 not go out from the Recovery Mode. Using Shibby version it's works.
In my test I start from Shibby version, migration to advancedtomato,  clean nvram no restore configuration

**Comment by AdziePahlevi** [comment]
I discover this issue when I'm using advance tomato 136 then I create this thread. Later I found this problem also observed on Shibby release. Last time I downgrade from 136 to 132 using Asus Firmware restorations.. 

try 30/30/30 method to put your router to Maintenance Mode, its also difficult for me last time but it was goes to maintenance mode after 30/30/30

Below is the steps:
1. Press Reset button (small black button) for 30 seconds, after 30 seconds plug out the power
2. Keep press the reset button for another 30 seconds, after 30 seconds passed, plug in the power
3. Keep Press reset button for another 30 seconds.

voila it goes to maintenance mode.

**Comment by Bezalel79** [comment]
Forgive me for my bad English . My problem is just the opposite . If I try to upgrade to the Advanced version Tomato 132 router does not go out from the recovery mode. Power led blinking slowly after reboot.
