### ISSUE TITLE
IP Traffic Monitoring / Bandwidth monitoring: Restore doesn't work

### ISSUE THREAD

**Issue by AndreDVJ** [Jackysi/advancedtomato#176]
Hi Jacky.

For some reason, AT GUI is unable to restore backups from these two pages. Tomato's GUI works just fine.

All you have to do is to backup, then immediately restore. You'll get the error message "Something went wrong... Error reading file"

I tried to trace down in the code but I couldn't figure out. Do you have any idea what is causing the issue?

I tried on my both units, R7000 and WNR3500Lv2. No good for both.

**Comment by Jackysi** [comment]
Sorry for late response. I had same issue but was never able to solve it. After some flashing etc it was gone. I have no idea what could've cause it but there is no differences in GUI handling uploads (restore) as Shibby's so I really wouldn't know.
