### ISSUE TITLE
MultiWAN Problem

### ISSUE THREAD

**Issue by tofuliang** [Jackysi/advancedtomato#178]
I set up 3WAN and all of them was connected, but the info of WAN 3 does not seem right.
How could I make sure WAN 3 is being use?
![vlan](https://cloud.githubusercontent.com/assets/1814685/16066210/f1bb2746-32e3-11e6-83cf-5656a0241e0a.png)
![qq 20160615101909](https://cloud.githubusercontent.com/assets/1814685/16066199/e2c16304-32e3-11e6-9a94-7f7e60454942.png)

**Comment by Jackysi** [comment]
Will look into it

**Comment by tofuliang** [comment]
Tomato Firmware 1.28.0000 -3.3-138 K26ARM USB AIO-64K fixed it.
