### ISSUE TITLE
Asus RT-AC56U HTTPD Failure

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#18]
I attempted to flash tomato-RT-AC56U-AT-ARM-2.4-123-AIO-64K.trx from the Asus restoration utility interface after doing a 30/30/30 reset and nvram wipe.

My router powers but the power light is the only light that comes on (on the front). I have been unable to access the router from the web interface. I have no DHCP but if I assign a manual IP I can ping the default 192.168.1.1. The activity lights on the LAN ports appear to work and if I hold the WPS button the power light flashes. I have been unable to get the router back into recovery mode with a 30/30/30 reset.

I can access the router via telnet.

**Comment by ghost** [comment]
Only errors I can see in /var/log/messages

Jan  1 01:01:30 RT-60A44C6B3B98 authpriv.warn dropbear[942]: Failed loading /etc/dropbear/dropbear_ecdsa_host_key
Jan  1 01:01:30 RT-60A44C6B3B98 authpriv.info dropbear[946]: Running in background
Jan  1 01:01:30 RT-60A44C6B3B98 daemon.info dnsmasq[951]: started, version 2.71 cachesize 1500
Jan  1 01:01:30 RT-60A44C6B3B98 daemon.info dnsmasq[951]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset Tomato-helper auth DNSSEC
Jan  1 01:01:30 RT-60A44C6B3B98 daemon.info dnsmasq[951]: asynchronous logging enabled, queue limit is 5 messages
Jan  1 01:01:30 RT-60A44C6B3B98 daemon.warn dnsmasq[951]: failed to access /etc/resolv.dnsmasq: No such file or directory
Jan  1 01:01:30 RT-60A44C6B3B98 daemon.info dnsmasq[951]: read /etc/hosts - 3 addresses
Jan  1 01:01:30 RT-60A44C6B3B98 daemon.info dnsmasq[951]: read /etc/dnsmasq/hosts/hosts - 3 addresses
Jan  1 01:01:31 RT-60A44C6B3B98 daemon.err httpd[953]: can't bind to any address
Jan  1 01:01:31 RT-60A44C6B3B98 user.info preinit[1]: NGinX - daemon not enabled cancelled generation of config file
Jan  1 01:01:31 RT-60A44C6B3B98 user.debug preinit[1]: starting rstats.
Jan  1 01:01:31 RT-60A44C6B3B98 user.debug preinit[1]: starting cstats.

**Comment by ghost** [comment]
root@RT-60A44C6B3B98:/tmp/etc# netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State  
tcp        0      0 192.168.1.1:139         0.0.0.0:\*               LISTEN  
tcp        0      0 0.0.0.0:53              0.0.0.0:\*               LISTEN  
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN  
tcp        0      0 192.168.1.1:445         0.0.0.0:\*               LISTEN  
tcp        0      0 :::9100                 :::\*                    LISTEN  
tcp        0      0 :::53                   :::\*                    LISTEN  
tcp        0      0 :::22                   :::\*                    LISTEN  
tcp        0      0 :::23                   :::\*                    LISTEN  
tcp        0      0 ::ffff:192.168.1.1:23   ::ffff:192.168.1.5:62860 ESTABLISHED 
udp        0      0 0.0.0.0:53              0.0.0.0:\*  
udp        0      0 192.168.1.1:137         0.0.0.0:\*  
udp        0      0 0.0.0.0:137             0.0.0.0:\*  
udp        0      0 192.168.1.1:138         0.0.0.0:\*  
udp        0      0 0.0.0.0:138             0.0.0.0:\*  
udp        0      0 :::53                   :::\*  
raw        0      0 0.0.0.0:255             0.0.0.0:\*               255  
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
unix  7      [ ]         DGRAM                       293 /dev/log
unix  2      [ ]         DGRAM                       984 
unix  2      [ ]         DGRAM                       935 
unix  2      [ ]         DGRAM                       928 
unix  2      [ ]         DGRAM                       883 
unix  2      [ ]         DGRAM                       296

**Comment by Jackysi** [comment]
That's strange. I see on tomatoanon there is 4+ routers running AC56U just fine. Have you checked MD5 hash before flashing the image? Its possible image got corrupted in download process!
http://anon.groov.pl/index.php?version=2.4

**Comment by ghost** [comment]
I suppose that it is possible that it got corrupted. I'm not totally sure where to go from here. The other thing I have noticed is that the date/time is way off. Is this typical of a first flash?

**Comment by Jackysi** [comment]
If you manage to get it working, please let me know! Also try MD5 hash check when you download, if its off it could be issue on a new site. Just for caution. Regarding time, my router goes way back at every reboot and the time corrects at full start up. Which is weird. But I can look into it when I have time.

**Comment by ghost** [comment]
Does the time correct itself without being connected to the internet?

**Comment by Jackysi** [comment]
I didn't try, but I would guess not. You can update it manually no?

**Comment by ghost** [comment]
I was able to manually update the time. I'm still getting the httpd failure. It is taking me a while since I'm not well versed in Linux Cli.

Since I have been unable to get the router into recovery mode am I able to reflash it? I noticed there are several binaries relating to NVRAM and MTD. I have mess around in OpenWRT enough to know that they use MTD to flash from the command line. Is that something that can be done in Tomato also? If so, can you point me to a reference for that utility?

[EDIT]: Is something like this the appropriate method for doing a flash via Cli?
http://forums.smallnetbuilder.com/showthread.php?t=7784

**Comment by ghost** [comment]
I was able to gain access to the GUI interface.

I cleared the NVRAM using "nvram erase". Then I issued a "reboot". Everything appears to have come up but I don't have a warm fuzzy about it. I double checked the MD5 for the firmware and it matched the site.

I think I am going to reflash just in case.
