### ISSUE TITLE
QoS Max Bandwidth Limit input field too short

### ISSUE THREAD

**Issue by Careless** [Jackysi/advancedtomato#183]
For Inbound and Outbound Rates / Limits text input fields on QoS settings page, there is no way of entering full amount.

Correct me if I'm mistaken, but it's read in kbit/s, or kilobits per second.

My internet connection tests at 130 up and 11 down, in Mbps/sec, or megabytes per second.

This equates to roughly 1,065,000 kbit up, but I cannot enter the last zero, thereby limiting my maximum bandwidth rate if I choose to use QoS and have some services top out at 100% of the available bandwidth.

Am I wrong, or is the field just not created with the maxchar variable allowed to enter a few more digits?

**Comment by Jackysi** [comment]
I will give it a look when I have time, thanks =)

**Comment by Eldenroot** [comment]
I can confirm this
