### ISSUE TITLE
Tenda N6 reset after,router cannot be work....

### ISSUE THREAD

**Issue by ttyard** [Jackysi/advancedtomato#185]
I use K26USB-1.28.AT-RT-N5x-MIPSR2-3.2-136-TendaN6.trx succeed write in Tenda N6  and work fine, but after I reset via Web interface, the router can't access, client can't get IP address.
    configuration my host IP to 192.168.1.x Still can't access router(default IP 192.168.1.1),router has become bricks,What's the other way to repair?Thanks.

**Comment by Jackysi** [comment]
This is not a support section!!! This is AdvancedTomato issues tracker and AdvancedTomato is GUI modification of original Tomato by Shibby. 
https://linksysinfo.org
