### ISSUE TITLE
Slow Wireless

### ISSUE THREAD

**Issue by craiggoodwin** [Jackysi/advancedtomato#186]
Hi I have an Netgear R7000 router with the latest release of Tomato.  For some reason I am only gettings 20-30MBPS download through wifi, either 2.4GHz or 5GHz.  The range of the router is also poor compared to my previous WRT54.

These problems are the same regardless of what device I connect to the router with.

If I connect through Ethernet my speed is 160MBPS.

In the status page of tomato I show 60MBPS for 2.4GHz and 216MBPS for 5GHz.  Why am I not getting these speeds, even when in the same room as the router?

**Comment by Jackysi** [comment]
That has literally 0 things to do with AdvancedTomato project. Please please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
