### ISSUE TITLE
Wireless survey (under Tools) inoperative

### ISSUE THREAD

**Issue by grimley** [Jackysi/advancedtomato#187]
Kudos on the work.

**Comment by Jackysi** [comment]
I will need more details, otherwise I will close this issue. Like screen shot of what is wrong? My router has no problem on that page.

**Comment by grimley** [comment]
Nothing appears on mine (R7000).
http://192.168.1.1/#tools-survey.asp 

![git](https://cloud.githubusercontent.com/assets/10035906/16714406/f1f90b28-468f-11e6-9b77-cd449d223ac4.jpg)

**Comment by Jackysi** [comment]
Did u click refresh? It doesn't appear unless refresh is setup... That's normal

**Comment by grimley** [comment]
That did it. Auto Refresh is on and I refreshed the page. Did everything but hit Refresh. 
Thanks

**Comment by Jackysi** [comment]
^^ ur welcome!

**Comment by Eldenroot** [comment]
Maybe add a note below or make a button in a different color would solve this issue
