### ISSUE TITLE
AdvancedTomato fonts not found (404)

### ISSUE THREAD

**Issue by freetushkan** [Jackysi/advancedtomato#19]
No one icon in admin panel not shown - needed font unreachable.
http://<external-ip>:8080/css/fonts/advancedtomato.ttf - 404 not found

Browser in admin-panel can't get access to any files in fonts directory.

Checked '/www/css/fonts/' via ssh - all files exist.

Problem was started from v.2.4-123. Sorry for very poooor english.

![advtom_bug_1](https://cloud.githubusercontent.com/assets/9003273/4964966/dc8e4930-6787-11e4-98ea-48c157a68bf5.PNG)
![advtom_bug_2](https://cloud.githubusercontent.com/assets/9003273/4964968/dc96869a-6787-11e4-8094-3a7de3ee3abb.PNG)
![advtom_bug_3](https://cloud.githubusercontent.com/assets/9003273/4964965/dc8c3ba4-6787-11e4-97d1-63861d81e3fc.PNG)
![advtom_bug_4](https://cloud.githubusercontent.com/assets/9003273/4964967/dc92ebca-6787-11e4-8bf2-254863ccdb62.PNG)

**Comment by Jackysi** [comment]
This is strange. It looks like HTTPD handler is not properly compiled so its possible you are running very first version of 2.4 release. That first version had this problem and I recompiled images to fix the issue. Could you try downloading latest file from http://advancedtomato.com/ and see if it happens again? If yes I will recompile again and re-upload. But its strange. Also router version / browser would help. Thanks for submitting!

**Comment by freetushkan** [comment]
You can see current flashed version in one of screenshots. I re-downloaded and reflashed image 3 times last week. Router is Asus RT-N16 rev.A1. Bug reproduce on any Chrome and IE browser. Previous versions of firmware worked properly.

**Comment by Jackysi** [comment]
I compiled 2.4 twice, after 48h after release I received report about the same issue you are experiencing and I recompiled it with a fix. If you navigate directly to a font file, you get 404 as well?

**Comment by freetushkan** [comment]
Yes. 404.
In my holy opinion, choosing another version for any fix better, than compiling with same version number.

I'll try to flash again right now. Thanks.

**Comment by Jackysi** [comment]
You are right, I would change number but it was a small fix and it wasn't worth of a new version number if you know what I mean. Shibby did the same with latest update. But I agree I should some how notify users about it. This was the commit which fixes the issue: https://github.com/Jackysi/advancedtomato2/commit/9546422b5cdecb8316bbdc5fe14441efdb91d31e

**Comment by freetushkan** [comment]
All working properly now. Thanks. AT is the best and most beautiful router firmware, I've ever used.

Offtop: after flashing router didn't start correctly, so I wait 10-15 mins and power off it manually, is it normal?

Offtop_2: What do you think about localization engine for web-ui? I can help with translation to russian :)

**Comment by Jackysi** [comment]
Glad to hear that! Thanks :)! I have same issue my router sometimes needs few min to start, but that was the same on Shibby's Tomato so I guess its normal? 
Regarding translations, there would be really A LOT of work to translate whole UI. I don't think its worth it. Most IT orientated people who use custom firmware already know English. After all they need to understand it to be able to flash AdvancedTomato. But thanks for offer :)
