### ISSUE TITLE
Access Restriction - Block all internet acess

### ISSUE THREAD

**Issue by joeyoong** [Jackysi/advancedtomato#193]
Hi

I have asus N16 router running on advanced tomato Version 3.1-132  AIO.
I have a issue with the "access restriction" where the added PC mac address to the list will have issue to resolve local computer name or browsing the share folder when the rule is enabled.

The access restriction is working properly when the rule is enable. the listed Mac address computer will be no access to internet. however, when you try to connect to local share folder by using host name, the access restricted list computer will have timeout or not able to find the host. but if using IP address, it doesn't have any issue at all.

do anyone one have this kind of issue same as mine?
I have updated the router firmware Version 3.2-136 AIO before the issue still remain same. as the instruction stated "Firmware images version 3.1-134 and above are currently considered experimental!"
so I reverted back to Version 3.1-132  AIO.

**Comment by Jackysi** [comment]
There is 166 closed tickets out of which 150+ are false reports. This is a support request and this is not a support forum. This is issues tracker! AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
