### ISSUE TITLE
MultiWAN - ISP Monthly Caps - Enhancement Request 

### ISSUE THREAD

**Issue by Modjor** [Jackysi/advancedtomato#196]
Hi,

One very interestin feature to have would be the ability to setup caps for specific WAN connection when using MultiWAN.

The scenario I'm thinking he's for user using AdvancedTomato with a monthly capped WAN connection (IE: 3/4G dongle with 20Gb per month).

So when a specified amount of data is reached, AdvancedTomato automatically failover to another connection (uncapped - or even capped and reapply the same process again).

I was originally thinking of using the basic failover mode, so as soon I have reached my monthly cap, the traffic becoming impossible on the 4G connection, Advanced Tomato would failover to another WAN. But thing is that when you reached you monthly cap, most of the time you are still able to use your capped connection - but at very very slow speed. So it does not trigger the Failover mode.

If this is a feature you are interested in, I've been working on few scripts to do just this but with aRaspberry Pi serving as router, and a couple of USB 4G dongle. I've been using VNStat to keep track of the monthly traffic for my WAN interface

The thing you need in order to ge this feature are:
- Data consumption Reset date: some/msot ISP are not resetting their traffic counter on the 1st of the month, so it is a variable you need to be able to configure from the WebUI.
- Monthly caps: again, a setting that need to be available for the WebUI, so users can configured the amount of monthly data they are entitled for

I'm happy to help if you need a hand on this - I'm a terrible developer, but still know some basics, and as said, I already work on this specific issue with a Raspberry / Raspbian. So at least I got a pretty good idea of the design / possible issues.

**Comment by Jackysi** [comment]
Please post this request to Shibby, the firmware developer who can do something about it: https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open. I can't because I am GUI developer meaning I don't modify Firmware so I don't have the knowledge to add request above.
