### ISSUE TITLE
WiFi/Interface Failure

### ISSUE THREAD

**Issue by farnwomt** [Jackysi/advancedtomato#197]
I compiled a copy of the latest version v3.2-137 for the WNDR3400v3 and it appears to work, but I find myself unable to connect to the WiFi access point almost daily and I need to reboot the router to get it working again.

Today I connected to the router using an ethernet cable, although I had to set the IP address by hand because it wasn't offering any sort of DHCP.  Having done so I was able to connect to the web interface and see the menu on the left hand side, but nothing else because it just continued to try to load the information.

Having connected via ssh it was clear from the logs that the system was up and running to some extent, but the "ifconfig" command never completed.  The only unusual entry I found was in "dmesg" and read as follows:

---

Reserved instruction in kernel code[#1]:
Cpu 0
$ 0   : 00000000 00000000 82827918 00000000
$ 4   : 802fda88 8282d448 000000dc ffffffff
$ 8   : 00000018 80005058 00a42700 5e434200
$12   : 00000104 00000200 c02aa344 0c02f250
$16   : 82e2ae60 83251b00 802fda88 000000dc
$20   : 000000d0 00000268 802fdae8 c024d26c
$24   : 00000001 c0213c74  
$28   : 802fc000 802fda78 802fdd80 82828008
Hi    : 00000007
Lo    : 5c28f5c9
epc   : 82828000     Tainted: P  
ra    : 82828008 Status: 1100bc03    KERNEL EXL IE 
Cause : 80000028
PrId  : 00019749
Modules linked in: ip6table_mangle ip6table_filter xt_recent xt_DSCP xt_layer7 xt_IMQ imq ebtable_filter ebtables vfat fat ext2 ext3 jbd mbcache usb_storage sd_mod scsi_wait_scan scsi_mod wl_high(P) ehci_hcd usbcore nf_nat_pptp nf_conntrack_pptp nf_nat_proto_gre nf_conntrack_proto_gre nf_nat_ftp nf_conntrack_ftp nf_nat_sip nf_conntrack_sip nf_nat_h323 nf_conntrack_h323 wl(P) dnsmq(P) et(P) igs(P) emf(P)
Process events/0 (pid: 4, threadinfo=802fc000, task=802f3000)
Stack : 82e31000 81399248 802fda88 00000000 000000af 00000000 802fdae8 82e31000
        802fdae8 82e31000 83e8e000 00000000 83c50480 82e32800 c024d258 c022b520
        81354cc0 8324b480 81354c00 c009567c 802fdae8 802fdae0 836ad048 00000020
        83c5080c a281d398 000000cd 00001a2b 00000000 00500000 00000000 00000000
        a109efdc efdcf340 f340a109 00000000 00000000 00640000 0e000011 6c6c6976
        ...
Call Trace:[<c024d258>][<c022b520>][<c009567c>][<c021281c>][<c024d26c>][<c020f88c>][<c024d258>][<c020f954>][<c0291b58>][<c0209850>][<c0209b50>][<c02094b4>][<c0207670>][<c0207628>][<c0209604>][<c020a548>][<c026a674>][<c022b364>][<c022b6a8>][<c024d258>][<c022b9f0>][<c0256018>][<c0256004>][<c0221208>][<c0226e88>][<c0254334>][<c022cb50>][<c022c124>][<c022bec0>][<c0260c20>][<c02491d8>][<c02211c4>][<c023947c>][<c0458954>][<c04b8e10>][<c04c4aec>][<c04ca040>][<c023a698>][<c0216490>][<c0214884>][<80005a48>]
## Code: 00000000  00000000  00000000 <77627363> 67353034  006f7068  73636d32  6f703233  00000000 

Does anybody have any thoughts on this?

Thanks,
Michael

**Comment by Jackysi** [comment]
Please post this issue to Shibby, the firmware developer who can do something about it: https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open. I can't because I am GUI developer meaning I don't modify Firmware so I don't have the knowledge to fix the issue above.
