### ISSUE TITLE
PPTP Client Problem

### ISSUE THREAD

**Issue by SkyWalker1726** [Jackysi/advancedtomato#198]
Hello , as soon as the router boots and the PPTP Vpn Connects ( Start With WAN ) , the device becomes unresponsive , the internet disconnects , and nothing works and cant ping the device . 
latest version working fine for me is tomato-K26USB-1.28.AT-RT-N5x-MIPSR2-3.1-132-AIO
newer that that and as soon as the PPTP connection is established , the device fails 
thanks

**Comment by Jackysi** [comment]
Please post this issue to Shibby, the firmware developer who can do something about it: https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open. I can't because I am GUI developer meaning I don't modify Firmware so I don't have the knowledge to fix the issue above.
