### ISSUE TITLE
R7000 WAN port problems

### ISSUE THREAD

**Issue by harmlessdrudge** [Jackysi/advancedtomato#199]
Original issue deleted.

One comment on that: currently I see that versions later than 3.3-134 are experimental. I can't see that there's any indication of versions no longer being experimental. I appreciate that they're superceded and that new versions become experimental, but that doesn't seem to be a good guide to which of the preceding versions is the best bet for a non-experimental version since the list may contain both good and (perhaps?) less good releases. I prefer to avoid the bleeding edge; guidance welcome.

**Comment by Jackysi** [comment]
Please post this issue to Shibby, the firmware developer who can do something about it: https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open. I can't because I am GUI developer meaning I don't modify Firmware so I don't have the knowledge to fix the issue above.
