### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by freetushkan** [Jackysi/advancedtomato#20]
Is it possible to include latest IANA Time Zone Database in next build? Or this requests must directed to Shibby too?
http://www.iana.org/time-zones

P.S. Sorry for couple of usless issues..

**Comment by Jackysi** [comment]
Its not that I can't add it, but I want to keep same Firmware as Shibby runs because I have no time for these features. So yeah it would be best if you request this with him. I work on GUI only due to my limited free time. Please don't apologize, Its not a problem that is why I'm here.
