### ISSUE TITLE
UI says qos disabled but enabled in QOS tab...

### ISSUE THREAD

**Issue by lceron80** [Jackysi/advancedtomato#200]
i'm experiencing an issue where the UI says that qos is disabled in the bandwith limiter tab but is enabled in the qos tab.  i have posted two videos with AdvancedTomato and tomatoshibby to verify that it only happens with AdvancedTomato.

AT 
https://mega.nz/#!jIlyFbjR!dhM3EhDuat9FJPagBRJv0yD9qhyjpmHoyd6Rvyvj3mM
TShibby 
https://mega.nz/#!HAcgECBS!NHhOqepTETyStoqkH05d7f3zqpkcjR0AzEj3IZXOGBs

EA6500v2
Advanced Tomato Version 3.2-137

**Comment by Jackysi** [comment]
Fixed, see reference
