### ISSUE TITLE
Too big image

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#209]
Latest build of firmware 3.3-138 for Tenda N60 is too big. Can't upgrade.

**Comment by Jackysi** [comment]
Ill try to remove some feature, though that means there will be a feature less =/.

P.S.: I've checked and N60 features are already skimmed as much as they can be. For further minification we would nee some developer who knows more about these file systems and firmware images.

**Comment by upgap** [comment]
Same problem here. Firmware 3.3-138 for Tenda N60 is too big. Why isn't it removed from download ? (until the issues are resolved) What's the point of providing a firmware no one can flash ?   Anyway, I've bought a new (supported) router today with more than 8 MB Flash RAM to get rid of  those problems hopefully for very long time.

**Comment by Jackysi** [comment]
Some people were successful flashing it so I'm not removing it for those who are. Don't ask me how that is possible.
