### ISSUE TITLE
Broken links in QOS graphs 

### ISSUE THREAD

**Issue by aditaga** [Jackysi/advancedtomato#21]
I'm using version 2.4-123 K26 USB AIO on a Netgear WNR3500Lv2

Clicking on the pie chars or on a table row in the QOS page lead to an error:

http://router/#qos-detailed.asp?class=9

ERROR occured!
There has been error while loading a page, please review debug data bellow if this is isolated issue.
If this is not an isolated issue, please create issue with details bellow and how to reproduce the error at https://github.com/Jackysi/advancedtomato2/issues.

Detailed information:

init@http://router/js/jquery.min.js line 2 > eval:335:22
@http://router/js/jquery.min.js line 2 > eval:1:1
.globalEval@http://router/js/jquery.min.js:2:4243
.domManip@http://router/js/jquery.min.js:3:21389
.append@http://router/js/jquery.min.js:3:18980
.html/<@http://router/js/jquery.min.js:3:20344
.access@http://router/js/jquery.min.js:2:5778
.html@http://router/js/jquery.min.js:3:20018
loadPage/TomatoAJAX.onCompleted@http://router/js/advancedtomato.js:215:3
XmlHttp.prototype.onReadyStateChange@http://router/tomato.js:1604:1
THIS/<@http://router/tomato.js:1856:28
E(...) is null

**Comment by Jackysi** [comment]
Sorry for long response, this issue has been reported before and when I saw it on the issues, I forgot to reply. I am aware of the error. ARM has different QOS so I'm unable to properly debug this, but I will try when Shibby releases 124 on Tomato repo.

**Comment by aditaga** [comment]
Hi,

I tried to track down this problem. So when I click on a pie slice in QOS graphs view, ajax code will make this GET request:

http://router.lan/qos-detailed.asp?class=5?_http_id=TIDfaf867d1dd571bf7

which is badly-formed (notice the repeated question marks). I made a patch to fix this.

```
--- advancedtomato.js   2014-12-21 00:57:21.000000000 +0100
+++ advancedtomato.js   2014-12-21 00:57:45.000000000 +0100
@@ -294,7 +294,12 @@
    }

    // Execute Prototype
-   TomatoAJAX.get(page);
+   var parts = page.split("?");
+   if (parts.lenght >  1) {
+       TomatoAJAX.get(parts[0], parts[1]);
+   } else {
+       TomatoAJAX.get(page);
+   }
 }

 // Nprogress
```

But there is one more issue to fix. When class is set, this line of code in qos-detailed.asp gets executed:

`if (viewClass != -1) E('stitle').innerHTML = 'Details: ' + abc[viewClass] + ' <span id=\'numtotalconn\'></span>';`

And it gives an error which is catched by your code in advancedtomato.js:

```
TypeError: Cannot set property 'innerHTML' of null
    at init (eval at  (http://router.lan/js/jquery.min.js:2:4243), :335:44)
    at eval (eval at  (http://router.lan/js/jquery.min.js:2:4243), :1:1)
    at eval (native)
    at Function.x.extend.globalEval (http://router.lan/js/jquery.min.js:2:4243)
    at x.fn.extend.domManip (http://router.lan/js/jquery.min.js:3:21416)
    at x.fn.extend.append (http://router.lan/js/jquery.min.js:3:18985)
    at null. (http://router.lan/js/jquery.min.js:3:20357)
    at Function.x.extend.access (http://router.lan/js/jquery.min.js:2:5780)
    at x.fn.extend.html (http://router.lan/js/jquery.min.js:3:20020)
    at Object.TomatoAJAX.onCompleted (http://router.lan/js/advancedtomato.js:215:36)Cannot set property 'innerHTML' of null
```

And this is how far I got today.

**Comment by Jackysi** [comment]
Hmm great! Tho I wouldn't do it as you did, lets rather remove the first "?" which is useless. That should fix both issues here :)

**Comment by Jackysi** [comment]
The invalid (Bad formed) address doens't really cause the issue. Problem is that 
<pre>if (viewClass != -1) E('stitle').innerHTML = 'Details: ' + abc[viewClass] + ' <span id=\'numtotalconn\'></span>';</pre> actually tries to write details into DIV ID stitle which doesn't exist.
This fixes the issue: https://github.com/Jackysi/AdvancedTomato-V2/commit/a2632d30f5acaeda0e772810b89650160ae23bf6

Thanks, I wouldn't find this without your help ;)

P.S.: URL with double ?? is not "actually" bad formed. The sign "?" is common for PHP language. Which  Tomato is not. You could use ?? or ## or any thing really to split information in the URL. Tomato doesn't mind if you use double ?? since it replaces the var "?_http_id=TIDfaf867d1dd571bf7" in the handler anyway.

**Comment by aditaga** [comment]
Thanks, this was fast :)

But please take another look at my patch. I think without it the viewClass variable is assigned a wrong value on line 33 in qos-detailed.asp, which would result in the QOS detail page showing an unfiltered view. The patch makes sure TomatoAJAX.get() is invoked with the right parameters (it expects query variables to be passed in the second parameter). In practice the difference in the constructed URL is only one character.

```
http://router.lan/qos-detailed.asp?class=5?_http_id=TIDfaf867d1dd571bf7  <--- before
http://router.lan/qos-detailed.asp?class=5&_http_id=TIDfaf867d1dd571bf7  <--- after
```

BTW, AdvancedTomato has the best damn looking router UI ever ;)

**Comment by Jackysi** [comment]
I understand your patch, don't worry :D I'm just saying its uneccessary to parse it on each page. This is original prototype for AJAX:

<pre>XmlHttp.prototype = {
    addId: function(vars) {
        if (vars) vars += '&';
        else vars = '';
        vars += '_http_id=' + escapeCGI(nvram.http_id);
        return vars;
    },
    get: function(url, vars) {
        try {
            vars = this.addId(vars);
            url += '?' + vars;
            this.xob.onreadystatechange = THIS(this, this.onReadyStateChange);
            this.xob.open('GET', url, true);
            this.xob.send(null);
        }
        catch (ex) {
            this.onError(ex);
        }
    },
    post: function(url, vars) {
        try {
            vars = this.addId(vars);
            this.xob.onreadystatechange = THIS(this, this.onReadyStateChange);
            this.xob.open('POST', url, true);
            this.xob.send(vars);
        }
        catch (ex) {
            this.onError(ex);
        }
    },
    abort: function() {
        try {
            this.xob.onreadystatechange = function () { }
            this.xob.abort();
        }
        catch (ex) {
        }
    },
    onReadyStateChange: function() {
        try {
            if (typeof(E) == 'undefined') return;   // oddly late? testing for bug...
            if (this.xob.readyState == 4) {
                if (this.xob.status == 200) {
                    this.onCompleted(this.xob.responseText, this.xob.responseXML);
                }
                else {
                    this.onError('' + (this.xob.status || 'unknown'));
                }
            }
        }
        catch (ex) {
            this.onError(ex);
        }
    },
    onCompleted: function(text, xml) { },
    onError: function(ex) { }
}</pre>

It already has exactly the same code (well result) as you wrote, so what I'm saying is I will adapt that code and fix it from origin. Your code is just "QUICK FIX" which is on long term unnecessary and it reduces GUI performance (Javascript profiling). Don't get me wrong, I appreciate your effort big time! But I'm perfectionist :D.

Thanks for the compliment, that was the idea :P

P.S.: This is the fix: https://github.com/Jackysi/AdvancedTomato-V2/commit/d49be300947dee464a4ae25c05a433bcaec497e2

**Comment by aditaga** [comment]
Yes, your solution is more proper :) I've even tested it, and it works.
