### ISSUE TITLE
Save button on the 'USB & NAS > USB Support' page does not work for R7000

### ISSUE THREAD

**Issue by terrelsa13** [Jackysi/advancedtomato#210]
Updated my R7000 #1 from AT v3.2-137 to AT v3.3-138 and cleared the NVRAM during and after the update. I was manually setting it back up and noticed the Save button on the 'USB & NAS > USB Support' page did not work. I erased the NVRAM again, this did not fix it. I re-flashed v3.3-138 while erasing the NVRAM no luck. Ended up using Shibby v138, nbd.

**_Temporary Work Around:_**
Updated R7000 #2, did a fresh install (erased all NVRAM) with Shibby v138 and confirmed the button works with Shibby. Completed manually entering settings with Shibby v138. I then upgraded R7000 #2 to AT v3.3-138 **without** erasing NVRAM. Still the same behaviour as as R7000 #1.

Shibby: tomato-R7000-ARM--137-AIO-64K.trx (Button works)
Shibby: tomato-R7000-ARM--138-AIO-64K.trx (Button works)
AT: tomato-R7000-AT-ARM-3.2-137-AIO-64K.trx (Button works)
AT: tomato-R7000-AT-ARM-3.3-138-AIO-64K.trx (Button does not work)

I also did fresh installs of AT v3.3-138 on 4x RT-N66U's and 1x WNR3500Lv2. Save button works perfectly on all of these.

Let me know if there's something else you'd like me to try, or other information you need.

**Edit:** I downloaded a new copy of AT v3.3-138 from the website three times on two different machines. Verified the md5sum 2 of 3 times.

**Comment by Jackysi** [comment]
All of that was completely uneccessary. Here: https://github.com/Jackysi/advancedtomato-gui/commit/b3e28aa3d0b6cf3756c924b3bec373c331f0126a

Thanks for report, even if its too late =)!
