### ISSUE TITLE
Timezone changing by itself.

### ISSUE THREAD

**Issue by RonNovy** [Jackysi/advancedtomato#211]
Tomato Firmware 1.28.0000 MIPSR2-3.2-137 K26 USB Mega-VPN
Linksys E2500 v3

The timezone seems to change itself any time the wireless connection goes down and resets.  I am running the router with the 5G in wireless client mode and I'm connecting one computer through the wired interface and another to the 2.4G wireless connection.

The router will occasionally lose wireless connection for some reason or another and the other day while looking at the logs I noticed that the timezone was not set correctly.  Today it changed again by itself.  Seems to change to random places.

To be honest, I had previously set the transmit power of both the 2.4G and 5G to about 200mw and it was crashing and doing strange things every hour or so.  When I realized this was a mistake I changed them both to about 45mw and it has been mostly stable now.  So, I'm not sure if the occasional crash and change of timezone is because the chips are now damaged or because of something else.

A different issue but also worth mentioning is that the speed of the connections didn't seem to be stable on the E2500 when under heavy load until I set the CPU speed to 500MHz.  The default CPU speed that Advanced Tomato set it to was 300MHz, but I believe that this CPU is capable of 500MHz and I believe that should be the default for the E2500.  I could be wrong, though.

**Comment by Jackysi** [comment]
Sorry but these issues are unrelated to the User Interface. You should contact Shibby who is the actual firmware developer at https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open. From my knowledge he has no issues tracker for the RT-N routers (Like E2500v3) so not sure he'll not simply close the issue. Anyway I have no knowledge to fix or even give u any tips for the above problem.
