### ISSUE TITLE
Issues over 32kb of nvram

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#212]
Hi,

I'm using the Linksys EA6500 v2. I know this router has issues with reading its whole 64kb of nvram, however my knowledge was that Tomato did not have the issue as it manually addresses the whole 64kb.

It recognizes the whole 64kb of nvram, but if I go over 32kb or 50.00%, upon reboot a lot of data is corrupted and I lose my 2.4GHz eth1.

Any ideas? I am using the latest version of AdvancedTomato, the AIO version. I have also tried older versions and even builds from Shibby.

**Comment by Jackysi** [comment]
Sorry but these issues are unrelated to the User Interface. You should contact Shibby who is the actual firmware developer at https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open. From my knowledge he has no issues tracker for the RT-N routers (Like E2500v3) so not sure he'll not simply close the issue. Anyway I have no knowledge to fix or even give u any tips for the above problem.
