### ISSUE TITLE
Both Enable and Disable button showing for virtual wireless network 

### ISSUE THREAD

**Issue by JJohnson1988** [Jackysi/advancedtomato#213]
I mentioned this on linksysinfo.org:

There exists both an Enable and Disable button at once when displaying information about my virtual wireless network (not the primary ones). Pretty certain only one or the other should be displayed since it's a toggle.
![bothtogglebuttonsbug](https://cloud.githubusercontent.com/assets/8522214/17692448/ae374c8e-634e-11e6-87ea-1a74f6cb3d28.png)

**Comment by Jackysi** [comment]
I will look into it, the console shows no errors so its possible I simply forgot to bind the buttons to the Virtual Interfaces. That's good, easier to fix.
