### ISSUE TITLE
Advanced > VLAN, the menu is not appear

### ISSUE THREAD

**Issue by s3n0** [Jackysi/advancedtomato#218]
**FW:** tomato-K26USB-1.28.AT-RT-N5x-MIPSR2-**3.3-138**-AIO.trx

**Device:** ASUS RT-N16

**Screenshot:** I forgot it. Sorry mate. I was flashing back the original firmware of Shibby already - there is VLAN-menu  working properly. 

**BUG:** I see in the menu 'Advanced>VLAN' there only two lines - first line with text "Wireless" and second line with text ...ehm...I forgot it, sorry... :-/ 

**What I was trying already:**
-NVRAM reset
-many router restarts
-reflash your firmware once again
-Mozilla Firefox & Goole Chrome (with latest updates, both of them)

Good Luck
Mike

**Comment by Jackysi** [comment]
https://github.com/Jackysi/advancedtomato/issues/206
