### ISSUE TITLE
"Logging Configuration" link broken inside Status>Logs page when "Log Internally" is disabled

### ISSUE THREAD

**Issue by AndreDVJ** [Jackysi/advancedtomato#22]
Whenever log configuration is disabled, and you wish to go to the logging configuration page using that shortcut:

![disabled1](https://cloud.githubusercontent.com/assets/8248926/5069544/54bb66fc-6e42-11e4-8e81-46ba1fa1fde3.PNG)

You get a broken logging configuration page, doesn't redirect correctly.

![disabled2](https://cloud.githubusercontent.com/assets/8248926/5069551/6855c78e-6e42-11e4-87fb-8ad026b8f339.PNG)

This affects the latest release, 2.4-123.

**Comment by Jackysi** [comment]
Thanks for reporting the issue!
