### ISSUE TITLE
QOS scheduler problem

### ISSUE THREAD

**Issue by rafalantas** [Jackysi/advancedtomato#221]
Hi,

I'm  trying to enable QOS on Ac66u and Im getting "The field "qos_pfifo" is invalid. Please report this problem." I didnt touch any of setting bellow. Just changed scheduler to fq_codel. 

thanks,
Rafal

**Comment by Jackysi** [comment]
Will be looked into

**Comment by ghost** [comment]
Same here. Tenda N60

**Comment by Jackysi** [comment]
The scheduler fq_codel is only available on ARM. The GUI shows it because sometimes I miss changes that shibby does between branches (RT-AC/ARM/RT-N). Anyway, fixed.

**Comment by Jerezano** [comment]
I still have this issue on E2500v1

**Comment by f00b4r0** [comment]
Issue still exists in v3.3-138 on E2500v3. codel and fq_codel options are invalid as they are not supported by the provided kernel.

**Comment by Jackysi** [comment]
The fix applies to version 3.4-138+.
