### ISSUE TITLE
No guide for Huawei WS880 install

### ISSUE THREAD

**Issue by tcreek** [Jackysi/advancedtomato#232]
Since there is no guide, I attempted the install based on some other routers, and the obvious choice: 
Firmware Update.

However, when trying to connect to it, all I get is in red letters:

"Upgrade failed. Please choose the correct file. "

This is attempting with WS880-AT-ARM-3.3-138-AIO-64K.trx

Thanks

**Comment by Jackysi** [comment]
Not a support section...
