### ISSUE TITLE
SFTP server running but setting off. 

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#234]
I'm seeing the SFTP running on the router although I have never changed the default off. Don't think it's me or Tomato. GUI not reflecting true state.

**Comment by Jackysi** [comment]
Can you provde a screen shot of Tools -> System Commands and enter: <pre>ps | grep ssh</pre>

**Comment by Jackysi** [comment]
P.S.: Tomato doesn't run SFTP at all. It only has SSH.
