### ISSUE TITLE
If both "Auto resolve addresses" and "show shortcuts" are selected, the IP's are not auto-resolved on reentry

### ISSUE THREAD

**Issue by vrapp** [Jackysi/advancedtomato#237]
In Quality of Service/View Details, or Transfer Rates, if the user selects both "auto-resolve" and "show shortcuts", then on re-entry to this menu the addresses are not resolved, and there's infinitely spinning wheel. Perhaps these two settings should be mutually-exclusive.

To reproduce:
Go to Quality of Service/Transfer Rates
expand Filters, and check "Auto resolve addresses" and "Show shortcuts"
The IP's will become resolved
go to any other node in the menu
return to Service/Transfer Rates

Expectation: the IP's in source and destination should be auto-resolved at once
Reality: they are not; the cursor appears as waiting (spinning wheel), and it does not change, 

Uncheck and re-check "Auto resolve addresses" - the IP's will become resolved immediately, and spinning wheel will change to normal cursor.

![ss](https://cloud.githubusercontent.com/assets/2778779/19215128/f38b42b4-8d5a-11e6-96d6-3cb561bea333.png)

The same in  Quality of Service/View Details.

If  "Show shortcuts"is not selected, then it works OK.

It was tested in Chrome, Firefox, and IE with the same result.

**Comment by Jackysi** [comment]
Does this work on Shibby?

**Comment by vrapp** [comment]
> Does this work on Shibby?
> No idea, I only have advanced tomato. If I understand correctly, Advanced is about web interface, so since this is purely web interface issue, it's probably AT-specific.

**Comment by Jackysi** [comment]
That's not true. The data for the web interface comes from the firmware (custom C based HTTPD handler) which I don't have knowledge to fix. And so its possible that this issue is present on both firmwares. 

I will give it a look when I have time.

**Comment by Jackysi** [comment]
I've checked this and i'm pretty sure this bug is Tomato related not just AdvancedTomato. I don't think it will be fixed anytime soon because there are more pressing issues to take care first. But I will have it as a note maybe to fix it one day.

**Comment by Jackysi** [comment]
Seems to work fine in latest 3.4-140 (tested it for few times)
