### ISSUE TITLE
Cannot upload .html page for captive portal

### ISSUE THREAD

**Issue by NHLGames** [Jackysi/advancedtomato#241]
I am trying to enable the captive portal but when I upload my .html page I get this error:

```
500 Unknown
Read error
```

**Comment by Jackysi** [comment]
Can you confirm this works on Tomato by Shibby?

**Comment by Jackysi** [comment]
I've tested this "Issue". The upload works fine but the redirect after upload is to unexisting page. That's why you get that error. I fixed the issue with redirect so this issue can be closed :).
https://bitbucket.org/jackysi/advancedtomato-arm/commits/10e38e2236008a2d14eff88dcb03385bc659f839
