### ISSUE TITLE
Bytes vs bits

### ISSUE THREAD

**Issue by f00b4r0** [Jackysi/advancedtomato#245]
v3.3-138 Mega-VPN

in IP Traffic -> Transfer Rates
IP Traffic Details page mentions "bytes/s" but the data displayed is in _bits/s_ :)

**Comment by Jackysi** [comment]
I'll check.

**Comment by f00b4r0** [comment]
It's no longer doing it here, after some configuration changes I made (including fixing QoS by hand). I don't know which change fixed it though.

**Comment by Jackysi** [comment]
Too bad, would be nice to know. Well I will close for now but if you ever encounter this issue again we will reopen this issue and track down the problem.
