### ISSUE TITLE
Broken donate link

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#25]
on info/about page on the firmware. You shee who has worked on the project.

3 donate buttons.
first button goes with target blank (i like) to this page
https://advancedtomato.com/donate/ <<<--error 404

second
Shibby donate button is not target blank (i dont like).
works butt like to be target blank.

last (buttom)
who i donate?

**Comment by Jackysi** [comment]
Thanks for reporting! Darn! Didn't even notice!
I will fix them! Last donation goes to the original Tomato developer Jonathan Zarate.
