### ISSUE TITLE
No VPN features available

### ISSUE THREAD

**Issue by darkluk13** [Jackysi/advancedtomato#250]
I cant see options for VPN, is it removed or did i something wrong?
I have Version 3.2-137, because i cant flash newer version, too big file :(

**Comment by Jackysi** [comment]
router? image name?

**Comment by darkluk13** [comment]
Oh sorry, it's tenda n60, image Version 3.2-137.

**Comment by Jackysi** [comment]
from my knowledge that router doesn't have enough space to fit VPN on it. My firmware is based on Shibby's and I do no changes regarding packaging, so I'd say that I can't influence this. 

Also AdvancedTomato is slightly bigger than Tomato GUI. So there is no space for the additional features anyway. Think about switching to Shibby's releases instead.
