### ISSUE TITLE
Remote access to control panel and forwarded ports don't work

### ISSUE THREAD

**Issue by vrapp** [Jackysi/advancedtomato#251]
I noticed that about 2 weeks ago it became impossible to connect to my router (Asus RT-AC68P/U B1) from the outside. It was possible before.

I run Advanced Tomato 3.3-138 AIO, which connects to internet via Speedstream DSL modem in PPPoE. There are no problems to browse internet. Remote administration is enabled on port 8080 via HTTP. But when I try to open router's page from outside, it does not connect - I immediately receive ERR_CONNECTION_REFUSED.

Also don't work forwarded ports. However, Tomato's remote FTP, NGINX Web Server, and remote SSH are accessible from outside, if I enable their remote access.

I checked whether the connection was blocked by router's firewall. It was not. I also ran network monitor at the remote computer:

3620	18:16:36 10/30/2016	6.0850420	telnet.exe	<external address>	<my ddns address>	TCP	TCP:Flags=......S., SrcPort=62856, DstPort=HTTP Alternate(8080), PayloadLen=0, Seq=4016202513, Ack=0, Win=8192 (  ) = 8192	{TCP:49, IPv4:35}
3621	18:16:36 10/30/2016	6.1147770	telnet.exe	<my ddns address>	<external address>	TCP	TCP:Flags=...A.R.., SrcPort=HTTP Alternate(8080), DstPort=62856, PayloadLen=0, Seq=0, Ack=4016202514, Win=0	{TCP:49, IPv4:35}

So it looks like connection was made, but router refused to serve the page.

What I tried:
1. tried another Asus router with Merlin firmware, with the same DSL modem. The was no problem, I was able to connect from outside to the router's control panel on the same port 8080, and to the ports forwarded on the router, like always before.
2. performed router reset, including with nvram. Did not help.

What to look at?

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
