### ISSUE TITLE
 DIR-868L

### ISSUE THREAD

**Issue by jnko** [Jackysi/advancedtomato#252]
Router : D-Link DIR-868L
AdvTomato 3.3-138
Detailed (serial console output) below
To reproduce: Flash AdvTomato and try to start.

I tried to flash AdvTomato Version 3.3-138  on a DIR-868L which does not work.
Flashing works, kernel boots but it didn' reach the init system.
According to /proc/cmdline /sbin/preinit has run.
Since I do not know yet very much about tomato (but know a lot about linux) I'm trying to dig in a little bit.
Any advice? 

I will go back every release to see which one works and try to get some more information.

`
Digital core power voltage set to 0.9375V
SVN revision: 1164
Decompressing...done
Digital core power voltage set to 0.9375V

R 1.13
07DC06011801080000000000001A103F01000000

S30040293
00001F70

00000004
00000047
0000003100000031

SVN revision: 1164
Decompressing...done
Found a ST compatible (Marconix) serial flash with 32 64KB blocks; total size 2MB

CFE version 6.30.163.18 (r377098) based on BBP 1.0.37 for BCM947XX (32bit,SP,)
Build Date: Wed Apr 29 11:55:52 CST 2015 (tom_lin@101)
Copyright (C) 2000-2008 Broadcom Corporation.

Init Arena
Init Devs.
Boot partition size = 262144(0x40000)
Found a AMD NAND flash:
Total size:  128MB
Block size:  128KB
Page Size:   2048B
OOB Size:    64B
Sector size: 512B
Spare size:  16B
ECC level:   8-bit
Device ID: 0x01 0xf1 0x80 0x1d 0x01
DDR Clock: 533 MHz
Info: DDR frequency set from clkfreq=800,*533*
et0: Broadcom BCM47XX 10/100/1000 Mbps Ethernet Controller 6.30.163.18 (r377098)
CPU type 0x0: 800MHz
Tot mem: 262144 KBytes

CFE mem:    0x00F00000 - 0x0109357C (1652092)
Data:       0x00F5A430 - 0x00F5B42C (4092)
BSS:        0x00F5B438 - 0x00F9157C (221508)
Heap:       0x00F9157C - 0x0109157C (1048576)
Stack:      0x0109157C - 0x0109357C (8192)
Text:       0x00F00000 - 0x00F4F55C (324956)
Boot:       0x01094000 - 0x010D4000
Reloc:      I:00000000 - D:00000000

Board Name: WRGAC35
SVN revision: 1164
We disable the arp for self.
emergency web server running ...
We disable the arp for self.
Device eth0:  hwaddr 00-90-4C-0F-F0-18, ipaddr 192.168.0.1, mask 255.255.255.0
        gateway not set, nameserver not set
[ALPHA] PRESS Ctrl-C TO ENTER EMERGENCY MODE ...
Loader:raw Filesys:tftp Dev:eth0 File:: Options:(null)
Loading: Failed.
Could not load :: Timeout occured
Dest=00008000, source =02000000, filename=nflash1.trx
[/home/tom_lin/dir868/bcm4708_ARM/src/cfe/cfe/arch/common/board/bcm947xx/src/ui_bcm947xx.c alpha_load 298] seama header magic mismatched
Loader:raw Filesys:raw Dev:nflash0.os File: Options:(null)
Loading: .... 4144640 bytes read
Entry at 0x00008000
Closing network.
emergency web server closing ...
Starting program at 0x00008000
console [ttyS0] enabled, bootconsole disabled
serial8250.0: ttyS1 at MMIO 0x18000400 (irq = 117) is a 16550
brd: module loaded
loop: module loaded
pflash: found no supported devices
Boot partition size = 262144(0x40000)
Creating 2 MTD partitions on "bcmsflash":
0x000000000000-0x000000040000 : "boot"
0x0000003f0000-0x000000400000 : "nvram"
Found a AMD NAND flash:
Total size:  128MB
Block size:  128KB
Page Size:   2048B
OOB Size:    64B
Sector size: 512B
Spare size:  16B
ECC level:   8 (8-bit)
Device ID: 0x 1 0xf1 0x80 0x1d 0x 1 0xf1
lookup_nflash_rootfs_offset: offset = 0x0
nflash: squash filesystem with lzma found at block 13
Creating 2 MTD partitions on "nflash":
0x000000000000-0x000002000000 : "linux"
0x0000001a6d94-0x000002000000 : "rootfs"
PPP generic driver version 2.4.2
PPP MPPE Compression module registered
NET: Registered protocol family 24
PPTP driver version 0.8.5
=== PPTP init ===
Mirror/redirect action on
u32 classifier
    Actions configured
Netfilter messages via NETLINK v0.30.
nf_conntrack version 0.5.0 (3990 buckets, 15960 max)
xt_time: kernel timezone is -0000
ip_tables: (C) 2000-2006 Netfilter Core Team
TCP cubic registered
NET: Registered protocol family 10
ip6_tables: (C) 2000-2006 Netfilter Core Team
NET: Registered protocol family 17
L2TP core driver, V2.0
PPPoL2TP kernel driver, V2.0
802.1Q VLAN Support v1.8 Ben Greear <greearb@candelatech.com>
All bugs added by David S. Miller <davem@redhat.com>
Registering the dns_resolver key type
Northstar brcmnand NAND Flash Controller driver, Version 0.1 (c) Broadcom Inc. 2012
NAND device: Manufacturer ID: 0x01, Chip ID: 0xf1 (AMD NAND 128MiB 3,3V 8-bit)
Spare area=64 eccbytes 56, ecc bytes located at:
 2 3 4 5 6 7 8 9 10 11 12 13 14 15 18 19 20 21 22 23 24 25 26 27 28 29 30 31 34 35 36 37 38 39 40 41 42 43 44 45 46 47 50 51 52 53 54 55 56 57 58 59 60 61 62 63
Available 7 bytes at (off,len):
(1,1) (16,2) (32,2) (48,2) (0,0) (0,0) (0,0) (0,0)
Scanning device for bad blocks
Options: NO_AUTOINCR,NO_READRDY,BBT_SCAN2NDPAGE,
Creating 2 MTD partitions on "brcmnand":
0x000002000000-0x000008000000 : "brcmnand"
0x000004000000-0x000008000000 : "jffs2"
VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
devtmpfs: mounted
Freeing init memory: 216K

Hit ENTER for console...

emf: module license 'Proprietary' taints kernel.
Disabling lock debugging due to kernel taint
et_module_init: passivemode set to 0x0
et_module_init: txworkq set to 0x0
et_module_init: et_txq_thresh set to 0x0
eth0: Broadcom BCM47XX 10/100/1000 Mbps Ethernet Controller 6.37.14.86 (r456083)
wl_module_init: passivemode set to 0x0
wl_module_init: txworkq set to 0x0
PCI: Enabling device 0001:01:00.0 (0140 -> 0142)
eth1: Broadcom BCM4331 802.11 Wireless Controller 6.37.14.86 (r456083)
eth2: Broadcom BCM4360 802.11 Wireless Controller 6.37.14.86 (r456083)
/ #
`

Interfaces did not got an IP address
`/ # ip addr
1: lo: <LOOPBACK,MULTICAST,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 brd 127.255.255.255 scope host lo
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ifb0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 32
    link/ether b2:81:8b:5f:6d:ce brd ff:ff:ff:ff:ff:ff
3: ifb1: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 32
    link/ether 3a:28:ed:f6:87:a2 brd ff:ff:ff:ff:ff:ff
4: ifb2: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 32
    link/ether 82:8f:29:ca:eb:fb brd ff:ff:ff:ff:ff:ff
5: ifb3: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 32
    link/ether fa:41:6d:29:90:f2 brd ff:ff:ff:ff:ff:ff
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN qlen 1000
    link/ether 00:90:4c:0f:f0:18 brd ff:ff:ff:ff:ff:ff
7: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 00:90:4c:0d:c0:18 brd ff:ff:ff:ff:ff:ff
8: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 00:90:4c:0f:50:18 brd ff:ff:ff:ff:ff:ff
9: vlan1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 00:90:4c:0f:f0:28 brd ff:ff:ff:ff:ff:ff
10: vlan2@eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN
    link/ether 00:90:4c:0f:f0:18 brd ff:ff:ff:ff:ff:ff`

Process list:
`/ # ps www
  PID USER       VSZ STAT COMMAND
    1 root      1520 S    /sbin/preinit
    2 root         0 SW   [kthreadd]
    3 root         0 SW   [ksoftirqd/0]
    4 root         0 SW   [kworker/0:0]
    5 root         0 SW   [kworker/u:0]
    6 root         0 SW   [migration/0]
    7 root         0 SW   [migration/1]
    8 root         0 SW   [kworker/1:0]
    9 root         0 SW   [ksoftirqd/1]
   10 root         0 SW<  [khelper]
   11 root         0 SW   [kworker/u:1]
   53 root         0 SW   [sync_supers]
   55 root         0 SW   [bdi-default]
   56 root         0 SW<  [kblockd]
  111 root         0 SW   [kswapd0]
  158 root         0 SW   [fsnotify_mark]
  166 root         0 SW<  [crypto]
  242 root         0 SW   [mtdblock0]
  247 root         0 SW   [mtdblock1]
  252 root         0 SW   [mtdblock2]
  257 root         0 SW   [mtdblock3]
  288 root         0 SW   [kworker/0:1]
  289 root         0 SW   [kworker/1:1]
  292 root         0 SW   [mtdblock4]
  297 root         0 SW   [mtdblock5]
  691 root       664 S    hotplug2 --persistent --no-coldplug
  735 root      1508 S    blink_5g
  736 root      1440 S    console
  738 root      1376 S    syslogd -L -s 50 -b 1
  740 root      1384 S    /bin/sh
  741 root      1376 S    klogd
  757 root         0 SW   [khubd]
  818 root         0 SW<  [usbhid_resumer]
  925 root      1376 S    telnetd -p 23
  932 nobody    1588 S    dnsmasq -c 4096 --log-async
  936 root      1384 S    crond -l 9
  939 root      1504 S    sched start
  940 root      1044 S    rstats
  943 root       984 S    cstats
  953 root      1384 S    udhcpc -i vlan1 -b -s dhcpc-event -H unknown -O 33 -O 121 -O 249 -m -p /var/run/udhcpc-wan.pid
  954 root      1380 R    ps www`

Listening ports:
`/ # netstat -tul
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:domain          0.0.0.0:*               LISTEN
tcp        0      0 :::domain               :::*                    LISTEN
tcp        0      0 :::telnet               :::*                    LISTEN
udp        0      0 0.0.0.0:domain          0.0.0.0:*
udp        0      0 0.0.0.0:bootps          0.0.0.0:*
udp        0      0 :::domain               :::*`

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
