### ISSUE TITLE
Need IP-Sec for Lan to Lan VPN Network with a AVM Fritz.box 7490

### ISSUE THREAD

**Issue by Acer90** [Jackysi/advancedtomato#257]
Hello,

I Need a Ipsec Server to create a lan 2 lan Network with a fritzbox.
Here is a link from the Producer avm:
https://en.avm.de/service/vpn/how-to-tips/setting-up-a-vpn-connection-between-two-fritzboxes-for-individual-lan-ports/

thx for help.

**Comment by Acer90** [comment]
Router is a Netgear R7000 and Img Version is Tomato Firmware 1.28.0000 -3.3-138 K26ARM USB AIO-64K

**Comment by Jackysi** [comment]
Some how I don't see how that's anyhow related to "issues" or AdvancedTomato. Please don't post these things here rather use "Tomato" community at https://linksysinfo.org
