### ISSUE TITLE
VPN PPTP connects but doesn't allow access both ways.. 

### ISSUE THREAD

**Issue by jwprice** [Jackysi/advancedtomato#258]
I have 2 RT-AC68 routers. The server side is running the latest Merlin software. The second, client side, is using advancedtomato's latest version.
The reason for pptp is due to needing the client side to have a server side IP range to access the WD Cloud drive without having to setup or maintain a vpn on each computer / device.

The server uses 192.168.1.1/255.255.255.0, has a vpn set range of x.x.x.225-245.

The client uses 192.168.0.1/255.255.255.0... The client router ping tool can ping 192.168.1.1, but nothing behind the server router. Also on the client side of the router, no computer on this side can ping 192.168.1.1 directly. If I use windows pptp client I can access everything on the server side. So it seems as though the routing table for the server side isn't getting passed through to the client side. Also, the server side router can't ping either 192.168.0.1 or the 192.168.1.225 that the client router is using... I haven't tried accessing a client side IP from a server side device yet but that would seem to be mute since the server side router can't even get a ping response from the client side router gateway IP nor it's PPTP given IP... 

Is there a command to use in the client that can get the routing tables to work?

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
