### ISSUE TITLE
/opt/etc/config/ scripts not loading *.fire during boot since 2.4

### ISSUE THREAD

**Issue by erenfro** [Jackysi/advancedtomato#26]
Hey, I recently upgraded from AT 2.3 to 2.4, and.. To explain a little background:

I have a USB device in, mounted at boot using an init script from the AT Admin->Scripts->Init:
echo "LABEL=router /opt ext2 defaults 1 1" >> /etc/fstab

What's on USB that's fairly important as well, is /opt/etc/config, which has my *.wanup, *.init.fire, and *.rules.fire structured very simply as:
01-init.wanup
01-vip1.wanup
01-vip2.wanup
01-vip3.wanup
02-vip1.init.fire
02-vip2.init.fire
02-vip3.init.fire
10-vip1.rules.fire
10-vip2.rules.fire
10-vip3.rules.fire

In addition, as a just-in-case factor, I have /opt/.autorun to post-load these rules per autorun, in case of USB mounting latency:

```
#!/bin/sh

if [ -f /var/notice/wan ]; then
        for s in /opt/etc/config/*.wanup; do $s; done
        for s in /opt/etc/config/*.fire; do $d; done
fi
```

The odd part is, since the upgrade, only the _.wanup scripts actually load, none of the *.fire scripts do, however. What this tells me is that it does initialize the USB before the WAN is up, but the tomato boot-up process itself is not loading the scripts in /opt/etc/config/_.fire anymore.

**Comment by Jackysi** [comment]
Hmm, sounds strange. Could you contact Shibby about this issue? I will check it out but I can't promise much since I am not really Linux expert. Shibby on other hand is.

**Comment by erenfro** [comment]
How do you contact Shibby? That's been my main issue so far, is actually finding a proper means to contact him about anything related to things like this.

**Comment by Jackysi** [comment]
Easiest way would be to pm him on http://linksysinfo.org/ (Username: 
Shibby20). Its the way we discuss things too.

**Comment by erenfro** [comment]
I think I solved this issue. There was actually a bug in my own /opt/.autostart script. Before, it never mattered because the USB device came up before the WAN was fully activated, but now, it's not, so the autorun of my script was expecting to do things it would've normally handled in that case. 

Here's my script, and I'll describe what I had done wrong:

``` bash
#!/bin/sh

if [ -f /var/notice/wan ]; then
        for s in /opt/etc/config/*.wanup; do $s; done
        for s in /opt/etc/config/*.fire; do $s; done
else
        for i in $(seq 1 5)
        do
                if [ -f /var/notice/wan ]; then
                        for s in /opt/etc/config/*.fire; do $s; done
                        break
                else
                        sleep 15
                fi
        done
fi
```

Where I was doing `for s in /opt/etc/config/*.fire; do $s; done` I had used $d for the variable in that loop, so typo. :) The wanup scripts were using the proper $s variable, fire was not. 

Once that was corrected, my .autorun is now running the appropriate rules accordingly and handles both scenarios properly.
