### ISSUE TITLE
Bad "tab" when router_name contains apostrophe

### ISSUE THREAD

**Issue by fyellin** [Jackysi/advancedtomato#264]
My router name is "Orbit's Router".  This is the value set in the router_name variable.

Previously, my tab would should the icon and 
    "[Orbit's Router] System ID".  
Now it shows 
     "[Orbit&#39;s Router]".  
It appears that there is some unnecessary HTML quoting going on.

**Comment by Jackysi** [comment]
I will look into it =) Thanks

**Comment by Jackysi** [comment]
I've checked and I've realized tomato HTTPD handler quotes ' and " for safety. Not sure why but that's how it works. For now I won't be changing this or working on it, but thanks for report anyway.
