### ISSUE TITLE
Display bug for Wireless  SSID and Shared Key on mobile

### ISSUE THREAD

**Issue by oozy-jet-portable** [Jackysi/advancedtomato#265]
I have a Wireless SSID on eth1 and a second SSID on wl0.1.

On my laptop details are displayed correctly.
On my phone, Domain and Password details from my DDNS setup are shown in the SSID and Shared Key fields, respectively.

**Comment by Jackysi** [comment]
Would be useful to know browsers, router, firmware used and perhaps OS?
