### ISSUE TITLE
"Update available!" message even after already updated

### ISSUE THREAD

**Issue by vrapp** [Jackysi/advancedtomato#268]
After firmware was updated to 3.4-138 , it still shows "Update Available! AdvancedTomato version 3.4-138 has been released and it is available for download.	"
![capture-12-05-00004](https://cloud.githubusercontent.com/assets/2778779/20913589/cdde39a6-bb3e-11e6-8b4c-d276bf524b88.png)

...also, in the message itself "it" is not needed: "and is available for download".

**Comment by Jackysi** [comment]
Which router? It could be cache which is strange because tmp folder clears on reboot (after flash). I have N66U and R7000 and I can't replicate the issue.

**Comment by vrapp** [comment]
Asus RT-AC68P/U B1

The message showed up immediately after having upgraded. Then I clicked "x" to close it, it closed and no longer shows up.

**Comment by vrapp** [comment]
...which ,maybe presents another problem. If this message can be hidden by closing it, if the upgrade _was_ in fact available, how to re-invoke it again? There's no "check for upgrade" button on the "upgrade" page admin-upgrade.asp .

**Comment by Jackysi** [comment]
When you hide update box, it hides that specific update so 3.4-138. Next update 3.5-138 or 3.4-139 will be shown normally.

**Comment by vrapp** [comment]
What if I hide the next update without installing it, for whatever reason? will I be able to see it again?

**Comment by Jackysi** [comment]
The specific version you disabled will not ever appear again. But if in above example 3.5-139 is released, you will see the notification again.

**Comment by Jackysi** [comment]
I can't reproduce this issue. Been trying to since version 138 :/
