### ISSUE TITLE
Unchecked checkboxes are invisible

### ISSUE THREAD

**Issue by vrapp** [Jackysi/advancedtomato#269]
With the current color scheme. unchecked checkboxes are almost invisible until you hover the mouse over them. Here's typical example.

![s1](https://cloud.githubusercontent.com/assets/2778779/20926135/893aa090-bb80-11e6-9c83-7f68f482c392.png)

![s2](https://cloud.githubusercontent.com/assets/2778779/20926134/893342a0-bb80-11e6-9ae9-1c8188d78c50.png)

Tried in Firefox, Chrome, and IE - looks the same everywhere.

**Comment by Jackysi** [comment]
They're supposed to be. If using RGB or sRGB monitor it should appear just slightly. Which is the idea because you can also click on "Enable" and it will check the check box. Also not sure what this is? bug report defo since this is not a bug =)

P.S.: These sort of things should go to community forums. http://www.linksysinfo.org/index.php?threads/advancedtomato-flat-material-designed-web-gui-shibby-base.70254/page-9

**Comment by vrapp** [comment]
The problem with clicking on "enable" is that you don't see where to click. Really, if I need to enable something, I have to slowly move the mouse horizontally until the cursor changes, that's how I identify where the checkbox is. When I used it first time, I could not understand how to enable things at all, until I finally figured, almost accidentally, that in fact there's a checkbox, although almost invisible. Be at just a slightly wrong angle to the monitor, and you already don't see the checkbox, at least not without really, really closely looking. It shouldn't be that way.

**Comment by Jackysi** [comment]
Yes, but that's up to a discussion (community?). I don't agree with you for example. Unless at least some amount of people agree with you, I won't implement changes to that. That's not a bug its how I wanted it. This is still my project so its up to me how the things are going to look like no?

 I don't have the same issues as you, guess quality monitor (I have 3 calibrated monitors) make a difference.

**Comment by vrapp** [comment]
[One more user agreed](http://www.linksysinfo.org/index.php?threads/advancedtomato-flat-material-designed-web-gui-shibby-base.70254/page-9#post-282259) :-)
