### ISSUE TITLE
extra virtual wireless dont work

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#27]
if i add wl0.1 (same for wl1.1) and choose save, it still say saving... (wait 2 min)

If i press on virtual wireless nothing saved.

Asus ac66u  - last advanced tomato version

**Comment by Jackysi** [comment]
I am sorry for this late response, I actually saw the issue same day you posted. I was so busy I had no time to give it a look. I will do that asap.

**Comment by ghost** [comment]
I have found the problem was on Win 7, IE (butt out my head i dont know the IE version). Look when im home.

If i use my phone / Fiefox it was OK.

**Comment by Jackysi** [comment]
Any updates for this?

**Comment by ghost** [comment]
I cant check my router is lent to a friend
Op 8 mrt. 2015 13:18 schreef "Jacky Prahec" notifications@github.com:
