### ISSUE TITLE
Connection lost error

### ISSUE THREAD

**Issue by D156u153** [Jackysi/advancedtomato#274]
v3.4-138Max

When trying to access the "wireless" section under "Advanced Settings" the loading bar gets about half way through loading and then states "Connection lost error" and I am unable to get to that section. I tried different computers and browsers with the same results.

Just noticed it is also doing the same thing for "Network" under "Basic settings" as well.

**Comment by Jackysi** [comment]
Check F12 developers console and paste the screen shot if any errors occur. I'm pretty sure there is something wrong with your NVRAM values or router configuration which is causing javascript errors which end up showing "Connection Lost Error".

**Comment by Mako88** [comment]
![image](https://cloud.githubusercontent.com/assets/4147635/24779972/84eeacb0-1af9-11e7-9d39-96586e818dca.png)

I'm getting the same error, and here's a screenshot :)

**Comment by Jackysi** [comment]
From screenshot above its visible that router simply does not respond. The UI it self doesn't really have anything to do with that. Is there anything about HTTPD errors in Logs?

**Comment by garzonm77** [comment]
I had the same issue clicking on upgrade. As a workaround, I was able to right-click on Upgrade and open in New Tab...it opened up and upgraded to the latest version for my router (Netgear r7000). After the upgrade I didn't have the issue anymore.

**Comment by Jackysi** [comment]
Guess its resolved? No one bothers to write about it anymore =)?
