### ISSUE TITLE
Suggested EN US wording for Firmware Update MD5 warning

### ISSUE THREAD

**Issue by dtech0501** [Jackysi/advancedtomato#277]
The current (1.28.0000 MIPSR2-3.4-138 K26 USB AIO) EN US wording on the Firmware Upgrade page (https://myrouter.local/#admin-upgrade.asp) could be improved to read better. Suggestion:

Attention!
Sometimes an image file can become corrupted while downloading to your computer. To avoid problems, please verify the MD5 checksum (link here) of the AdvancedTomato image file before attempting to flash your router.

![screenshot](https://cloud.githubusercontent.com/assets/19142075/21289380/3c770cba-c46a-11e6-8b17-dc22579054f2.png)

**Comment by Jackysi** [comment]
Thanks. That's actually much better, shorter and more on the point
