### ISSUE TITLE
Wireless Temperature Display

### ISSUE THREAD

**Issue by VREMSoftwareDevelopment** [Jackysi/advancedtomato#279]
Hi Jacky,

AdvancedTomato status overview page has CPU and Wireless temperature available for the Asus  RT-AC68.
Asus RT-AC66 and RT-N66 hardware has wireless temperature censors (does not have CPU temperature censor).
Is it possible to add wireless temperature display to the status overview page for the Asus RT-AC66 and RT-N66 routers?

Thanks,

VREM

**Comment by Jackysi** [comment]
The features are shared across all RT-N routers. So if others don't support (and they don't) it wouldn't work or even cause problems/issues. So no I won't implement such feature and honestly I follow strictly Shibby's implementations to avoid confusion and loss of features/differences. My project is GUI "mod" more than firmware for it self.
