### ISSUE TITLE
OpenVPN not working

### ISSUE THREAD

**Issue by maicardi** [Jackysi/advancedtomato#28]
I own an Asus RT-N16 router with AdvancedTomato 1.28.0000 MIPSR2-2.4-123 K26 USB AIO.

I try to enable OpenVPN but it does not start.

Using SSH I discovered that it seems that the TUN/TAP devices are missing:

Sat Dec 20 17:49:31 2014 ROUTE default_gateway=192.168.101.1
Sat Dec 20 17:49:31 2014 Note: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Sat Dec 20 17:49:31 2014 Note: Attempting fallback to kernel 2.2 TUN/TAP interface
Sat Dec 20 17:49:31 2014 Cannot allocate TUN/TAP dev dynamically
Sat Dec 20 17:49:31 2014 Exiting

Is there a fix?

Thanks.

**Comment by Jackysi** [comment]
Hmm, I think you should report this to Shibby. I don't think I have the knowledge to fix this sort of issue. See here: http://tomato.groov.pl/?page_id=334

**Comment by maicardi** [comment]
Done: http://tomato.groov.pl/?page_id=334&bugerator_nav=display&bug_project=1&issue=1674

Thanks for your reply.

Marco

**Comment by Jackysi** [comment]
No problem, I hope Shibby is still following that bug tracker. Otherwise I will send him pm on Linksysinfo forums.

**Comment by maicardi** [comment]
> No problem, I hope Shibby is still following that bug tracker.
> Otherwise I will send him pm on Linksysinfo forums.

No answer in the last 2 weeks. Will you please PM him?

Thanks.

**Comment by Jackysi** [comment]
Try to contact him via http://openlinksysinfo.org/ web site. Most developers are only active there.
Also please this issue is not in my knowledge to fix, so let it closed.
P.S.: If you notice any GUI errors or issues, this is where to report them! :)
