### ISSUE TITLE
Offer a  3rd static DNS entry field?

### ISSUE THREAD

**Issue by MikeM16** [Jackysi/advancedtomato#280]
Hi, 
looking at Shibby's screenshots it seems http://tomato.groov.pl/wp-content/gallery/screenshots/network.png shows there are three possible static DNS server entries.

However AdvancedTomato only offers a maximum of _two_ static DNS entries to configure.
Would it be possible to have a third field added to the GUI in future releases?

A Happy New Year to all!
Note: using tomato-Netgear-3500Lv2-K26USB-1.28.AT-RT-N5x--3.4-138-AIO

**Comment by Jackysi** [comment]
That was removed by Shibby once he added multi-wan features (the screen shot is outdated). So no.
