### ISSUE TITLE
https://advancedtomato.com/ is down

### ISSUE THREAD

**Issue by webmaster33** [Jackysi/advancedtomato#281]
It seems, https://advancedtomato.com/ is down.

I get Error 502 (Bad gateway) Ray ID: 31b0542b8cc90f6f • 2017-01-02 18:38:40 UTC

Not sure, if this is the correct place to report it.

**Comment by Jackysi** [comment]
Horrible way to report web site down. You should mail me instead because this has literally nothing to do with GUI which is why this issues tracker exists.
