### ISSUE TITLE
Tools-Wot: selected device is not highlighted

### ISSUE THREAD

**Issue by vrapp** [Jackysi/advancedtomato#282]
On the page #tools-wol.asp , the lines with devices get highlighted only when the mouse if hovering; but if I select one device I'm going to wake up, as soon as I move the mouse to the button "Wake Up", no device is highlighted.

The expectation is that when I'm pressing the button, I should clearly see which device I'm about to wake up, i.e. the line with selected device should look different from others.

Also, perhaps, until any device is selected, the button might be disabled.

**Comment by Jackysi** [comment]
Am the button is there for "MAC Address List" and not for the table lol. When you click device name it will wake up that device. Hovering device name says "Click to wake up"
