### ISSUE TITLE
hundreds of vlan2 entries on the "Devices list" page

### ISSUE THREAD

**Issue by pboschi** [Jackysi/advancedtomato#283]
On the "Devices list" page i get a list which includes devices on br0 and ethX, which is correct, and a list of hundreds of IPs to which i'm connected to (in the vlan2 interface). Also see:
http://superuser.com/questions/747913/are-public-ips-in-my-tomato-router-device-list-something-to-worry-about

I know that maybe this is a tomato issue/feature, but I think that vlan2 entries should be filtered out from the list on the "Devices list" page, as they are actually not "devices".

**Comment by Jackysi** [comment]
Nothing to do with GUI, this data is collected within backend. Contact Shibby (check his page for repos, issues tracker, etc...)
