### ISSUE TITLE
Initial files install for NETGEAR WNDR3700v3

### ISSUE THREAD

**Issue by MrWu-at-msv** [Jackysi/advancedtomato#285]
Hello,
i try to install Advanced Tomato Version 3.4-138 on NETGEAR WNDR3700v3 over OFW but the router is half bricked  (i can recover over serial tftpd) after uploading, router hang on booting.
Maybe need some initial file install before final update, but i can't find any (also not @ shibby).
Any advise??
Thanks

**Comment by ThatMarko** [comment]
+1 It bricked my WNDR3700v3. Used the latest version. Flashed correctly! Successfully unbricked router using TFTP after enabling it via the serial port.
