### ISSUE TITLE
Add ability to change default user ID for samba NAS

### ISSUE THREAD

**Issue by s10** [Jackysi/advancedtomato#287]
It would be nice and very useful to have option to change default NAS Samba user ID from 100 to 1000. 1000 is a default user id in Ubuntu/Debian. All files on the external HDD with ext3/ext4 are created with uid 1000, and currently, with 100 uid it is not possible to access those files.

It looks like today this value is inside the code: https://github.com/Jackysi/advancedtomato/blob/advancedtomato-ac/release/src/router/rc/telssh.c#L60

**Comment by Jackysi** [comment]
Its a firmware issue, but i'll look into it.

**Comment by s10** [comment]
Nothing will be done.
