### ISSUE TITLE
Help file?

### ISSUE THREAD

**Issue by jpsoutlook** [Jackysi/advancedtomato#289]
Hi I am running Tomato Firmware 1.28.0000 MIPSR2-3.0-132 K26 USB AIO on E4200 v1 hardwired bridged to a second E4200 v1.  I think the reason in on the firmware is for speed reasons with modprobe bcm_nat hack.  My question is....is there a help file in the portal?  I can't seem to find one anywhere and figured I was not looking correctly.  I am looking to enable QoS and wanted more clarification on each setting or is there a guide?

**Comment by Jackysi** [comment]
This is open source firmware that keeps changing. There is no help or documentation available.
