### ISSUE TITLE
router slows to a halt when downloading online themes fails

### ISSUE THREAD

**Issue by aditaga** [Jackysi/advancedtomato#29]
Today my router became nearly unresponsive. I still managed to log in, and found about 1000 /usr/sbin/ttb processes running. There were just as many log messages like this:

Dec 20 19:57:32 router user.notice root: ATTD: Cannot download Online themes. Will try again soon...

A very similar issue was reported before:

http://tomato.groov.pl/?page_id=334&bugerator_nav=display&issue=128

The solution proposed there should work, but seems like it was never implemented.

For the time being, I have worked around the problem by changing the 'Interface Theme' setting (under 'Admin Access') from 'On-line from ATTD' to 'Default'.

Such a bad time to submit a bug... Happy Christmas!

**Comment by Jackysi** [comment]
Thanks for report, I will fix it in next release :(. Marry Christmas to you too!
https://github.com/Jackysi/advancedtomato2/commit/023b8e6234bd83cc2bcb0964c87ad15137145b1c
