### ISSUE TITLE
Multiple wan connections doesn't work

### ISSUE THREAD

**Issue by dddango** [Jackysi/advancedtomato#290]
Tomato Firmware 1.28.0000 MIPSR2-138 K26 USB AIO-64K

I have been testing tomato performance with 2 WAN connections. 
Both are 50Mbps if run alone with native asus wrt in N66U.

http://i.imgur.com/HkwvYew.png   <-- WAN2
http://i.imgur.com/e0mnEtG.png   <-- WAN1

Here I have few ubuntu downloads going When I start downloads in load balance with both WAN connections active. I only get around 20Mpbs connection. Then I unplug the other one, so that all the downloads go for WAN2. Surprisingly download speed from this singular WAN2 connection jumps up to 40Mbps. And when I connect back to both WAN then WAN2 speed drops back to 20Mbps. 

Torrent protocol is suppose to be able to use multiple WAN connections and I wanted to test how multiple WAN works. Why does my download speed drop to half with 2 connections?? Shouldn't I get 40Mbps+40Mbps = 80Mbps, 
and NOT 20Mbps + 20Mbps = 40Mpbs. 

And further testing by disabling either of WAN connections I end up with
40Mpbs + 0Mpbs = 40Mbps  in which case 2 WAN connections are as good as only one connection. Is this a bug or what is happening?

I highly doubt that the reason would be "nobody can send you files that fast", because I can get better speeds when tested with exactly the same downloads in 150Mbps network.

**Comment by Jackysi** [comment]
NOT GUI issue. Talk to Shibby.
