### ISSUE TITLE
GUI issue with configuring Ethernet Ports State from overview

### ISSUE THREAD

**Issue by o355** [Jackysi/advancedtomato#292]
Hi, I'm pretty sure I found a bug with the GUI on the overview screen.

When I go down to the Ethernet Ports State on the overview, when I hover over the settings button, and let the "Configure Settings" thing show, when I click the settings gear, the "Configure Settings" popup doesn't go away, and this is consistent throughout the UI. If I do a full refresh, it'll go away.

I'm using an Asus RT-AC68R with 3.4-138 AIO-64K, and it shows up every time.

**Comment by Jackysi** [comment]
Yep its a bug. Thanks for reporting.
