### ISSUE TITLE
Static DNS missing.

### ISSUE THREAD

**Issue by teerekt** [Jackysi/advancedtomato#294]
just switched my router from a Asus RT-AC3200 to a Netgear Nighthawk 6700 (which I upgraded to a 7000!) and flashed advanced tomato. I've been using pi-hole on my pi zero the past few weeks and everything worked like a charm. On my Asus router I set my Lan DNS to my pi hole IP, turned off DHCP and let my Pi handle everything. On the latest version of advanced tomato I only have the option to change my Wan DNS. There is no option to change my Lan DNS. Is something wrong? I log into the router admin page, go to Basic Settings > Network but it is not there. Here is a screenshot of what I see, I've used Chrome and Edge and Internet Explorer.

Pic of what I see -

http://imgur.com/a/VkFXf

I also had this problem on my Asus - AC68U.

Edit - Using the following - Tomato Firmware 1.28.0000 -3.4-138 K26ARM USB AIO-64K.

Edit 2 - Found the issue. It's the version that I was using. The newest versions have the bug where it does not show up. If I go back a few revisions (3.0-132) allows me to change the LAN DNS. Anything newer and the options goes away. It has to be a bug.

**Comment by Jackysi** [comment]
Shibby moved static DNS to WAN settings. I attached screen shot.
![screencapture-192-168-1-1-444-1486900629668](https://cloud.githubusercontent.com/assets/2860965/22861927/7e79c27e-f124-11e6-8077-1a0dece52ca2.png)
