### ISSUE TITLE
Support Cloudflare in Dynamic DNS

### ISSUE THREAD

**Issue by overcookedTOFU** [Jackysi/advancedtomato#295]
Cloudflare has updated their api that allows one to change your dns configuration.  Tomato should support it.

I am not certain how Tomato currently does dynamic dns updates, but Cloudflare is supported in the newest version of ddclient (3.8.3).

Resources: 
https://support.cloudflare.com/hc/en-us/articles/200168816-Does-Cloudflare-work-with-Dynamic-DNS-Can-I-update-my-DNS-records-remotely-

https://www.cloudflare.com/technical-resources/#ddclient

**Comment by Jackysi** [comment]
I don't do firmware stuff. Talk to Shibby about that ^^

**Comment by overcookedTOFU** [comment]
Will do.  I added a Feature Request here: http://tomato.groov.pl/?page_id=334&bugerator_nav=list&bug_project=1

Is that the right bug tracker?

Thanks!

**Comment by Jackysi** [comment]
Bitbucket is better, its linked on my AdvancedTomato contact page

**Comment by overcookedTOFU** [comment]
Thanks!  For future reference, here is the bug at Bitbucket: https://bitbucket.org/pl_shibby/tomato-arm/issues/133/support-cloudflare-in-dynamic-dns
