### ISSUE TITLE
VPN's DHCP

### ISSUE THREAD

**Issue by john3v** [Jackysi/advancedtomato#299]
I have a issue with VPN PPTP DHCP.
![pptp_dhcp](https://cloud.githubusercontent.com/assets/25791274/22979618/b30039b0-f39f-11e6-89b1-767f953e5653.png)
It only allows six IP addresses.

How can override rule for only 6 IP's?

For example: 192.168.88.100-115

RT-AC66 Advanced Tomato, Version: 1.28.0000 MIPSR2-1.24.17 K26AC USB AIO-64K

**Comment by Jackysi** [comment]
You are running very outdated firmware man...

**Comment by john3v** [comment]
Updated router to last stable version "Tomato Firmware 1.28.0000 MIPSR2-3.4-138 K26AC USB AIO-64K" - the same issue. I can not use more than 6 ip addresses range.
And cannot add more than 6 users via GUI (ssh is different story)
