### ISSUE TITLE
dnsmasq crashing continuously with IPv6 enabled

### ISSUE THREAD

**Issue by Xykon** [Jackysi/advancedtomato#303]
Hello,

I'm in the UK using BT Infinity 2 with a Draytek Vigor 130 using default settings and an Asus RT-AC-66U with v3.4-138 AIO-64k.

I tried resetting my router to default settings and after configuring IPv4 and Wifi everything works fine. As soon as I enable IPv6 as recommended by BT using DHCPv6 with Prefix Delegation and a prefix of 56 and leaving everything else blank except to accept RA from WAN (which should be the default) my Windows 10 client PC gets a 20/20 on ipv6-test.com but I have difficulty reaching the router web interface on 192.168.1.1 usually with a connection lost message.

Upon checking the logs I can see that dnsmasq crashes approx. twice every second, which causes the webinterface to reload. This is what I can see in the logs:

Mar 13 22:46:18 router daemon.info dnsmasq[16789]: started, version 2.76 cachesize 4096
Mar 13 22:46:18 router daemon.info dnsmasq[16789]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset Tomato-helper auth DNSSEC loop-detect no-inotify
Mar 13 22:46:18 router daemon.info dnsmasq[16789]: asynchronous logging enabled, queue limit is 5 messages
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: DHCP, IP range 192.168.1.2 -- 192.168.1.51, lease time 1d
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: DHCPv6, IP range ::1 -- ::255.255.255.255, lease time 12h, template for br*
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: DHCPv4-derived IPv6 names on br*
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: router advertisement on br*
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: DHCPv6, IP range 2a00:23c0:73ad:8200::1 -- 2a00:23c0:73ad:8200::ffff:ffff, lease time 12h, constructed for br0
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: DHCPv4-derived IPv6 names on 2a00:23c0:73ad:8200::, constructed for br0
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: router advertisement on 2a00:23c0:73ad:8200::, constructed for br0
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: RTR-ADVERT(br0) 2a00:23c0:73ad:8200::
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: IPv6 router advertisement enabled
Mar 13 22:46:18 router daemon.info dnsmasq[16789]: reading /etc/resolv.dnsmasq
Mar 13 22:46:18 router daemon.info dnsmasq[16789]: using nameserver 208.67.222.222#53
Mar 13 22:46:18 router daemon.info dnsmasq[16789]: using nameserver 208.67.220.220#53
Mar 13 22:46:18 router daemon.info dnsmasq[16789]: read /etc/hosts - 3 addresses
Mar 13 22:46:18 router daemon.info dnsmasq[16789]: read /etc/dnsmasq/hosts/hosts - 5 addresses
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: read /etc/dnsmasq/dhcp/dhcp-hosts
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16789]: RTR-ADVERT(br0) 2a00:23c0:73ad:8200::
Mar 13 22:46:18 router daemon.info httpd[16792]: Tomato interface started successfully
Mar 13 22:46:18 router user.debug init[1]: 255: pptp peerdns disabled
Mar 13 22:46:18 router daemon.info dnsmasq[16789]: exiting on receipt of SIGTERM
Mar 13 22:46:18 router daemon.info dnsmasq[16796]: started, version 2.76 cachesize 4096
Mar 13 22:46:18 router daemon.info dnsmasq[16796]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset Tomato-helper auth DNSSEC loop-detect no-inotify
Mar 13 22:46:18 router daemon.info dnsmasq[16796]: asynchronous logging enabled, queue limit is 5 messages
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: DHCP, IP range 192.168.1.2 -- 192.168.1.51, lease time 1d
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: DHCPv6, IP range ::1 -- ::255.255.255.255, lease time 12h, template for br*
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: DHCPv4-derived IPv6 names on br*
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: router advertisement on br*
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: DHCPv6, IP range 2a00:23c0:73ad:8200::1 -- 2a00:23c0:73ad:8200::ffff:ffff, lease time 12h, constructed for br0
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: DHCPv4-derived IPv6 names on 2a00:23c0:73ad:8200::, constructed for br0
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: router advertisement on 2a00:23c0:73ad:8200::, constructed for br0
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: RTR-ADVERT(br0) 2a00:23c0:73ad:8200::
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: IPv6 router advertisement enabled
Mar 13 22:46:18 router daemon.info dnsmasq[16796]: reading /etc/resolv.dnsmasq
Mar 13 22:46:18 router daemon.info dnsmasq[16796]: using nameserver 208.67.222.222#53
Mar 13 22:46:18 router daemon.info dnsmasq[16796]: using nameserver 208.67.220.220#53
Mar 13 22:46:18 router daemon.info dnsmasq[16796]: read /etc/hosts - 3 addresses
Mar 13 22:46:18 router daemon.info dnsmasq[16796]: read /etc/dnsmasq/hosts/hosts - 5 addresses
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: read /etc/dnsmasq/dhcp/dhcp-hosts
Mar 13 22:46:18 router daemon.info dnsmasq-dhcp[16796]: RTR-ADVERT(br0) 2a00:23c0:73ad:8200::
Mar 13 22:46:19 router daemon.info httpd[16799]: Tomato interface started successfully
Mar 13 22:46:19 router user.debug init[1]: 255: pptp peerdns disabled
Mar 13 22:46:19 router daemon.info dnsmasq[16796]: exiting on receipt of SIGTERM

I've had a look at the dnsmasq man page but couldn't really find anything I could add to the configuration that would give me more detailed log output that could help me find out why dnsmasq is crashing. I'm hoping someone here on github can help.

Thanks a lot for making this great firmware!

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
