### ISSUE TITLE
R7000 bandwidth and ip traffic log 

### ISSUE THREAD

**Issue by Norren** [Jackysi/advancedtomato#305]
Some of the time when I go into Bandwidth or the IP traffic log and click 24 hour view, I get a connection lost error and the attached series of javascript errors.  It happens most often on the device specific IP traffic side.  If I can get it to load, dropping it from 24 to either 2 or 4 hour views seems to eliminate the chance of the error occurring.  From the Javascript console message, I'm guessing that the GUI gives up before the router is finished parsing and transmitting the log.

I'm running a Netgear R7000 with version 3.4-138, and have around 30 devices on network.

[advancedtomato bandwidth error.txt](https://github.com/Jackysi/advancedtomato/files/862763/advancedtomato.bandwidth.error.txt)

**Comment by Jackysi** [comment]
It possible that the timeout is too short. How long does it take approximately to load statistics? You should see ajax request via console (network tab) (F12 chrome). 

P.S.: I set limit based on my data which loads in 2sec (lots of devices etc).
