### ISSUE TITLE
QoS: B/W Limiter limits SMB bandwidth

### ISSUE THREAD

**Issue by Kazula** [Jackysi/advancedtomato#310]
The Bandwidth Limiter works fine with data from wan but also limits the bandwidth from files via SMB from my connected HDD drive which is plugged in to the router.

I tried to turn off QoS and also tried to play with some values in the "Max Bandwidth Limit" but all of them didn't increase the bandwidth speed via SMB.

Speed with B/W Limiter actived: ~6-8 MB/s
Speed without B/W Limiter actived: ~25-27 MB/s

I also recognized that the cpu will not go to 100% when I transfer data via SMB with B/W Limiter enabled.

![unbenannt](https://cloud.githubusercontent.com/assets/27579994/25066616/9178ea0c-222b-11e7-9edc-84fd7cf06029.JPG)
![unbenannt2](https://cloud.githubusercontent.com/assets/27579994/25066617/917eb748-222b-11e7-80f7-c9a3a24eb114.JPG)

**Comment by Jackysi** [comment]
QOS stuff is unrelated to the AdvancedTomato GUI Modification. This whole project is only GUI modification meaning I don't change any internal software/code related to the routing it self. This project is goaling to stay on same state as Shibby's Tomato and for that reason this report is completely useless here. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open
