### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by HFsi** [Jackysi/advancedtomato#314]
Hi!
It´s been a while since the last update, are you still working on the project?
Please do! It´s by far the best WRT available out there!
Thanks

**Comment by Jackysi** [comment]
lol its Tomato not WRT :D that's not the same! Well I didn't get almost any reports about GUI so I'm really waiting for Shibby's 139/140 release to work on. The project is waiting... I'm also super busy so its hard to learn stuff at the moment.
