### ISSUE TITLE
Add GUI builds for shibby K26ARM7 

### ISSUE THREAD

**Issue by bear454** [Jackysi/advancedtomato#315]
[Shibby](http://tomato.groov.pl/?page_id=164) builds for the following [K27ARM7](http://tomato.groov.pl/download/K26ARM7/) routers:

* Netgear R8000
* Asus RT-AC3200

Please, _please_, *please* add builds for these routers.

**Comment by Jackysi** [comment]
This is issues tracker and you are sending a request. I don't own ARM7 for that reason R8000 and AC3200 will not be released anytime soon. There are some GUI modifications required and without a router that's impossible to make work.
