### ISSUE TITLE
Netgear R7000 - Ethernet Ports State 100Mb only

### ISSUE THREAD

**Issue by wshosting** [Jackysi/advancedtomato#319]
Hello,

after Upgrading my Netgear R7000 all my LAN Ethernet Ports now only support 10/100.
The WAN Port is showing as 1000M Full.

With the original Firmware my R7000 supported 1000 speed as well.

Any help is appreciated.

Thank you,

Daniel

**Comment by Jackysi** [comment]
Based on what? where? if its firmware issue report to shibby.
