### ISSUE TITLE
"Run APCUPSD Deamon" checkbox not working

### ISSUE THREAD

**Issue by maurice-w** [Jackysi/advancedtomato#321]
In _USB & NAS_ / _USB Support_, checking / unchecking _Run APCUPSD Deamon_ and saving does not actually save the setting. Works in Shibby's v140 firmware, so seems to be a GUI issue.

Router: Linksys E4200
Interface and firmware version: 3.4-140

(Oh, and by the way, it's spelled "Daemon").

**Comment by Jackysi** [comment]
Could be RT-N series only, on my ARM R7000 it works fine. I will give it a look thx!
