### ISSUE TITLE
Displaying CPU usage

### ISSUE THREAD

**Issue by Ivantosov** [Jackysi/advancedtomato#322]
Toastman’s Tomato displays CPU usage: 
![tomato-on-asus-rt-n16](https://cloud.githubusercontent.com/assets/28530674/26012395/0b98096c-375d-11e7-9476-248319895e65.png)
And on main page of Advanced Tomato site it displays: https://advancedtomato.com/ ( https://advancedtomato.com/images/advancedtomato-gui.png )
But in Advanced Tomato GUI (at least on RT-N16 (1.28.0000 MIPSR2-3.4-140 K26 USB AIO) CPU usage is missing:
![2](https://cloud.githubusercontent.com/assets/28530674/26012563/8fe1c000-375d-11e7-81ed-3d1c005a70eb.png)
CPU usage is very useful information for multitask router, can you add it?
Thanks

**Comment by Jackysi** [comment]
No, I follow Shibby's builds which have no CPU usage on GUI for RT-N/RT-AC devices Toastman's Tomato has really nothing to do with this project.
