### ISSUE TITLE
Lots of timeout errors with ASUS RT-N16 and 1.28.0000 MIPSR2-3.4-140 K26 USB AIO

### ISSUE THREAD

**Issue by dtech0501** [Jackysi/advancedtomato#328]
I have two RT-N16s that almost always show the attached error when switching from page to page. This did not happen with version 3.4-138. It also does not happen on my Netgear 6300v2 with 3.4-140. Firefox 53 on Linux Mint 18.1

![screenshot from 2017-05-29 20-53-38](https://cloud.githubusercontent.com/assets/19142075/26564635/6ec08698-44b1-11e7-8949-737877e01c92.png)

**Comment by dtech0501** [comment]
I'm getting these timeout errors (screenshot below) about every 30 seconds on the bandwidth page.

![screenshot from 2017-05-30 16-07-43](https://cloud.githubusercontent.com/assets/19142075/26602778/94a28e82-4552-11e7-964d-61f3a95c3586.png)

**Comment by Jackysi** [comment]
Firmware issue. I can't help with this, please pass it to another firmware developer like Shibby.
