### ISSUE TITLE
Port Forwarding > Basic - Weird Tab Order

### ISSUE THREAD

**Issue by windy-** [Jackysi/advancedtomato#33]
In the Port Forwarding > Basic page (#forward-basic.asp), if I type in a single port # (such as 100) in the Ext Ports field, the tab order works fine as it goes to Int Ports, Int Address, Description and finally Add+ button when I hit the tab key consecutively. However, as soon as I put in a range (such as 100-200) for the Ext Ports, the tab order becomes unpredictable. 

I have tested this on Asus RT-AC68U (2.5-124 K26ARM USB AIO-64K) and Asus-RT-N66U (2.5-124 K26AC USB AIO-64K).

**Comment by Jackysi** [comment]
I apologize for such long delay in my response. I was extreme busy as you may imagine. I will look into issue!

**Comment by Jackysi** [comment]
I have tested this 10x now on RT-N66U and AC32000. I can't reproduce the problem.
