### ISSUE TITLE
Cannot set vlans properly

### ISSUE THREAD

**Issue by DBLouis** [Jackysi/advancedtomato#332]
Netgear WNR3500Lv2
AdvancedTomato 3.4-140

Vlans settings are not saved correctly. I set it like this:
vid 0: ports 8, bridge br1, default
vid 1: ports 1 2 3 4 8(tagged), bridge br0
vid 15: bridge wan

And after reboot it is modified:
vid 0: ports 8, bridge br1, default
vid 1: ports 1 2 3 4, bridge br0
vid 2: ports 8
vid 15: bridge wan

(port 8 is wan, bridged to br0)

**Comment by DBLouis** [comment]
I tried other configurations, every times it add or remove a vid, change the default vlan, swap bridges ...

**Comment by wbinek** [comment]
I've also noticed the issue. I tested vlans with original tomato shibby 140 and it works fine there.

**Comment by DBLouis** [comment]
Someone has to do something about it, my router is basically unusable. I tried using the CLI, it is the same. It keeps adding another vlan and messing with the ports ...
(My first message is wrong, it appears that port 0 is wan and ports 4, 3, 2 and 1 are reversed. I don't know what is port 8)

**Comment by Jackysi** [comment]
Maybe this will fix the problem: https://github.com/Jackysi/advancedtomato-gui/commit/d77af3574dddc1a1e742f22e3ee0eb2fbb622b3a

**Comment by Jackysi** [comment]
Duplicate: https://github.com/Jackysi/advancedtomato/issues/338
