### ISSUE TITLE
"undefined" values on Status>Overview page>System after auto-refresh

### ISSUE THREAD

**Issue by GrumpyMeow** [Jackysi/advancedtomato#333]
Firmware: Tomato Firmware 1.28.0000 -3.4-140 K26ARM USB AIO-64K
Router: Netgear R7000

After the automatic refresh (3 seconds) the values get set to 'undefined' for labels of: Time, Uptime, ..., Swap Usage.

In the Console of Chrome (Windows) i get this error:
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at <anonymous>:311:34
    at by (jquery.min.js:2)
    at Function.globalEval (jquery.min.js:2)
    at text script (jquery.min.js:2)
    at aU (jquery.min.js:2)
    at H (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
    at XMLHttpRequest.send (<anonymous>:1:761)
    at Object.send (jquery.min.js:2)
    at Function.ajax (jquery.min.js:2)

the status-data.jsx returns:
//
nvram = {
	'router_name': 'Router',
	'wan_domain': 'Home',
	'wan_hostname': 'Router',
	'et0macaddr': 'xx:xx:xx:xx:xx:xx',
	'lan_proto': 'dhcp',
	'lan_ipaddr': '192.168.11.1',
	'dhcp_start': '100',
	'dhcp_num': '28',
	'dhcpd_startip': '192.168.11.100',
	'dhcpd_endip': '192.168.11.127',
	'lan_netmask': '255.255.255.0',
	'wl_security_mode': 'disabled',
	'wl0_security_mode': 'disabled',
	'wl1_security_mode': 'disabled',
	'wl_crypto': 'aes',
	'wl0_crypto': 'aes',
	'wl1_crypto': 'aes',
	'wl_mode': 'ap',
	'wl0_mode': 'ap',
	'wl1_mode': 'ap',
	'wl_wds_enable': '0',
	'wl0_wds_enable': '0',
	'wl1_wds_enable': '0',
	'wl_hwaddr': '',
	'wl0_hwaddr': 'xx:xx:xx:xx:xx:xx',
	'wl1_hwaddr': 'xx:xx:xx:xx:xx:xx',
	'wl_net_mode': 'mixed',
	'wl0_net_mode': 'mixed',
	'wl1_net_mode': 'mixed',
	'wl_radio': '1',
	'wl0_radio': '0',
	'wl1_radio': '0',
	'wl_channel': '6',
	'wl0_channel': '6',
	'wl1_channel': '0',
	'lan_gateway': '0.0.0.0',
	'wl_ssid': 'Tomato24',
	'wl0_ssid': 'Tomato24',
	'wl1_ssid': 'Tomato50',
	'wl_closed': '0',
	'wl0_closed': '0',
	'wl1_closed': '0',
	't_model_name': 'Netgear R7000',
	't_features': '0x1C1',
	'dhcp1_start': '100',
	'dhcp1_num': '28',
	'dhcpd1_startip': '10.0.0.100',
	'dhcpd1_endip': '10.0.0.127',
	'dhcp2_start': '100',
	'dhcp2_num': '28',
	'dhcpd2_startip': '192.168.12.100',
	'dhcpd2_endip': '192.168.12.127',
	'dhcp3_start': '',
	'dhcp3_num': '',
	'dhcpd3_startip': '',
	'dhcpd3_endip': '',
	'lan1_proto': 'dhcp',
	'lan1_ipaddr': '10.0.0.254',
	'lan1_netmask': '255.255.255.0',
	'lan2_proto': 'dhcp',
	'lan2_ipaddr': '192.168.12.1',
	'lan2_netmask': '255.255.255.0',
	'lan3_proto': '',
	'lan3_ipaddr': '',
	'lan3_netmask': '',
	'lan_ifname': 'br0',
	'lan1_ifname': 'br1',
	'lan2_ifname': 'br2',
	'lan3_ifname': '',
	'lan_ifnames': 'vlan1',
	'lan1_ifnames': 'vlan3',
	'lan2_ifnames': 'vlan4',
	'lan3_ifnames': '',
	'wan_ifnames': 'vlan2',
	'tomatoanon_enable': '0',
	'tomatoanon_answer': '1',
	'lan_desc': '1',
	'wan_ppp_get_ip': '',
	'wan_pptp_dhcp': '0',
	'wan_pptp_server_ip': '',
	'wan_ipaddr_buf': '',
	'wan_gateway': '94.208.78.1',
	'wan_gateway_get': '0.0.0.0',
	'wan_get_domain': '',
	'wan_hwaddr': 'xx:xx:xx:xx:xx:xx',
	'wan_ipaddr': 'xxx.xxx.xxx.xxx',
	'wan_netmask': '255.255.254.0',
	'wan_proto': 'static',
	'wan_run_mtu': '1500',
	'wan_sta': '',
	'wan2_ppp_get_ip': '',
	'wan2_pptp_dhcp': '0',
	'wan2_pptp_server_ip': '',
	'wan2_ipaddr_buf': '',
	'wan2_gateway': '0.0.0.0',
	'wan2_gateway_get': '0.0.0.0',
	'wan2_get_domain': '',
	'wan2_hwaddr': '',
	'wan2_ipaddr': '0.0.0.0',
	'wan2_netmask': '0.0.0.0',
	'wan2_proto': 'dhcp',
	'wan2_run_mtu': '',
	'wan2_sta': '',
	'wan3_ppp_get_ip': '',
	'wan3_pptp_dhcp': '0',
	'wan3_pptp_server_ip': '',
	'wan3_ipaddr_buf': '',
	'wan3_gateway': '0.0.0.0',
	'wan3_gateway_get': '0.0.0.0',
	'wan3_get_domain': '',
	'wan3_hwaddr': '',
	'wan3_ipaddr': '0.0.0.0',
	'wan3_netmask': '0.0.0.0',
	'wan3_proto': 'dhcp',
	'wan3_run_mtu': '',
	'wan3_sta': '',
	'wan4_ppp_get_ip': '',
	'wan4_pptp_dhcp': '0',
	'wan4_pptp_server_ip': '',
	'wan4_ipaddr_buf': '',
	'wan4_gateway': '0.0.0.0',
	'wan4_gateway_get': '0.0.0.0',
	'wan4_get_domain': '',
	'wan4_hwaddr': '',
	'wan4_ipaddr': '0.0.0.0',
	'wan4_netmask': '0.0.0.0',
	'wan4_proto': 'dhcp',
	'wan4_run_mtu': '',
	'wan4_sta': '',
	'mwan_num': '1',
	'pptp_client_enable': '0',
	'pptp_client_ipaddr': '',
	'pptp_client_netmask': '',
	'pptp_client_gateway': '',
	'pptp_client_get_dns': '',
	'pptp_client_srvsub': '10.0.0.0',
	'pptp_client_srvsubmsk': '255.0.0.0',
	'wl_unit': '0',
	'http_id': 'TIDXXXXXxxxxxxxx',
	'web_mx': '',
	'web_pb': ''};

//
//
sysinfo = {
	uptime: 88177,
	uptime_s: '1 day, 00:29:37',
	loads: [192, 1568, 2976],
	totalram: 261767168,
	freeram: 219922432,
	shareram: 0,
	bufferram: 5787648,
	cached: 13778944,
	totalswap: 0,
	freeswap: 0,
	totalfreeram: 239489024,
	procs: 45,
	flashsize: 128,
	systemtype: 'ARMv7 Processor rev 0 (v7l)',
	cpumodel: '',
	bogomips: ' (dual',
	cpuclk: '1000 MHz (dual',
	cputemp: '68',
	wlsense: 'eth1: 2.4G - --&#176;C&nbsp;&nbsp;&nbsp;&nbsp;eth2: 5G - --&#176;C',
	jiffies: '7018 0 5048 17594960 162 0 28079 0 0 0'
};

//
wlstats = [ { radio: 0, client: 0, channel:  6, mhz: 2437, rate: 900, ctrlsb: 'upper', nbw: 40, rssi: 0, noise: -99, intf: -1 }
,{ radio: 0, client: 0, channel:  36, mhz: 5180, rate: 1200, ctrlsb: 'lower', nbw: 20, rssi: 0, noise: -99, intf: 0 }
];

stats = { };
do {
var a, b, i;
var xifs = ['wan', 'lan', 'lan1', 'lan2', 'lan3', 'wan2', 'wan3', 'wan4'];
stats.anon_enable = nvram.tomatoanon_enable;
stats.anon_answer = nvram.tomatoanon_answer;
stats.lan_desc = nvram.lan_desc;
if (typeof(last_wan_proto) == 'undefined') {
last_wan_proto = nvram.wan_proto;
}
else if (last_wan_proto != nvram.wan_proto) {
reloadPage();
}
stats.flashsize = sysinfo.flashsize+'MB';
stats.cpumhz = sysinfo.cpuclk+'-core)';
stats.cputemp = sysinfo.cputemp+'°';
stats.systemtype = sysinfo.systemtype;
stats.cpuload = ((sysinfo.loads[0] / 65536.0).toFixed(2) + '<small> / </small> ' +
(sysinfo.loads[1] / 65536.0).toFixed(2) + '<small> / </small>' +
(sysinfo.loads[2] / 65536.0).toFixed(2));
stats.freqcpu = nvram.clkfreq;
stats.uptime = sysinfo.uptime_s;
var total_jiffies = 0;
var jiffylist = sysinfo.jiffies.split(' ');
for (i=0; i < jiffylist.length; ++i) {
total_jiffies += parseInt(jiffylist[i]);
}
var diff_idle = jiffylist[3] - lastjiffiesidle;
var diff_total = total_jiffies - lastjiffiestotal;
lastjiffiesusage = (1000*(diff_total-diff_idle)/diff_total)/10;
lastjiffiestotal = total_jiffies;
lastjiffiesidle = jiffylist[3];
stats.cpupercent = lastjiffiesusage.toFixed(2) + '%';
stats.wlsense = sysinfo.wlsense;
a = sysinfo.totalram;
b = sysinfo.totalfreeram;
stats.memory = scaleSize(a - b) + ' <small>/</small> ' + scaleSize(a) + ' (' + ((a - b) / a * 100.0).toFixed(2) + '%)';
stats.memoryperc = ((a-b) / a * 100.0).toFixed(2) + '%';
if (sysinfo.totalswap > 0) {
a = sysinfo.totalswap;
b = sysinfo.freeswap;
stats.swap = scaleSize(a - b) + ' <small>/</small> ' + scaleSize(a) + ' (' + ((a - b) / a * 100.0).toFixed(2) + '%)';
stats.swapperc = ((a - b) / a * 100.0).toFixed(2) + '%';
} else {
stats.swap = '';
}
stats.time = 'Sun, 18 Jun 2017 08:48:30 +0200';
stats.wanup = [1,0,0,0];
stats.wanuptime = ['1 day, 00:29:26','-','-','-'];
stats.wanlease = ['','0 days, 00:00:00','0 days, 00:00:00','0 days, 00:00:00'];
stats.dns = [['8.8.8.8:53','8.8.4.4:53'],[],[],[]];
stats.wanip = [];
stats.wannetmask = [];
stats.wangateway = [];
for(var uidx = 1; uidx <= nvram.mwan_num; ++uidx) {
var u = (uidx>1) ? uidx : '';
stats.wanip[uidx-1] = nvram['wan'+u+'_ipaddr'];
stats.wannetmask[uidx-1] = nvram['wan'+u+'_netmask'];
stats.wangateway[uidx-1] = nvram['wan'+u+'_gateway_get'];
if (stats.wangateway[uidx-1] == '0.0.0.0' || stats.wangateway[uidx-1] == '')
stats.wangateway[uidx-1] = nvram['wan'+u+'_gateway'];
switch (nvram['wan'+u+'_proto']) {
case 'pptp':
case 'l2tp':
case 'pppoe':
if (stats.wanup[uidx-1]) {
stats.wanip[uidx-1] = nvram['wan'+u+'_ppp_get_ip'];
if (nvram['wan'+u+'_pptp_dhcp'] == '1') {
if (nvram['wan'+u+'_ipaddr'] != '' && nvram['wan'+u+'_ipaddr'] != '0.0.0.0' && nvram['wan'+u+'_ipaddr'] != stats.wanip[uidx-1])
stats.wanip[uidx-1] += '&nbsp;&nbsp;<small>(DHCP: ' + nvram['wan'+u+'_ipaddr'] + ')</small>';
if (nvram['wan'+u+'_gateway'] != '' && nvram['wan'+u+'_gateway']  != '0.0.0.0' && nvram['wan'+u+'_gateway']  != stats.wangateway[uidx-1])
stats.wangateway[uidx-1] += '&nbsp;&nbsp;<small>(DHCP: ' + nvram['wan'+u+'_gateway']  + ')</small>';
}
if (stats.wannetmask[uidx-1] == '0.0.0.0')
stats.wannetmask[uidx-1] = '255.255.255.255';
} else {
if (nvram['wan'+u+'_proto'] == 'pptp')
stats.wangateway[uidx-1] = nvram['wan'+u+'_pptp_server_ip'];
}
break;
default:
if (!stats.wanup[uidx-1]) {
stats.wanip[uidx-1] = '0.0.0.0';
stats.wannetmask[uidx-1] = '0.0.0.0';
stats.wangateway[uidx-1] = '0.0.0.0';
}
}
}
stats.ip6_wan = ((typeof(sysinfo.ip6_wan) != 'undefined') ? sysinfo.ip6_wan : '') + '';
stats.ip6_lan = ((typeof(sysinfo.ip6_lan) != 'undefined') ? sysinfo.ip6_lan : '') + '';
stats.ip6_lan_ll = ((typeof(sysinfo.ip6_lan_ll) != 'undefined') ? sysinfo.ip6_lan_ll : '') + '';
stats.wanstatus = ['Connected','Disconnected','Disconnected','Disconnected'];
for(var uidx = 1; uidx <= nvram.mwan_num; ++uidx) {
if (stats.wanstatus[uidx-1] != 'Connected') stats.wanstatus[uidx-1] = '<b>' + stats.wanstatus[uidx-1] + '</b>';
}
stats.channel = [];
stats.interference = [];
stats.qual = [];
for (var uidx = 0; uidx < wl_ifaces.length; ++uidx) {
u = wl_unit(uidx);
a = i = wlstats[uidx].channel * 1;
if (i < 0) i = -i;
stats.channel.push('<a href="#tools-survey.asp">' + ((i) ? i + '' : 'Auto') +
((wlstats[uidx].mhz) ? ' - ' + (wlstats[uidx].mhz / 1000.0).toFixed(3) + ' <small>GHz</small>' : '') + '</a>' +
((a < 0) ? ' <small>(scanning...)</small>' : ''));
stats.interference.push((wlstats[uidx].intf >= 0) ? ((wlstats[uidx].intf) ? 'Severe' : 'Acceptable') : '');
a = wlstats[uidx].nbw * 1;
wlstats[uidx].nbw = (a > 0) ? (a + ' <small>MHz</small>') : 'Auto';
if (wlstats[uidx].radio) {
a = wlstats[uidx].rate * 1;
if (a > 0)
wlstats[uidx].rate = Math.floor(a / 2) + ((a & 1) ? '.5' : '') + ' <small>Mbps</small>';
else
wlstats[uidx].rate = '-';
if (wlstats[uidx].client) {
if (wlstats[uidx].rssi == 0) a = 0;
else a = MAX(wlstats[uidx].rssi - wlstats[uidx].noise, 0);
stats.qual.push(a + ' <i class="icon-wifi-' + MIN(MAX(Math.floor(a / 10), 1), 3) + '"></i>');
}
else {
stats.qual.push('');
}
wlstats[uidx].noise += ' <small>dBm</small>';
wlstats[uidx].rssi += ' <small>dBm</small>';
}
else {
wlstats[uidx].rate = '';
wlstats[uidx].noise = '';
wlstats[uidx].rssi = '';
stats.qual.push('');
}
if (wl_ifaces[uidx][6] != 1) {
wlstats[uidx].ifstatus = '<b>Down</b>';
} else {
wlstats[uidx].ifstatus = 'Up';
for (i = 0; i < xifs.length ; ++i) {
if ((nvram[xifs[i] + '_ifnames']).indexOf(wl_ifaces[uidx][0]) >= 0) {
wlstats[uidx].ifstatus = wlstats[uidx].ifstatus + ' (' + xifs[i].toUpperCase() + ')';
break;
}
}
}
}
} while (0);

Keep up the good work! Thanks!

**Comment by Jackysi** [comment]
Clear NVRAM and reboot router. If you are using IPv6 that could be also causing weird issues. 
I can't replicate the problem on my R7000.
