### ISSUE TITLE
Option to ignore "Unclassified" traffic in QOS Charts

### ISSUE THREAD

**Issue by GreenBattery** [Jackysi/advancedtomato#341]
It appears that at present all LAN to LAN traffic is marked as "unclassified" for the purpose of QoS. 

This is sensible, as on the LAN there is no pressing need to apply QoS to traffic. 

However, this means that in the QoS charts, the bulk of traffic is always Unclassified as there is usually a lot more LAN traffic going on than WAN traffic. 

The charts will be more useful if by default, such Unclassified traffic is not included (with the option to include it if the user requires).

**Comment by Jackysi** [comment]
I am sorry, but I don't extend functionality of the interface/router. That's because I want to stay close to Shibby's releases. You can ask him to implement this, it shouldn't be hard.
