### ISSUE TITLE
Cannot Port Forward to Port 80

### ISSUE THREAD

**Issue by AdziePahlevi** [Jackysi/advancedtomato#342]
Hi Jack, 

thanks a lot for your excellent work on the firmware. I was recently update the firmware to the latest one 3.4-140 everything are working except port forwarding to Internal IP Port 80

![image](https://user-images.githubusercontent.com/19539988/29409676-8cf52f60-8377-11e7-9853-87e95d9a3336.png)

all above port forwarding are working fine and accessible from internet using DDNS except the one that fwd-ed to Port 80. I was enabling remote access to port 80 and 8080 but still not working. 

I did not touch firewall settings and leave it as default. Any advise what else to checked on my router? 

Below is the router log after I enabling the port forwarding

Aug 17 18:11:32 AdziE-RTN16 daemon.info transmission-daemon[4563]: Port Forwarding Starting (port-forwarding.c:92)

**Comment by Jackysi** [comment]
I'm sorry but that has nothing to do with this modification. This is done in the firmware itself and so I don't have control over it other than over GUI which stores the values properly.
