### ISSUE TITLE
Add GCM ciphers in OpenVPN Encryption options

### ISSUE THREAD

**Issue by dhiru1602** [Jackysi/advancedtomato#344]
OpenVPN 2.4 supports GCM ciphers (AES-256-GCM and AES-128-GCM), but they are not listed in the encryption dropdown box in AT 3.4-140.

I am able to use Inspect Element in Chrome or Firefox to add the cipher to the dropdown option list and I am able to use the cipher regardless. It's however good to have these ciphers added to the list in the next build.

**Comment by Jackysi** [comment]
https://github.com/Jackysi/advancedtomato/issues/343#issuecomment-323581260
See last response. Unless Shibby has this option it won't be added.
