### ISSUE TITLE
No Bandwidth Reporting for Asus RT-AC68U

### ISSUE THREAD

**Issue by windy-** [Jackysi/advancedtomato#35]
I am not seeing any kind of bandwidth being reported (all 0.00s) for Asus RT-AC68U using firmware version 2.5-124 K26ARM USB AIO-64K.

**Comment by Jackysi** [comment]
This happens on Bandwidth monitoring pages or IP Traffic?
Bandwidth monitoring pages are known to not work properly, this is issue related to ALL ARM builds which are very early stage of development (buggy, alpha builds)
