### ISSUE TITLE
Status Overview Ethernet Ports State

### ISSUE THREAD

**Issue by trismos** [Jackysi/advancedtomato#352]
On an Asus RT-N53  #A1
tomato-K26USB-1.28.AT-RT-N5x-MIPSR2-3.4-140-RT-N53

The Status Overview Ethernet Ports State shows that I am plugged into LAN4, when in fact I am in LAN1, and visa versa. When plugged into LAN3, it shows I am in LAN2, and visa versa.

**Comment by Jackysi** [comment]
Not a GUI issue. Report to Shibby.

**Comment by trismos** [comment]
sorry m8
