### ISSUE TITLE
Adblock issues

### ISSUE THREAD

**Issue by ManlyElectronics** [Jackysi/advancedtomato#353]
1. in Adblock Custom Block list does not accept more than some number of hosts, a hundred or so.  If you paste more hosts and hit Save – the router page brakes.
2. Adblock from lists loaded via URLs is intermittent, some ads showing some not. 
3. When Adblock is on other sites not specified in lists can be blocked such as Google and Github.

So overall adblock does not work and brakes normal router operation.

**Comment by Jackysi** [comment]
This is all related to firmware only. Please contact Shibby about it. See his Bitbucket issues tracker (Google Search)
