### ISSUE TITLE
Router won’t flash to Advanced Tomato

### ISSUE THREAD

**Issue by rkmckiny1** [Jackysi/advancedtomato#354]
I have a Netgear R7000 running GUI V1.0.9.10_2.1.38.1 with firmware V1.0.9.10_2.1.21 that I have flashed first with your ARM-3.4-140-initial-644K-chk then with the full ARM-3.4-140-AIO-64K.trx using the instructions from the advanced Tomato website. Rebooted several times when finished but no internet connection. I was able to ping it. After the router was recovered I reflashed back to original firmware. I started the process all over again following directions step by step. Versions in the video were: Netgear V1.0.3.24_1.1.20 and Tomato was R7000-RT-118. I tried to find the older firmware for my router but all the links I found were no longer supported. Is there a work around for this? I am not a programmer but follow directions extremely well.

**Comment by Jackysi** [comment]
I don't know. Use Linksysinfo forums. This is GUI modification and it is based on original tomato by Shibby. I have R7000 and it works fine. Its probable you have different hardware.
