### ISSUE TITLE
Recent DNSMASQ Vulnerabilities

### ISSUE THREAD

**Issue by Qiyamah** [Jackysi/advancedtomato#355]
Hi,
Do we need to patch those vulnerabilities?

https://security.googleblog.com/2017/10/behind-masq-yet-more-dns-and-dhcp.html

**Comment by Jackysi** [comment]
I have no idea. I'm GUI (Front-end) Developer. I have no idea about coding behind DNS MASQ. You should ask that on Linksysinfo forums =).
