### ISSUE TITLE
Unable to communicate between VLANs when VPN is on

### ISSUE THREAD

**Issue by manthis** [Jackysi/advancedtomato#357]
Hi,

I'm having an issue with my VLANs. When VPN is on, I can't communicate between them but as soon as I disconnect from VPN, everything is back to normal. I posted this issue on Shibby's forum but it seems they cannot reproduce the problem. Could you help?

Thanks

**Comment by sitekeeper** [comment]
That would be an issue you need to take up with Shibby "http://tomato.groov.pl/" as AdvancedTomato is only a graphic interface enhancement.
