### ISSUE TITLE
Option tls-remote no longer in OpenVPN

### ISSUE THREAD

**Issue by Philio** [Jackysi/advancedtomato#359]
After updating to 140 which includes OpenVPN 2.4.1, the `tls-remote` option no longer works as it has been removed from OpenVPN (and was deprecated in the previous version).

It's a simple work around to fix:

* Disable "Verify server certificate (tls-remote)" option
* Add to custom config: `verify-x509-name <hostname> name`

Possible to update the UI or OpenVPN config file generation?

**Comment by ziraxas** [comment]
hi,

I found this issue and solution, too. I think the web gui produces the wrong config file with "tls-remote" instead of the new command "verify-x509-name". It should be a fast and easy fix.

**Comment by Jackysi** [comment]
But GUI doesn't produce any config files. Tomato Web handler (which works like an API) does that. So I can't do anything about that because I don't do changes to the web handler :/. Well trying not to
