### ISSUE TITLE
Upgraded from v132 to ATT V3.1-135 or V3.4-140  DMZ and DDNS WAN IP address do not work

### ISSUE THREAD

**Issue by GerGitHub** [Jackysi/advancedtomato#366]
I upgraded from v132 to tomato-R7000-AT-ARM-3.1-135-AIO-64K.trx. /... /R7000-AT-ARM-3.4-140-AIO-64K.trx        
But DMZ and DDNS WAN IP address do not work     
1.Port Forwarding does not work        
2.DMZ does not work     
3.in DDNS the Use IP WAN address always shows 0.0.0.0

the 3.1-132-AIO-64K.trx everything works fine

**Comment by Jackysi** [comment]
Clear NVRAM first. 

Secondly this is GUI project, I don't develop functionality of the router, firmware or anything related to that.  I'm guessing what ever issues you have are related to nvram or multi-wan features. I can't help you with that.
