### ISSUE TITLE
v.3.5-140 - NETGEAR R9000 - Native IPV6 from ISP option disappeared

### ISSUE THREAD

**Issue by tdx79** [Jackysi/advancedtomato#372]
I just discovered that new v.3.5-140 is missing the "Native ipv6 from ISP" option (which was available on previous v.3.5-140 version for Netgear R7000 in Basic menu -> ipv6).
I'm going to revert back to v.3.4-140 for now, hopefully it will be fixed on next version.
Kind regards,
Fabio

**Comment by Jackysi** [comment]
There is no missing feature. It was simply renamed to "DHCPv6 with Prefix Delegation"
