### ISSUE TITLE
DIR 868L 

### ISSUE THREAD

**Issue by mfar1984** [Jackysi/advancedtomato#373]
Hi sir,

i have issue with tomato24 after installation.

my router DIR868L appear page Firmware Upgrade after i install Tomato24.

When you see image 1.png. For Ethernet section, i already set segment static 192.168.0.1 for gateway. and appear Tomato24

![1](https://user-images.githubusercontent.com/33825287/33008065-7f6f6394-ce0c-11e7-9d9b-bdf95d88252b.png)

i try many time to upload the firmware but still appear pages like below 👎 

![2](https://user-images.githubusercontent.com/33825287/33008066-8089de1c-ce0c-11e7-8922-c62d76b759af.png)

Please help me for this issue.

tQ

**Comment by Jackysi** [comment]
This is not a support section? Cmon... https://linksysinfo.org
