### ISSUE TITLE
IP Traffic hostnames/ips shown in one sinle row after upgrade to 3.5-140

### ISSUE THREAD

**Issue by ulimarti** [Jackysi/advancedtomato#374]
The list of hostnames in the IP traffic menu are listed in a single row after upgrading to 3.5-140, see attached image.
![screencapture](https://user-images.githubusercontent.com/33886961/33109429-1b67c476-cf07-11e7-996d-371816577a6f.png)

**Comment by Jackysi** [comment]
https://github.com/Jackysi/advancedtomato-gui/commit/d31c7bd8abab870071bcc8ae5d18fb84217ed371
