### ISSUE TITLE
Unable to mount ext formatted HDD

### ISSUE THREAD

**Issue by andrdnl** [Jackysi/advancedtomato#376]
Hello,

I am having trobule mounting an USB HDD that is ext formatted on my Asus N18 router.

![image](https://user-images.githubusercontent.com/34215524/33527556-966d08fe-d85b-11e7-96d9-3071d8acd626.png)

i can't find anything in the log, this is the only relavant thing i guess...

> Dec  3 15:49:01 unknown kern.warn kernel: [<c004213c>] (PC is at __bug+0x1c/0x28)
Dec  3 15:49:01 unknown kern.warn kernel: [<c004213c>] (__bug+0x1c/0x28) from [<c006e2cc>] (mod_timer+0x1b8/0x1c8)
Dec  3 15:49:01 unknown kern.warn kernel: [<c006e2cc>] (mod_timer+0x1b8/0x1c8) from [<bf52399c>] (init_once+0xd0/0x11c [ext4])
Dec  3 15:49:01 unknown kern.warn kernel: [<bf52399c>] (init_once+0xd0/0x11c [ext4]) from [<bf5241e0>] (ext4_freeze+0x118/0x128 [ext4])
Dec  3 15:49:01 unknown kern.warn kernel: [<bf5241e0>] (ext4_freeze+0x118/0x128 [ext4]) from [<bf525484>] (ext4_error_inode+0x40/0xd4 [ext4])
Dec  3 15:49:01 unknown kern.warn kernel: [<bf525484>] (ext4_error_inode+0x40/0xd4 [ext4]) from [<bf52be44>] (ext4_ext_fiemap_cb+0x420/0x504 [ext4])
Dec  3 15:49:01 unknown kern.warn kernel: [<bf52be44>] (ext4_ext_fiemap_cb+0x420/0x504 [ext4]) from [<bf52c49c>] (ext4_ext_check_inode+0x24/0x30 [ext4])
Dec  3 15:49:01 unknown kern.warn kernel: [<bf52c49c>] (ext4_ext_check_inode+0x24/0x30 [ext4]) from [<bf517ce0>] (ext4_iget+0x564/0x690 [ext4])
Dec  3 15:49:01 unknown kern.warn kernel: [<bf517ce0>] (ext4_iget+0x564/0x690 [ext4]) from [<bf528310>] (ext4_fill_super+0x1b34/0x2830 [ext4])
Dec  3 15:49:01 unknown kern.warn kernel: [<bf528310>] (ext4_fill_super+0x1b34/0x2830 [ext4]) from [<c00cd3d0>] (get_sb_bdev+0x148/0x180)
Dec  3 15:49:01 unknown kern.warn kernel: [<c00cd3d0>] (get_sb_bdev+0x148/0x180) from [<bf522838>] (ext4_get_sb+0x20/0x84 [ext4])
Dec  3 15:49:01 unknown kern.warn kernel: [<bf522838>] (ext4_get_sb+0x20/0x84 [ext4]) from [<c00cc644>] (vfs_kern_mount+0x54/0x120)
Dec  3 15:49:01 unknown kern.warn kernel: [<c00cc644>] (vfs_kern_mount+0x54/0x120) from [<c00cc754>] (do_kern_mount+0x34/0xe4)
Dec  3 15:49:01 unknown kern.warn kernel: [<c00cc754>] (do_kern_mount+0x34/0xe4) from [<c00e3c94>] (do_mount+0x15c/0x770)
Dec  3 15:49:01 unknown kern.warn kernel: [<c00e3c94>] (do_mount+0x15c/0x770) from [<c00e4590>] (sys_mount+0x84/0xc4)
Dec  3 15:49:01 unknown kern.warn kernel: [<c00e4590>] (sys_mount+0x84/0xc4) from [<c003eac0>] (ret_fast_syscall+0x0/0x30)
Dec  3 15:49:01 unknown kern.emerg kernel: Code: e59f0010 e1a01003 eb0a723a e3a03000 (e5833000) 
Dec  3 15:49:01 unknown kern.warn kernel: ---[ end trace fa0efe4e39bafbb6 ]---

> 

thanks!

**Comment by Jackysi** [comment]
This is not AdvancedTomato issue I'm afraid. Please check out linksysinfo forums and Shibby's issues tracker on bitbucket. AdvancedTomato is GUI modification and has nothing to do with firmware behind it. That is based on work from other authors. For now at least.
