### ISSUE TITLE
UPS Monitor 

### ISSUE THREAD

**Issue by joksik** [Jackysi/advancedtomato#379]
Hi i use linksys e4200 lates your build 3.5-140 and when i go to site USB & NAS and UPS Monitor i have this errors:

**APC UPS Status**
/tmp/.wxMrQgHD: line 5: ./ext/cgi-bin/tomatoups.cgi: not found
**UPS Response**
/tmp/.wxnWdZ5y: line 5: ./ext/cgi-bin/tomatodata.cgi: not found

**Comment by Jackysi** [comment]
That's normal when you have UPS disabled
