### ISSUE TITLE
Wifi Password gets corrupted after saving

### ISSUE THREAD

**Issue by TheHellSite** [Jackysi/advancedtomato#384]
On the current AdvancedTomato build (3.5-140) for my asus rt-n18u I can't write my usual wifi password.
The following text is not my password, but it will show the bug just fine.

%WIFI$12§34$WIFI% ---> The field "wl_wpa_psk" is invalid. Please report this problem.
This password gives me the above text next to the save button and doesn't even save.

$Fr3e%1234%Fr3e$ ---> $Fr3e343e$
My password only contains $ and % as special characters.
And the % char gets replaced by this strange symbol.
To reproduce the error just type any password with % or § (maybe there are more characters that are bugged) and save it. Either reload the page or click on "Basic Settings --> Network". Then click into the shared key field. It should be corrupted.
![bug_1](https://user-images.githubusercontent.com/34900685/34396778-dad165cc-eb6f-11e7-8929-cfa769c0dec1.png)
![bug_2](https://user-images.githubusercontent.com/34900685/34396779-daf194a0-eb6f-11e7-8709-3cfcf3030150.png)

**Comment by Jackysi** [comment]
Can you re-download image and re-flash it? There was some differences after 2 days of release and I didn't want to put whole new release number because I only changed the way special characters are handled. Other than that I have no idea what could it be, I have no problems.

**Comment by TheHellSite** [comment]
When did you release the latest image? I downloaded the currently flashed one on the 26th dec., I think.
But I can try downloading it again.

**Comment by Jackysi** [comment]
About a month ago. So that's probably not the case. Strange though, I tried to do that and it works fine here.

**Comment by TheHellSite** [comment]
I even cleared NVRAM after installing the update.

**Comment by Jackysi** [comment]
That has no effect on the problem though.
Can u try setting password via Shell / Telnet / SSH?

Something like "nvram set wl0_wpa_psk=password" it really depends on your router ( I don't know exact values ) and then see if it still shows wrong in GUI

**Comment by TheHellSite** [comment]
Doesn't work either! The password gets set, but extremely cut.
"nvram set wl0_wpa_psk=%Fre3$1234$Fre3%" will give me "e3".
Without special characters, it works fine.
I will try telnet now.

**Comment by Jackysi** [comment]
but did the login work via wifi? because otherwise its probably nvram limitation and can't be really fixed unless some one else does the fix. I develop gui only =)

**Comment by TheHellSite** [comment]
So I just tried it with telnet.
"%Fre3$1234$Fre3%" gets to "%Fre3%".
I will try the 3.4-140 release now. I know you are only doing a GUI but with the 3.4 release I could set that password just fine.

**Comment by TheHellSite** [comment]
Same bug on 3.4 release. Very strange.
I even tried different browsers and devices to set the password.
On the clients I get an authentication problem when the router has saved the corrupted password.

**Comment by VoxCodice** [comment]
The problem is that some of those special characters are used by the firmware. When you save the settings,  the router basically gets a string of text in the form of URL parameters such as 
`wl_wpa_psk=somePassword&someOtherSetting=someOtherValue&etc`
Notice that the "&" character is used to separate each setting. In this case the "&" is a special character and there are other such special characters that when you use in the password field, the router sees them as special characters.
To fix this, these characters need to be replaced with a code so that the router knows it's part of the password and not a special character. This is called encoding. For example, the "&" needs to be replaced with "%26". 

I'm going to open another issue and provide a temporary solution so that you can set a password as you want.

**Comment by TheHellSite** [comment]
Okay cool, thanks for pointing that out!

**Comment by TheHellSite** [comment]
@Jackysi 
I just tried the standard "1.28.0000 MIPSR2-140 K26 Max" build from shibby. No problems there.

**Comment by Jackysi** [comment]
Fixed.

**Comment by mmartoccia** [comment]
Is this correction in a release yet?
