### ISSUE TITLE
Low contrast with input fields

### ISSUE THREAD

**Issue by joytrekker** [Jackysi/advancedtomato#388]
Please add some contrast to the input fields. It's much easier to read the pages when inputs have a background color. I recommend using the background color #F1F4F5 for the light themes. 
EDIT: should go under the gui repository but there is no issue tracker.

**Comment by Jackysi** [comment]
The fields are just fine. I actually wanted to remove the background and leave simply bottom border but then decided to leave borders intact. Also I have SRGB calibrated monitor and I can see fields perfectly fine
