### ISSUE TITLE
Restore Configuration Dialogue Bug

### ISSUE THREAD

**Issue by docklandsstudios** [Jackysi/advancedtomato#389]
Linksys E2500v3
AdvancedTomato 3.5-140
Opera Browser (not an issue with Firefox)

- when clicking on the Browse button to locate the Backup, no dialogue opens.

![screen shot 1](https://user-images.githubusercontent.com/764560/35183418-ac350630-fddd-11e7-9ba7-dea15bd8c755.png)

**Comment by Jackysi** [comment]
Interesting, I can not replicate this issue. All file input dialogs use the same code, can you try them on different pages (e.g. restore bandwidth/ip traffic)? I see no way how this would happen, unless there is a browser issue with detecting mouse location/touch location
