### ISSUE TITLE
IP Traffic screen visual bug

### ISSUE THREAD

**Issue by OpticNerve75** [Jackysi/advancedtomato#390]
Since the last update (3.5-140) there has been a visual issue on the IP Traffic screen.  The list of machine/devices/IP addresses now scrolls endlessly across the screen to the right.  With previous versions, this behaved correctly and displayed as multiple lines.

I have attached a screenshot to show the issue.  I have drawn a red line through the names and IP address of all my devices, but you can still see that the list of devices continues off the screen.  I can scroll the web browser to the right to view all of my devices (a LONG way!).

I've tried various browsers and they all do the same thing (Chrome, Edge etc).  I have a friend who also runs Advanced Tomato on his R7000 and he has the exact same issue since installing 3.5-140.

![iptraffic](https://user-images.githubusercontent.com/35950275/35551926-9f66f0fc-05e5-11e8-859f-2d094bc478b2.png)

![iptraffic2](https://user-images.githubusercontent.com/35950275/35552082-6dcb1270-05e6-11e8-9873-61f0676440e4.png)

**Comment by Jackysi** [comment]
Fixed here: https://github.com/Jackysi/advancedtomato-gui/commit/d31c7bd8abab870071bcc8ae5d18fb84217ed371
