### ISSUE TITLE
modprobe bcm_nat

### ISSUE THREAD

**Issue by hirenshah** [Jackysi/advancedtomato#391]
Asus RT-N66U
Tomato v1.28.0000 MIPSR2-3.5-140 K26AC USB AIO-64K

I read online that I would increase the WAN speed by running the below:
`modprobe bcm_nat`

But I get:
`modprobe: module bcm_nat not found in modules.dep`

Am I missing something here?

**Comment by Jackysi** [comment]
Depends on router, ARM/ARM7 and RT-N are different. But generally enabling CTF does the same on most devices. The mentioned module was not compiled into newer routers if I'm correct. Maybe check forums about this. Defo not Advanced Tomato problem

**Comment by hirenshah** [comment]
I found out that the N5x version has it in, but the AC6x doesn't. I would need to downgrade for it to be available.
