### ISSUE TITLE
Downgrading from 6x to 5x

### ISSUE THREAD

**Issue by hirenshah** [Jackysi/advancedtomato#392]
Is a NVRAM wipe required?

**Comment by Jackysi** [comment]
I have no idea what are you trying to downgrade from? 6x to 5x?

**Comment by hirenshah** [comment]
Apologies, should have been clearer... from AC6x to N5x versions of the firmware.

This is linked to my other message about bcm_nat because the option is not available on the N66U router when on the AC6x firmware.

**Comment by Jackysi** [comment]
Wipe is always required. Specially at such big changes as switching firmware drivers (AC6x vs N5x are mostly changes in drivers and have nothing to do with "firmware version") =)
