### ISSUE TITLE
Truncated code in #nas-usb.asp page

### ISSUE THREAD

**Issue by toulousain79** [Jackysi/advancedtomato#397]
Hello,

I want to report a bug on the "nas-usb. asp" page for the "Run after mounting" and "Run before unmounting" fields.
It is impossible to insert the code you want. This is truncated when you save the changes.
The insertion works perfectly with the original Shibby's firmware.

For example, I would want insert this code:

case "$1" in
	'/opt')	[ -f "$1/root/SCRIPTs/USB_AfterMounting.sh" ] && sh $1/root/SCRIPTs/USB_AfterMounting.sh;;
esac

But, the result is:

case "$1" in
	'/opt')	[ -f "$1/root/SCRIPTs/USB_AfterMounting.sh" ]

Regards

**Comment by Jackysi** [comment]
Yeah, this is exactly the same issue as here (same function is used to work with text input): https://github.com/Jackysi/advancedtomato/issues/385.
Thanks for taking time and reporting.
