### ISSUE TITLE
R8000 Shibby-->Advanced (UI Issue)

### ISSUE THREAD

**Issue by Sideflare** [Jackysi/advancedtomato#399]
went from this *working
tomato-R8000-ARM--140-AIO-64K.trx

to this
tomato-R8000-AT-ARM7-3.5-140-AIO-64K.trx

router still works great but no UI...

looks like this   

![screen shot 7](https://user-images.githubusercontent.com/20179414/36932031-d6baa850-1e77-11e8-9a4b-5ac7d15c1dfb.jpg)

i click administration and this...

![screen shot 6](https://user-images.githubusercontent.com/20179414/36932022-a0a8396c-1e77-11e8-8ca6-92be6bb01711.jpg)

**it will allow me to select a new file but clicking the upgrade button yields no results.**

performed several normal reboots through the ui... it allowed me to....   saw the wifi drop off so i know that worked. ui still the same...

things could have been alot worse lol....

any ideas for next action?

**Comment by Jackysi** [comment]
Reset browser cache (look online how to do that).
