### ISSUE TITLE
Unable to enter settings in virtual wirless

### ISSUE THREAD

**Issue by scassarGitHub** [Jackysi/advancedtomato#4]
I

I'm trying to configure a guest wireless vlan with no access to my personnal network.

I've created a specific vlan 3 on LAN1 br1, with a DHCP...

When I go in "Advanced Settings->Virtual Wireless", I can create wl0.1 on LAN1 but the "save" button is not working. In addition,  for wl0.1 settings, all fileds are displayed (shared keys, radius server, encryption, passphrase, WDS...) even if I choose "Acces Point" and no security.

Thx for your help.

Tomato Firmware 1.28.0000 MIPSR2-2.01.20 K26AC USB AIO-64K
Asus RT-N66U

**Comment by Jackysi** [comment]
This issue is being investigated, thank you for report!
