### ISSUE TITLE
WhatsApp Video and Call not working

### ISSUE THREAD

**Issue by G0n3D** [Jackysi/advancedtomato#402]
Hi here,
I have the latest version of Advancedtomato =>  Version: 3.5-140 on R7000

I have issue with WhatsApp application on my iPhone in Wifi.
The video call and voice call not working.

Regards,

**Comment by Jackysi** [comment]
Sincerely doubt that's Tomato's fault in any way.

**Comment by G0n3D** [comment]
You kidding me ? i have try with another fw and another router and work good...
I think the problem is on this section:
![image](https://user-images.githubusercontent.com/7012051/41536140-bb78bf00-72d2-11e8-8a08-3e71f48ebad3.png)
Please reopen the issue....

**Comment by Jackysi** [comment]
You just contridicted your self. Another fw/router... AdvancedTomato is gui modification of Tomato by Shibby. If you can prove it works on Tomato by Shibby version 140 on same router then I can re-open it. Otherwise Linksysinfo forums, not AT issues tracker (GUI only!!!!)

**Comment by G0n3D** [comment]
With Netgear fw for R7000 and AsusMerlin i dont have this issues.

With Bell Router also same thing....

I have this version : Tomato Firmware 1.28.0000 -3.5-140 K26ARM USB AIO-64K
