### ISSUE TITLE
Ampersand in SSID

### ISSUE THREAD

**Issue by esiefker** [Jackysi/advancedtomato#403]
My building's wifi has the SSID 'M&M-5GHZ'.  I have no control over this.  

AdvancedTomato chokes on the ampersand.  When I enter the SSID literally, it truncates the SSID to 'M'. Putting quotes around the SSID still truncates it to '"M'. 

If I set the SSID to 'M%26M-5GHZ', the GUI shows 'M&M-5GHZ' but does not connect.  I suspect it is using 'M%26M-5GHZ' as the SSID, but the GUI is rendering the '%26' as '&'.  

Special characters in SSIDs may be unwise, but they are allowed by the standard so I think this is a bug.  Are there existing ways to escape special characters, or am I stuck until this is fixed?

If it matters, I have an RT-AC3200 running RT-AC3200-AT-ARM7-3.5-140-AIO-64K.trx.  Thanks

**Comment by Jackysi** [comment]
Same issue as others
