### ISSUE TITLE
Special characters in vpn client password

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#404]
The VPN client won't save a password with special characters. In my case, only the portion of the password up to the first special character (an ampersand '&') in my vpn password was saved by the gui in nvram. This was causing the vpn client to receive auth_failed responses when attempting to connect. Dumping the nvram showed that the vpn client password was truncated up to the first ampersand. My password has other special characters, so it's possible that it won't like others as well. I also used the system shell command function in the gui to retrieve the vpn client password (nvram get vpn_client1_password); this confirmed that my password was getting truncated. I attempted to set the password via the shell using the 'nvram set vpn_client1_password={password here}' command, but the same result occurred: the password was truncated up to the first special character.

For now I will have to change my vpn password and remove all special characters...

This issue seems similar to issue #403 

Thanks for advancedtomato and the great gui

UPDATE: after updating advancedtomato to latest version, i encountered the same issue. Changed vpn password to remove special characters and it now works fine.

**Comment by Jackysi** [comment]
Same issue as referenced above https://github.com/Jackysi/advancedtomato/issues/385
