### ISSUE TITLE
Special characters in wifi password 

### ISSUE THREAD

**Issue by tglu** [Jackysi/advancedtomato#407]
As a character of a WIFI shared key, the percent character % will cause the WIFI shared key string to end at the %, including itself, after saving the changes.  This will erase the percent character and anything following it.  It occurs both in Basic / Networking as well as Advanced / Virtual Wireless.

Asus RT-N16
MIPSR2-3.5-140 K26 USB AIO
Tested in Firefox 59.0.2 and Chrome 65.0.3325.181

This is similar to issues [403](https://github.com/Jackysi/advancedtomato/issues/403) and [404](https://github.com/Jackysi/advancedtomato/issues/404).

**Comment by Jackysi** [comment]
Its the same. Closed
