### ISSUE TITLE
Receive/Transmit Antenna is for linksys or asus system ?

### ISSUE THREAD

**Issue by allionWilliam** [Jackysi/advancedtomato#408]
Hi helper

I have an ASUS AC3200 and update advancedtomato successfully.
But in the advanced setting>>Wireless>>Receive/Transmit Antenna, I really don`t know it is functional or not.
With 6 external RF port on my access point, but the option to adjust only have  A/B/auto to choose.
There are some information saied this is the legacy for Linksys system, so it is available for ASUS? If not I think it should be removed from the ASUS series firmware.

Many thanks

**Comment by Jackysi** [comment]
Its functional. I don't know how it works exactly cause that's not my job to work on. You should take it up with Linksysinfo forums as this is not support section but issues tracker. AdvancedTomato issues, which is GUI only.
