### ISSUE TITLE
"wl_wps_psk" is invalid

### ISSUE THREAD

**Issue by theflx12** [Jackysi/advancedtomato#410]
Tenda W1800R
Version v3.5 - 140
updated around one month ago

Every time you change a WIFI setting (2,4 or 5 GHZ) and then try to "save" I get the following message:
The field "wl_wpa_psk" is invalid. Please report this problem.

I narrowed it down to the "&" letter I use in my password.

Since the last update it is not possible to use the "&" letter in a password you have to replace it with "%26". This is a good workaround but maybe there is a future fix.

![screenshot](https://user-images.githubusercontent.com/38971896/39614974-f3d9f828-4f73-11e8-9f7b-c980257cb1ed.JPG)

**Comment by Jackysi** [comment]
This is  getting tiresome... The issue has been marked as resolved 4x at least: https://github.com/Jackysi/advancedtomato/issues/385
