### ISSUE TITLE
R7000 - Port Forward not working with PPPoE WAN DHCP

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#411]
I'd like to setup port forwarding on the router, but because of my ISP settings I have to have DHCP box checked on my WAN settings because the service is dynamic.  It appears that this is preventing port forwarding from working  (according to other people describing the issue).  People with static IP's can uncheck this box and port forwarding will work... But that isn't an option for me.  Is there a fix or a workaround?

**Comment by Jackysi** [comment]
i don't know any thing about that. Should work. I've never heard anyone having issues with port forwarding. So please take it on linksysinfo forums. This is not support section.
