### ISSUE TITLE
ASUS RT-AC3200 kernel warning - dhd_prot_ioctl

### ISSUE THREAD

**Issue by tarblaster** [Jackysi/advancedtomato#412]
I have Advanced Tomato v3.5-140 VPN-64k on a ASUS RT-AC3200 and persistently get the following error in the logs:

May 31 11:07:51 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:51 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:51 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:51 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:07:55 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:08:00 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:08:00 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:08:00 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23 
May 31 11:08:00 raptor-host kern.warn kernel: dhd_prot_ioctl: status ret value is -23

**Comment by Jackysi** [comment]
This issue has nothing to do with AdvanceTomato it self. You should take it up with Linksysinfo forums as this is not support section but issues tracker. AdvancedTomato issues, which is GUI only.
