### ISSUE TITLE
Real Time IP Traffic Monitoring - List of IPs does not wrap properly

### ISSUE THREAD

**Issue by boktai1000** [Jackysi/advancedtomato#414]
When viewing the Real Time IP Traffic monitor, I've previously seen it either due to an older version of Advanced Tomato and Google Chrome at the time, that the list of connected devices on the LAN listed by hostname or IP Address would properly wrap when viewing.

Currently (and I've noticed this for probably a few months now, but just now am reporting it) it seems that the wrapping simply isn't working anymore, and instead Google Chrome would like to scroll all the way to the right to view these devices instead - meaning you're just seeing IP addresses with white space above and below and after selecting one, you've got to scroll all the way back left. I also tested this with Microsoft Edge and Internet Explorer and both browsers exhibited this problem as well.

My current versions that I'm able to replicate this with are as follows:

Netgear R7000
Google Chrome - Version 67.0.3396.99 (Official Build) (64-bit)
Windows 10 Build 1803
Tomato Firmware 1.28.0000 -3.5-140 K26ARM USB AIO-64K

**Comment by Jackysi** [comment]
https://github.com/Jackysi/advancedtomato/issues/405
