### ISSUE TITLE
Bricked WNDR3700v3

### ISSUE THREAD

**Issue by ThatMarko** [Jackysi/advancedtomato#421]
Used the latest available version of AdvancedTomato. After successful upload of the firmware, router restarted and entered a state of restart-loops. It was bricked. Successfully unbricked router using TFTP after enabling it via the serial port.

**Comment by Jackysi** [comment]
I don't see why would you post this on Issues tracker? I'm pretty sure its not Advanced Tomato's fault for the brick. Did you mark clear NVRAM after flashing?
