### ISSUE TITLE
Why does the Ping button have a Weibo logo?

### ISSUE THREAD

**Issue by geobio** [Jackysi/advancedtomato#426]
<img width="96" alt="screen shot 2018-11-12 at 6 14 50 pm" src="https://user-images.githubusercontent.com/9601962/48386486-fe49a900-e6a6-11e8-8be2-db59afc2667d.png">

^ The above icon next to "Ping" is the Weibo logo, which is odd. See:
https://www.google.com/search?q=weibo&tbm=isch

**Comment by Jackysi** [comment]
I like it that's why :D
