### ISSUE TITLE
Access restrictions should force MAC addresses to lowercase

### ISSUE THREAD

**Issue by mmindenhall** [Jackysi/advancedtomato#43]
Hello,

I found [this bug report](http://tomato.groov.pl/?page_id=334&bugerator_nav=display&bug_project=1&issue=195) that indicates "Access Restriction" addresses are case sensitive.  There's a comment that it's not a bug because _Linux is case sensitive_.  Regardless of whether this should be considered a bug in the firmare (I think it should), this feature is not working in Advanced Tomato.  I suspect it's because the GUI forces the MAC address entered to uppercase, whereas MAC addresses in Linux (e.g., if you type the command `ifconfig -a`) are always presented in lowercase.

Please change the GUI to force MAC addresses to lowercase instead of uppercase until this bug is fixed within Shibby Tomato.

I'm running the latest version (tomato-RT-AC68U-AT-ARM-2.6-127-AIO-64K.trx) on an Asus RT-AC68U.

Thanks for creating this great project!

**Comment by Jackysi** [comment]
If I am correct this is done automatically when values are read from NVRAM. So if that is not working this is Shibby issue. Forcing lowercase via GUI is doing a mess because later on when the initial problem is fixed I will forget about it.
