### ISSUE TITLE
Low Bandwith Gui

### ISSUE THREAD

**Issue by sshaikh** [Jackysi/advancedtomato#433]
At times I might need to log into the web gui externally (via a VPN, say). However over low bandwidth wan links the GUI proves to be problematic to use, mainly with timeouts.

Is there a low bandwidth mode or a way to increase timeouts or access static setting pages?

**Comment by Jackysi** [comment]
uff that's not possible... Perhaps you would want to switch to Fresh Tomato instead in this case.
