### ISSUE TITLE
New Tomato Firmware Netgear WNDR 4500 v1 Router

### ISSUE THREAD

**Issue by MaxPayneXL** [Jackysi/advancedtomato#435]
I am currently using Tomato Firmware 1.28.0000 MIPSR2-140 K26AC USB AIO-64K for my **Netgear WNDR 4500 v1** router. This firmware is 2 years old. The broadband speed is 100Mbps lower than while using the original Netgear  firmware.

May I know where could I find a new tomato firmware version for this model, if it is available?

Appreciate any help in this regard...

**Comment by Jackysi** [comment]
Its not available. You can switch forks and go with Fresh Tomato. Simple google "Fresh Tomato Firmware" will do.
