### ISSUE TITLE
Netgear R7000 boot loop

### ISSUE THREAD

**Issue by splinter007x** [Jackysi/advancedtomato#437]
Hi,

I dont have a problem with flashing r7000 to advanced tomato. but after i  configure the router settings to setup my WAN and LAN it ask for reboot , then after the reboot it begin to infinite boot loop. 
any idea how to fix this problem?

**Comment by yumitsu** [comment]
Do 30/30/30 nvram reset. 
https://wiki.dd-wrt.com/wiki/index.php/Recover_from_a_Bad_Flash
