### ISSUE TITLE
dnsmasq custom configuration limited to 2048 characters ?

### ISSUE THREAD

**Issue by zjgithub** [Jackysi/advancedtomato#443]
Firstly thank you all for the great works. 

I flashed Asus RT-AC68U (RT-AC68U-AT-ARM-3.5-140-AIO-64K.trx) without problem, but when it comes to adding customer configuration for dnsmasq,  the webui gives error saying "limited to 2048 characters".

I hope this bug can be fixed in next build, because dnsmaq is very powerful and 2048 character limit seems really limiting its potential.

Thank you !

**Comment by zjgithub** [comment]
hmm, I just rebooted my router, and noticed that my manual modifications to /etc/dnsmasq are all gone.  So I guess manual changes to /etc/dnsmasq is not sticky. I need to save it to nvram variable dnsmasq_custom ...

**Comment by rampageX** [comment]
dnsmasq webui just need one line:
`conf-dir=/opt/etc/dnsmasq/custom/`

Then put all your custom config files of dnsmasq into /opt/etc/dnsmasq/custom/, no limited.

**Comment by zjgithub** [comment]
That's wonderful ! Thank you !

**Comment by Jackysi** [comment]
That is the best solution. Config limitation to 2048 lines is actually huge. The config is stored in NVRAM which is limited in size and when nvram gets full, it starts dumping out good data. I would say 2048 is safe and high limit, for extras use file system.
