### ISSUE TITLE
Netgear N8000 is not responding while update firmware tomato-R8000-1.28.AT-ARM7-3.5-140-initial-64K????

### ISSUE THREAD

**Issue by cbazeem12** [Jackysi/advancedtomato#447]
Hello, 
I were trying to updating the firmware-tomato-R8000-1.28.AT-ARM7-3.5-140-initial-64k,During the installation- router light were blinking - i waited 30 mints, now router is not responding at all. 
I think, i made this router bricked. !!
I read online about tfttp2.exe. i tried to reset router using static IP method and command for ping... there was nothing happening. ( server failed to connect)
I used ping command then i am getting respond for 30 sec from 192.168.1.1- TTL 100 for 4 times and then no respond.... 
I am still struggling to start this router. is there any way i can unbrick this router and go back to normal.... is any one can help and guide me to resolve this issue. ?

**Comment by Jackysi** [comment]
https://forum.dd-wrt.com/phpBB2/viewtopic.php?p=1050515
