### ISSUE TITLE
Collapsed navigation - request to make setting persistent

### ISSUE THREAD

**Issue by CyberSho** [Jackysi/advancedtomato#48]
Can you make "toggle collapsed navigation" persistent as setting in nvram and effective on all fresh opened tabs? I find its hint-like behavior extremely useful to browse different GUI tabs quickly.
You can resign from verical scrollbar in "Advanced Settings", too, I think - there are not so many options there, and it's better to have them all shown in submenu instantly. In "Administration" submenu resigning from scrollbar could lead to the submenu position change, so I don't know what would be better, maybe it's good as it is now.

**Comment by Jackysi** [comment]
This is issue tracker. For features requests and things like that please email me or use http://linksysinfo.org/.

Also "Collapsed Navigation" is already in the firmware. It does save to NVRAM. https://advancedtomato.com/demo/status-overview.asp#admin-access.asp (Default Navigation State option). I have no idea what vertical scrollbar are you talking about. I need screenshot or something.
