### ISSUE TITLE
Web Services Web Server page error when starting/stopping server

### ISSUE THREAD

**Issue by jbobthegreat** [Jackysi/advancedtomato#49]
Starting or stopping the nginx webserver results in an error page every time.  The server itself does successfully start and behaves normally, but I have to click on the web services link in the sidebar menu again to display the configuration settings.  This occurs every time I start or stop the server.  

![error](https://cloud.githubusercontent.com/assets/12220800/7445201/2e2c8a98-f16e-11e4-8b38-3337ad5599a6.PNG)

**Comment by Jackysi** [comment]
Thanks for report, can you include your AdvancedTomato version please?

**Comment by jbobthegreat** [comment]
I'm running 2.7-128 K26ARM USB AIO-64k on a Netgear R6250

**Comment by Jackysi** [comment]
Apologize for late response, fixed issue for next release.
