### ISSUE TITLE
Multiple IP Support

### ISSUE THREAD

**Issue by erenfro** [Jackysi/advancedtomato#5]
One thing lacking in Tomato in general is the lack of multiple IP support, in both assignment of the IP's and the firewall configuration..
Currently the only way to handle this in any respect is to manually create scripts on an opt mounted USB device or JFFS2.

It would be nice if the WebUI could account for a setup involving multiple static IPs and firewall settings for them as this would all be WebUI, I figured I would ask for this feature request since you are amazingly good at WebUI.

**Comment by Jackysi** [comment]
I'm not sure this is my area of expertise. I'm more of a GUI guy than Tomato developer. What I mean is my skills end at HTML, CSS, Javascript and PHP. I haven't yet got the skills to implement such feature but you could ask Shibby and he'd consider it.
