### ISSUE TITLE
Use d3.js for charting

### ISSUE THREAD

**Issue by baskinomics** [Jackysi/advancedtomato#51]
Just a suggestion, I'd be happy to contribute.

**Comment by Jackysi** [comment]
I don't understand charting libs enough to know how to properly draw charts via live info. I tried with like 3 chart libs and I couldn't figure out how to draw/delete lines like Tomato has with as best optimized code as possible. Also D3 charts are not my thing, I prefer Flot Charts and High Charts. If you have knowledge and you would like to share it with me, I would very much appreciate.
