### ISSUE TITLE
DHCP Problem on only 2.4Ghz WiFi

### ISSUE THREAD

**Issue by MaartenMol** [Jackysi/advancedtomato#53]
Hello,

Since I use AdvancedTomato I have a bug with my 2.4 wifi and dhcp server.

Netgear R7000 acts as router
Windows Server 2012 R2 acts as DNS, DHCP, DC server.

After around 4 days when a client connects to my 2.4ghz wifi , they don't get an IP. However at the same time when clients connect to the 5.0ghz wifi they do get an IP from the Microsoft DHCP server.

So what is my work around? Go to "Advanced Settings" -> "Virtual Wireless" don't change anything just hit save. Then it says it reboots some services, then I connect a client to 2.4ghz wifi and it works fine again!

But I get a little tired doing this every so much days. I would like to know what services are being restarted at that time so I can create a schedule for like every night. I thought it would be "service wlan restart" but when I enter this in "Tools" -> "System Commands" it doesn't solve my problem like the save button does. Or this is some other command?

So can someone help me with this?

**Comment by Jackysi** [comment]
This is AdvancedTomato GUI issues tracker so its not really meant for questions or help, please try here: http://www.linksysinfo.org/
