### ISSUE TITLE
WDS for DIR-868L

### ISSUE THREAD

**Issue by Kiwi8** [Jackysi/advancedtomato#54]
Hello there!

I have difficulties getting WDS to work for a pair of DIR-868L, even when following the WDS instructions for Tomato.

Is there any issue with WDS for DIR-868L for the Tomato code?

**Comment by ryansch** [comment]
This project is just for the GUI replacement.  From the contact page:
`Note: This is not a support section. Please only contact me if your suggestion / question is related to the Graphical Interface.`

**Comment by Jackysi** [comment]
Thank you ryansch! I stopped bothering responding to such requests or contact emails, its just waste of time :)
