### ISSUE TITLE
OpenVPN client stop/start lands on vpnclient.asp

### ISSUE THREAD

**Issue by tparvu** [Jackysi/advancedtomato#55]
I recently updated to 1.28.0000 -2.8-130 K26ARM USB AIO-64K on an Asus RT-AC68R/U.

When I start or stop an OpenVPN client instead of reporting the status I land on http://10.10.10.1/vpn-client.asp which just displays 2 buttons, "save" and "cancel".

![image](https://cloud.githubusercontent.com/assets/13166222/8499607/42a34a18-215a-11e5-97bb-245562c5e1e4.png)

The buttons don't appear to do anything. The OpenVPN client will start/stop as can be seen by going to the status URL. It doesn't matter if you hit the buttons or do nothing at all. 

This happens every time I start or stop an OpenVPN client. 

Thanks for the great software. The stock Asus firmware was unstable and frustrating. Router is working great with AdvancedTomato!

**Comment by Jackysi** [comment]
I will fix this in next release, thanks for report :)

**Comment by tparvu** [comment]
Thanks much!

**Comment by Jackysi** [comment]
No problem, thank you! fixed :)
