### ISSUE TITLE
OpenVPN client fails to configure, Invalid IP and Port errors

### ISSUE THREAD

**Issue by SenorLAN** [Jackysi/advancedtomato#56]
When I try to save the configuration for the OpenVPN client (client 1 or 2), I receive two errors: "Invalid IP Address" and "Invalid Number. Valid Range: -1-32767."

![capture5](https://cloud.githubusercontent.com/assets/8877311/8714736/0cd018ba-2b3e-11e5-9795-ea04d092e97f.JPG)
![capture6](https://cloud.githubusercontent.com/assets/8877311/8714737/0dce55ec-2b3e-11e5-90db-7ff845192fac.JPG)

This was the first time to configure the OpenVPN clients on this router. The initial config seems to save fine, but then any further changes to the setup (i.e. protocol, port, or custom configuration)  give the two errors and do not save.  

My VPN provider is AirVPN and authentication is done with certificates. Below are the configuration pages as configured. 
![capture1](https://cloud.githubusercontent.com/assets/8877311/8714688/91bf558c-2b3d-11e5-8d12-824df122671b.JPG)
![capture3](https://cloud.githubusercontent.com/assets/8877311/8714691/95324d50-2b3d-11e5-83df-254c76ba094c.JPG)
![capture4](https://cloud.githubusercontent.com/assets/8877311/8714721/ea35ccc8-2b3d-11e5-853e-acb50cad8bfa.JPG)

Troubleshooting: 
If I change the Authorization Mode to Static Key and fill in any IP addresses into the Local/Remote endpoint fields then I no longer get the IP address error, but I still get the port error.
If I change the Server Address/Port port# it has no effect on the errors. 
I tried using VPN Client 2 to set up the same configuration and I receive the same errors with that client as well. 

I am using MIPSR2-2.8-130 K26 USB AIO on an ASUS RT-N16. This router was stock ASUS firmware before loading this AdvancedTomato build. All instructions to clear the NVRAM and any stored configs were followed as part of the flashing/conversion process. 

The router works fine in all other regards that I am aware of. The configuration was validated against the VPN provider guide for setup on Tomato. The VPN provider works fine if I use a desktop client or my PFSense server to connect to it.

**Comment by NYPD** [comment]
I could perhaps be running into sort of the same issue, but my problem is the inability to start the client.  I'm using the latest 2.9-131 on the R7000. I still need to test more and actually see if i can narrow something down.

**Comment by HuffYk** [comment]
similar issue here - running Tomato Firmware 1.28.0000 MIPSR2-3.1-132 K26 USB AIO on Asus NT16. When I have configured just Server nr.1 as TUN everything works fine. I wanted to start also Server nr.2 as TAP. After pasting keys it seems nvram got overwritten somewhere. I lost port setting in Server nr.1 and was not able to recover. Even after correcting port in Server nr.1 and starting it, it reverted back to empty value. I have received also same weird messages regarding missing port or incorrect value in TLS Renegotiation Time which was removed also. I had to restore old configuration to at least have Server nr1. running.

**Comment by Knifa** [comment]
Same issue here. Tomato Firmware 1.28.0000 MIPSR2-3.3-138 K26 USB AIO.

**Comment by gmordovin** [comment]
In my case, the second error "Invalid number ..." appears to be not for a port number, but for "Connection retry" entry.

**Comment by nfonseca** [comment]
Same issue running on Tenda N6 Tomato Firmware 1.28.0000 MIPSR2-3.4-138 K26 USB TendaN6
Is there any fix workaround ?

**Comment by nfonseca** [comment]
I have noticed that nvram is full when I get that error

![image](https://cloud.githubusercontent.com/assets/9517624/21117971/d0a7229a-c0b3-11e6-9931-18d2b0e7b645.png)

**Comment by nfonseca** [comment]
I found out out to workaround this bug. if you free up space on NVRAM by deleting some PortForwarding rules that are set up as examples, you won't have that problem anymore.
I think it's because the nvram gets full.

**Comment by gmordovin** [comment]
>  if you free up space on NVRAM by deleting some PortForwarding rules that are set up as examples, you won't have that problem anymore.

Thanks, man! It works!
Tomato Firmware 1.28.0000 MIPSR1-138 K26 USB VPN

**Comment by nfonseca** [comment]
Nice ! I think the NVRAM is a bit short on the Tenda N6 but deleting some unused stuff can help !

**Comment by Jackysi** [comment]
So if I understand properly, this is not actual issue =). NVRAM is actually "database" for all router options. Every command, script (admin scripts), port forward, etc... Is stored there. So 32kb isn't really big if you have long paths, lots of scripts, many additional commands and so on. Sadly some routers don't have enough storage available to have more NVRAM (Tenda N6 in this case). I stopped supporting 8mb flash size routers so honestly Asus RT-N16 and Tenda N6 are huge exceptions. 

I don't have much special stuff on my R7000 and my NVRAM usage is: 41.84 KB / 64.00 KB (65.37%)

**Comment by nfonseca** [comment]
As long we can bypass the issue freeing up some space it's OK. Anyway these devices are Home Router so they should not have a lot of Customizations. In my case I'm runing 91% nvram which makes it work as I want. Just don't stop supporting these devices. The Tomato Software is just great !

**Comment by nfonseca** [comment]
You can mark this as "not a bug" yes. It's a limitation of the NVRAM

**Comment by HuffYk** [comment]
NVRAM might be really an issue. I will try it later but even after removing examples from port forwarding I'm getting 93.25% NVRAM :(. Would be nice to have some feature in GUI as "NVRAM detailed usage" to see what exactly is consuming the space in NVRAM.

**Comment by nfonseca** [comment]
There are many other things you can clear to make the NVRAM thinner. Not only Port Forwarding. Look at QOS Rules :-)

**Comment by Jackysi** [comment]
Detailed NVRAM usage, not sure how would you show that, there is many different values (few hundred) only very few are actually large. In NVRAM is very simple database its almost as easy as "STRING = VALUE". You can export NVRAM and you will see which "value" is longest. Administration -> Debugging -> Dump NVRAM
