### ISSUE TITLE
CTF break NAT Loopback

### ISSUE THREAD

**Issue by stefauresi** [Jackysi/advancedtomato#57]
Hi ,

Is it possible to solve the problem with the nat loopback

I have a fiber connection to 1Gb / s, if CTF is off bandwidth = + -300mb / s and the nat loopback works
But If CTF is on bandwidth = + -900mb / s but the nat loopback is broken.

I tried with the latest version and the bug is present

Tested on RT-AC68U

Ps: with merlin firmware CTF on = nat loopback ok but i like your tomato firmware 

Best regards

Stéphane

**Comment by Jackysi** [comment]
As I replied to your email, this is not my area of expertise. I am not an Tomato developer, I only work on the GUI itself. For Tomato help please go to http://linksysinfo.org where you will get support from people who know much more than me. But as far as I know one of CTF functions is to disable NAT Loopback. However using SNAT might work through CTF.
