### ISSUE TITLE
Netgear R6300V2 2.4GHz issue

### ISSUE THREAD

**Issue by scifimike12** [Jackysi/advancedtomato#58]
I'm having a rather odd issue with my 2.4GHz band.  No matter what setting I choose (auto / N-only and 40 MHz channel width), I cannot get above 54Mbps.  It might show 450Mbps for a brief second when I apply settings but then it goes down to 54.  I've tested and confirmed that my wireless clients are stuck at their slow speeds too.

The 5GHz band runs fine but I noticed that there isn't an "AC-only" option, only "auto / A-only / N-only".  I'm using auto now and it runs above 500Mbps, so I'm getting the AC speeds.

![untitled](https://cloud.githubusercontent.com/assets/13596772/9020635/63724cee-37d5-11e5-9526-d97f9604916a.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/13596772/9020636/6386d560-37d5-11e5-845c-1beebba5282d.jpg)
![untitled3](https://cloud.githubusercontent.com/assets/13596772/9020637/8adc923a-37d5-11e5-873b-34905a52efe2.jpg)

**Comment by Jackysi** [comment]
Usually these issues are related to the wifi clients (if they don't support above 54mbps the whole antenna falls back to minimum 54mbps). Anyway I can't really help you with this because it is not GUI related issue. Please contact Shibby who's main developer of Tomato mod.
