### ISSUE TITLE
IP Traffic showing wrong units?

### ISSUE THREAD

**Issue by Swiftnesses** [Jackysi/advancedtomato#60]
Hello,

I'm running the latest version (131) on my R7000.

The issue I'm having is that the units on the IP Traffic graphs do not seem to match the actual data throughput. When running a speedtest from my Macbook (14Mbps up, 1Mbps down) the graphs do not show more than 7 KB/s...

What could cause this?

**Comment by Jackysi** [comment]
More info regarding this issue should be presented. At this time IP Traffic works fine for me and I can't reproduce your problem so please provide more details.
