### ISSUE TITLE
Can not save Nework seting when using 4G/LTE

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#62]
I just installed today the AdvanceTomato and I love it. I have till now just one small issue with the "Basic Settings -> Network". I run the 4G/LTE Mode which works fine as I had the previous settings still there. Now I wanted to add an additional network, but I can not save it as it complains by the field PPTP Gateway which can not be empty. But there isnt any PPTP Gateway for 4G/LTE. when I put there in the 0.0.0.0 it complains about the L2TP Server. If I do there the same than I can save the settings. No I believe those options needs to be removed from 4G/LTE configuration.

**Comment by Jackysi** [comment]
This was fixed in version 3.0-132. Apologies for late response!
