### ISSUE TITLE
Device list full of strange entries

### ISSUE THREAD

**Issue by pboschi** [Jackysi/advancedtomato#64]
I've just upgraded to latest version (2.9-131) on a Linksys E4200-1, and now the "Device list" page is full of strange entries:
![advanced_tomato_devices_list](https://cloud.githubusercontent.com/assets/14005124/9531569/dcebe5bc-4d06-11e5-9802-475cd900a7df.png)

Also tried to clear NVRAM, but nothing changed.

**Comment by Jackysi** [comment]
That's strange but it's unrelated to AdvancedTomato it self. The detection of devices is happening on Tomato itself and I am only a Graphical User Interface programer where I don't change or work on functions like that. Please in future post such problems to Shibby or http://linksysinfo.org/ forums where actual developers can help you out. Thank you for reporting though.
