### ISSUE TITLE
help: restore stock firmware tenda n60 and speedtest

### ISSUE THREAD

**Issue by 0pt1cal** [Jackysi/advancedtomato#66]
how to return the stock firmware after Tomato?

**Comment by 0pt1cal** [comment]
I installed the firmware from this site http://tomato.groov.pl/download/K26RT-N/build5x-131-EN/Tenda/
stock firmware speed on speedtest.net 600-700mbit / s firmware tomato 150mbit / s or download speedtest.net. why is that? whether there is the same problem with the speed in advanced tomato?

**Comment by Jackysi** [comment]
What the fuck man, this is not support section and read the damn FAQ.
