### ISSUE TITLE
Asus AC56 - unable to commit a file to NVRAM

### ISSUE THREAD

**Issue by jafisher5** [Jackysi/advancedtomato#67]
ASUS AC56-U
1.28.0000 -2.9-131 K26ARM USB AIO-64K

Trying to enable multiple users and write the /etc/passwd.custom and /etc/samba/smbpasswd files to nvram using:
nvram setfile2nvram /etc/passwd.custom
nvram setfile2nvram /etc/samba/smbpasswd
nvram commit

Files dont seem to commit to nvram, also tried using the /tmp/etc path instead, but either way, free space does not change in nvram and rebooting does not preserve these files.  Verified enough space in nvram available to store the two files which only contain a couple lines each. Maybe I'm missing something but I swore this was the same path I took to enable it on a Shibby build in the past.

Tried to clear the nvram from the gui (thorough) and retried but no change.

**Comment by Jackysi** [comment]
I can't offer support for these sort of issues. I am only GUI developer.
http://tomato.groov.pl/ && http://www.linksysinfo.org/index.php?forums/tomato-firmware.33/
