### ISSUE TITLE
PPTP Inbound client connection dropped when logging inbound traffic

### ISSUE THREAD

**Issue by SimplyAutomationized** [Jackysi/advancedtomato#69]
When enabling connection logging for inbound traffic any new clients to the pptp vpn will be dropped. (current connected clients will stay connected until they reconnect. resulting in a drop).
Even after the pptp server is restarted the clients can't connect unless I disable inbound connection logging for drops.

<img width="609" alt="screen shot 2015-09-13 at 9 54 58 pm" src="https://cloud.githubusercontent.com/assets/5528920/9842373/1c0ea8de-5a62-11e5-8d31-d17ef48672c6.png">

<strong>Tomato Firmware 1.28.0000 MIPSR2-2.9-131 K26 USB Mega-VPN
Model   Linksys E4200 v1
Chipset Broadcom BCM4716 chip rev 1 pkg 10
CPU Freq    480MHz
Flash Size  16MB
Details of IPTABLES, netstat, and processes:
</strong>
<img width="655" alt="screen shot 2015-09-13 at 9 48 39 pm" src="https://cloud.githubusercontent.com/assets/5528920/9842314/5281bfa6-5a61-11e5-9694-74784c9c4f17.png">
<img width="1066" alt="screen shot 2015-09-13 at 9 48 56 pm" src="https://cloud.githubusercontent.com/assets/5528920/9842313/527ed32c-5a61-11e5-9ac0-84e519caf132.png">
<img width="977" alt="screen shot 2015-09-13 at 9 59 57 pm" src="https://cloud.githubusercontent.com/assets/5528920/9842437/e9af9cda-5a62-11e5-81a4-3209b37cb3db.png">
<img width="667" alt="screen shot 2015-09-13 at 9 59 47 pm" src="https://cloud.githubusercontent.com/assets/5528920/9842438/e9b2fbe6-5a62-11e5-9ef6-09bc16a994ba.png">

**Comment by Jackysi** [comment]
I am sorry to inform you this: The issue is not related to AdvancedTomato Interface but Tomato itself. Please address the issue to Shibby since he is the main developer of Tomato mods I only fork his work and create GUI for it.

**Comment by SimplyAutomationized** [comment]
OK thanks :-)
