### ISSUE TITLE
R6250 2.4Ghz issue

### ISSUE THREAD

**Issue by yuriew** [Jackysi/advancedtomato#70]
when my wireless clients connect to 2.4Ghz, the speeds will slow down.I tested it got speed no more then 100kB/s,but 5Ghz is works fine,possible reason is bcm43217  I guess.

v2.9-131 AIO

**Comment by Jackysi** [comment]
This issue is not related to AdvancedTomato Interface but Tomato itself. Please address the issue to Shibby since he is the main developer of Tomato mods I only fork his work and create GUI for it.
