### ISSUE TITLE
D-Link DIR-868L won't load .trx file

### ISSUE THREAD

**Issue by baltojeff** [Jackysi/advancedtomato#71]
I've downloaded the latest version, tomato-DIR868L-AT-ARM-2.9-131-special.trx, file and confirmed the checksum. When trying to upload the file to my router, I get the following error: 
![screenshot from 2015-09-16 19 41 55](https://cloud.githubusercontent.com/assets/14321773/9921402/2e63cdac-5cab-11e5-8bec-db1ee82e2cf7.png)
I've tried changing the file type to .bin and get the same error. Any thoughts as to what I should be doing different? Hardware v.A1 Firmware v1.09

**Comment by Jackysi** [comment]
I have no idea what could that be... Can you flash Shibby's images?
P.S:: Did you check MD5 checksum of downloaded file? it may be a corrupted file download

**Comment by aviadsp** [comment]
HI, I also have Dir-868L rev.a
I was install Advanced-tomato successfully in emergency login of the router.
file (tomato-DIR868L-AT-ARM-2.9-131-special.trx).

**Comment by Jackysi** [comment]
As far as I know DIR868L should be flashed via Emergency Login and not standard router GUI. So this is not an actual issue just incorrect way of flashing. Also I don't offer support for Tomato Firmware issues only Graphical Interface issues which are part of AdvancedTomato GUI.
