### ISSUE TITLE
MAC filtering affecting guest wireless

### ISSUE THREAD

**Issue by RoadkillSD** [Jackysi/advancedtomato#79]
I installed AdvancedTomato v1.28 on my Tenda W1800R and configured a VLAN and linked it to my eth1.1 (5Ghz) and eth1.2 (2.4Ghz) guest wireless profiles. They work but only if I either add a device to my MAC filter list to be allowed or turn off wireless filter altogether. The two guest profiles are not bridged to the other LAN that the main 5Ghz and 2.4Ghz profiles are on (LAN0); they are on their own VLAN (LAN1) in Access Point mode. I set it up just like this: http://somethingk.com/main/?p=323

Is there a way have the MAC filtering only on my primary wireless bands, not the guest wireless?

Thanks

**Comment by Jackysi** [comment]
This is not an support section. This bug is also related to Tomato and not AdvancedTomato (GUI). Please follow up at http://linksysinfo.org/
