### ISSUE TITLE
AdvancedTomato - NGINX Configuration Not Saving

### ISSUE THREAD

**Issue by BalajiKumarD** [Jackysi/advancedtomato#8]
For my Asus RT-N16 router, i am using AdvancedTomato firmware with a build no: 2.02.20 K26 USB AIO. When i set the configuration for enabling the server on start, server root path, custom configuration, the configuration is not saved, when i click on "SAVE" button. SAVE button is not resulting in any action. I checked it in Chrome as well as IE11. Behavior is same. Can someone guide, where can be the problem and how i can resolve it. Thanks.

**Comment by buddmeister** [comment]
I have the same issue multiple browsers.  Firefox, IE11, Chrome.
Router: Linksys E4200 V1
Firmware: 2.02.20 K26 USB AIO

**Comment by Jackysi** [comment]
I'm sorry I haven't answered yet, I will look into it as soon as possible.

**Comment by BalajiKumarD** [comment]
Can I upgrade to shibby latest firmware on top of AdvancedTomato, without checking the "After flashing, erase all data in NVRAM memory"? Will my router work normally with the configuration set through AdvancedTomato? Thanks.

**Comment by Jackysi** [comment]
Yes you can, please don't close the issue because its still there. When its fixed I will close it.

**Comment by BalajiKumarD** [comment]
sure. I will not close the issue. thanks a lot. Whether it will be closed in the next build of yours? How much time it will take to release the next build? Thanks.

**Comment by Jackysi** [comment]
Umm I can't say, it depends on my free time and if I already have enough bug fixes for new release.

**Comment by Jackysi** [comment]
Here we go, fixed. New update will be released by end of week :)

**Comment by BalajiKumarD** [comment]
Thanks alot for your excellent and prompt support.

**Comment by Jackysi** [comment]
No problem :)!
