### ISSUE TITLE
Tenda N60 - Bandwidth limit page, stating QOS is disabled when it is actually enabled.

### ISSUE THREAD

**Issue by cheater123** [Jackysi/advancedtomato#80]
QOS is enabled yet, file qos-qoslimit.asp is saying "QoS is disabled"

see http://imgur.com/a/6znMK

**Comment by cpdivers** [comment]
Same issue here using 1.9-131 K26ARM USB AIO-64K

**Comment by Jackysi** [comment]
Fixed in next release, closing.
