### ISSUE TITLE
VPN over PPTP not working (unrecognized option 'of')

### ISSUE THREAD

**Issue by Wurzelmann** [Jackysi/advancedtomato#83]
I'm using the latest build (1.28.0000 -3.0-132 K26ARM USB AIO-64K) on my Asus RT-AC56U and cannot get the VPN to work. I'm trying to enable the PPTP Client Configuration, but after starting the service, there's this message in the log:

```
Nov  2 15:45:44 unknown daemon.info pptp[2819]: Plugin pptp.so loaded.
Nov  2 15:45:44 unknown daemon.info pptp[2819]: PPTP plugin version 0.8.5 compiled for pppd-2.4.5, linux-2.6.36.4
Nov  2 15:45:44 unknown daemon.err pptp[2819]: In file /etc/vpn/options.vpn: unrecognized option 'of'
Nov  2 15:45:44 unknown daemon.info dnsmasq[2471]: exiting on receipt of SIGTERM
Nov  2 15:45:44 unknown user.debug preinit[1]: 182: pptp peerdns disabled
```

I tried connecting via SSH and checking out the file options.vpn but it doesn't exist, neither does its direcotry "vpn".

**Comment by Jackysi** [comment]
You should report this issue to Shibby. I don't modify or work on Tomato Sources. I only work on the Graphical Interface which has nothing to do with the message above! Thanks.
