### ISSUE TITLE
Starting/stopping VPN client redirects to https://x.x.x.x/service.cgi#vpn-client.asp instead of https://x.x.x.x/#vpn-client.asp

### ISSUE THREAD

**Issue by mdPlusPlus** [Jackysi/advancedtomato#85]
Starting/stopping VPN client redirects to https://x.x.x.x/service.cgi#vpn-client.asp instead of https://x.x.x.x/#vpn-client.asp which doesn't give a 404 error but a "Secured connection failed" warning under Firefox and a ERR_EMPTY_RESPONSE error under Chromium.

**Comment by hasafly** [comment]
I confirm this.

**Comment by Jackysi** [comment]
Srry for late response, I will check it out and fix it in next release

**Comment by jontis** [comment]
I was looking into this issue and understand you already have the solution.
May I suggest an enhancement related to this fix:
It would be great to be able to put in a friendly nickname for your vpn if you have two.

**Comment by tparvu** [comment]
Decided I should search the bugs before opening a new one. :)

This is the same as the issue #105 and #95 

Jontis makes a good point, it would be nice to be able to assign a friendly nickname for the two configurations.

**Comment by mdPlusPlus** [comment]
~~May I ask why this has been closed? I can't find a commit which would fix the issue.~~

Found the commit: https://github.com/Jackysi/advancedtomato-gui/commit/651d6f4369fa1f3d6f7260476d7c04976caf4a3f
