### ISSUE TITLE
QoS classification not sorting

### ISSUE THREAD

**Issue by eXim82** [Jackysi/advancedtomato#88]
In the classification section i cant change the sort by clicking on the title. Tested in chrome an edge, In the detail section of QoS it works.

NETGEAR WNR3500Lv2
3.0-132

**Comment by Jackysi** [comment]
Are you sure this works on original Tomato?

**Comment by eXim82** [comment]
Not tested on shibby tomato

**Comment by Jackysi** [comment]
I'm not sure if this is actual issue or not, I don't have time to test so this will wait a little. But thanks for report!

**Comment by Jackysi** [comment]
Fixed in GUI repository, will be fixed here in next release. https://github.com/Jackysi/advancedtomato-gui/pull/15
