### ISSUE TITLE
Transaction Mismatch on Linksys E3200

### ISSUE THREAD

**Issue by claabs** [Jackysi/advancedtomato#89]
I've had this issue on all of Shibby's builds and on the Advanced Tomato firmware. 

The log message that repeatedly appears is:

> unknown user.warn kernel: Transaction mismatch: expected:0xd485 got:0xd484 type: 1

A Google search reveals others have this issue exclusively on the E3200 as well. 

Around when the error appears, the wireless seems to stop connecting to devices. LAN still works, but wireless does not.

Here's my [syslog.txt](https://github.com/Jackysi/advancedtomato/files/36276/syslog.txt)

**Comment by Jackysi** [comment]
AdvancedTomato is FORK of Tomato by Shibby. The difference between Shibby/AdvancedTomato is user interface. Everything else is the same. However I do not have knowledge to mess with firmware it self so I let these things to pros like Shibby. What I'm saying is, please stop reporting issues like this on AdvancedTomato Github and rather contact original developer Shibby which may actually do a difference.
