### ISSUE TITLE
RT-N10U - Firmware to big - not enought space

### ISSUE THREAD

**Issue by like-a-freedom** [Jackysi/advancedtomato#93]
When I try to upgrage firmware to K26USB-1.28.AT-RT-N5x-MIPSR2-3.0-132-VPN.trx on my Asus RT-10U, the error show "File is too big to fit in MTD". RT-N10U have only 8 Mb flash but latest firmware is 8064 Kb. Is there way to compress firmware?

**Comment by Jackysi** [comment]
no, N10U support will be removed soon.

**Comment by like-a-freedom** [comment]
Ok, thx for answer!
