### ISSUE TITLE
"No data received" after stopping Open VPN Client

### ISSUE THREAD

**Issue by orange-buffalo** [Jackysi/advancedtomato#95]
#### Version
- 1.28.0000 -3.0-132 K26ARM USB AIO-64K, Asus RT-AC56U
#### Prerequisites:
- Running Open VPN Client
#### Test Case
- Go to VPN -> Open VPN Client -> Running Client
- Click "Stop"

ER: Page is updated with new client state
AR: HTTP error "No data received"

**Comment by Jackysi** [comment]
I was unable to replicate this issue, but I will leave it open for few more weeks to see of anyone else can confirm it.

**Comment by tparvu** [comment]
Oops, just noticed this issue, I just opened issue #105 I'll leave it up as I have a screenshot in there. I think the URL should be "/#vpn-client.asp" instead of "/service.cgi#vpn-client.asp" but that is just a guess on my part.

**Comment by Jackysi** [comment]
Okay this has been fixed in GUI repository: https://github.com/Jackysi/advancedtomato-gui/commit/651d6f4369fa1f3d6f7260476d7c04976caf4a3f 
When releasing next version this fix will be included in main GUI.

**Comment by orange-buffalo** [comment]
Great, thank you!
