### ISSUE TITLE
80Mhz broken on R6300v2

### ISSUE THREAD

**Issue by zorrobyte** [Jackysi/advancedtomato#96]
For some reason AdvancedTomato is stuck using 40Mhz widths on 5GHZ on a R6300v2. I set regulatory domain to USA and such, still capped at 600Mbit/40Mhz. Interestingly enough, flashing shibby then AdvancedTomato without clearing NVRAM "forces" 80Mhz mode if previously setup.

**Comment by zorrobyte** [comment]
Ugh, nevermind - user error.

Apparently one must clear the NVRAM in total when upgrading from the initial flash!

**Comment by Jackysi** [comment]
^^
