### ISSUE TITLE
Samsung smart tv loses connection to media server repeatedly (DLNA)

### ISSUE THREAD

**Issue by echoleaf** [Jackysi/advancedtomato#97]
I have a Netgear R7000 running Advanced Tomato Firmware 1.28.0000 -3.0-132 K26ARM USB AIO-64K.

Everything is working great except that my Samsung UN40EH5300 smart tv loses connectivity to the media server regularly. I have an 3TB Seagate hard drive connected to the Netgear via the USB 3.0 port. The tv is connected to the Netgear via ethernet cable.

Important: the tv does _not_ lose connection to the internet when it loses connection to the media server. We've watched Netflix/Hulu on the tv for hours without interruption. Playing a media file (on the tv) off the external hard drive usually lasts 20-40 minutes before the connection is dropped. 

To get the media server connection back, the tv must be restarted.

I've not noticed any connectivity issues with our laptops and the connected storage - all seems to be well for everything except the media server/TV combo.

Here are the enabled settings:
USB Support
- Core usb support
- usb 3 support
- usb 2 support
- usb storage support
- file system support: NTFS only
- ntfs driver: Paragon
- Automount: yes
- Attached Devices
  Type    Host    Description Mounted?
  Storage 0   Seagate Backup+ Desk
  Partition 'MegaDrive' ufsd (348.32 GB / 2,794.51 GB used) is mounted on /tmp/mnt/MegaDrive

Samba File Sharing
- Enabled:  Yes, no authentication
- Workgroup name: workgroup
- client codepage: unspecified
- auto-share all usb partitions: read/write
- options: Master Browser & WINS server
- Additional Shares List
  Share Name  Directory   Description Access Level    Hidden
  jffs    /jffs   JFFS    Read / Write    No
  root$   /   Hidden Root Read Only   Yes

FTP Server OFF

Media Server
- Enabled
- Port: 0
- Database location: RAM (temporary)
- strictly adhere to DNLA standards
- Media Directories
  Directory   Content Filter
  /mnt/MegaDrive  Video only

UPS monitor n/a

BitTorrent client disabled

Name    TomatoUSB
Model   Netgear R7000
Chipset ARMv7 Processor rev 0 (v7l)
CPU Freq    1000 MHz (dual-core)
Flash Size  128MB

**Comment by Jackysi** [comment]
I am sorry but this bug is related to Tomato it self and not AdvancedTomato Graphical User Interface. I know its hard to understand but this project is fork of Tomato by Shibby. This project is only Graphical User Interface change (which is actually the hardest part) but the core functionality is unchanged. So for support and issues reports on Firmware/Linux/Core please contact Shibby. I do not have enough knowledge to poke around Firmware.
