### ISSUE TITLE
Flashing was unsuccessful  (ASUS RT-N18U)

### ISSUE THREAD

**Issue by Lizingrider** [Jackysi/advancedtomato#98]
Today morning I tried to flash my ASUS RT-N18U router with latest advanced tomato firmware (RT-N18U-AT-ARM-3.0-132-AIO-64K.trx)

The original FW is: ASUS RT-N18U Firmware version 3.0.0.4.378.9216

A followed the flashing guide step by step, but after the restoring and restarting the router didn’t provide the login screen, just gave me an original ASUS HTML page which contained information (in Hungarian language)about, that the IP address changed and I have to refresh this page. (Or something similar) Some leds were flashing after restart. It happened after 10 minutes waiting too. 

Then I restored the original previous ASUS firmware (ASUS RT-N18U Firmware version 3.0.0.4.378.8041). I tried it again with the previous (not latest) ASUS firmware, but the situation was same.

Do you have any ideas about it or could you give me any advice to avoid unsuccessful flashing?

**Comment by Jackysi** [comment]
This is not a support section... http://www.linksysinfo.org/
