### ISSUE TITLE
no PPTP vpn server on advancedtomato.com for Asus RT-N18U

### ISSUE THREAD

**Issue by bartplessers** [Jackysi/advancedtomato#99]
Hi,
Thanx for Tomato firmware. I appreciate the good work done here!

Installed Advanced Tomato (https://advancedtomato.com) RT-N18U-AT-ARM-3.0-132-AIO-64K.trx on my Asus RT-N18U and everything is running fine.
However, when I try to connect to the PPTP-server from a Windows client, connection can not be made, it seems to time-out.
Previously with the original Asus firmware, there was no problem.

Is this a bug, or do I something wrong?
Settings of my PPTP-server:

![10-12-2015 9-53-31](https://cloud.githubusercontent.com/assets/10470708/11711030/ea3e3174-9f23-11e5-8004-cba3faa3695c.png)

Kind regards,
Bart

**Comment by Jackysi** [comment]
First of, this is NOT support section. It is BUG REPORTING ONLY. Secondly I can't help you with router firmware issues. I only work on GUI (Graphical User Interface). Basically the LOOKS and graphic design... Time outs, service issues, config issues that's all firmware related...
